package cl.servel.gasto.entity;
// Generated 11-03-2019 10:17:14 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CadCargaDatos generated by hbm2java
 */
@Entity
@Table(name = "cad_carga_datos")
public class CadCargaDatos implements java.io.Serializable {

	private Integer cadId;
	private EveEventoEleccionario eveEventoEleccionario;
	private String cadTipoCarga;
	private String cadEstadoCarga;
	private Date cadFechaInicio;
	private Date cadFechaTermino;
	private Set<ResumenCarga> resumenCargas = new HashSet<ResumenCarga>(0);

	public CadCargaDatos() {
	}

	public CadCargaDatos(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	public CadCargaDatos(EveEventoEleccionario eveEventoEleccionario, String cadTipoCarga, String cadEstadoCarga,
			Date cadFechaInicio, Date cadFechaTermino, Set<ResumenCarga> resumenCargas) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.cadTipoCarga = cadTipoCarga;
		this.cadEstadoCarga = cadEstadoCarga;
		this.cadFechaInicio = cadFechaInicio;
		this.cadFechaTermino = cadFechaTermino;
		this.resumenCargas = resumenCargas;
	}

	@SequenceGenerator(name = "CadCargaDatosIdGenerator", sequenceName = "cad_carga_datos_cad_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "CadCargaDatosIdGenerator")

	@Column(name = "cad_id", unique = true, nullable = false)
	public Integer getCadId() {
		return this.cadId;
	}

	public void setCadId(Integer cadId) {
		this.cadId = cadId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@Column(name = "cad_tipo_carga", length = 30)
	public String getCadTipoCarga() {
		return this.cadTipoCarga;
	}

	public void setCadTipoCarga(String cadTipoCarga) {
		this.cadTipoCarga = cadTipoCarga;
	}

	@Column(name = "cad_estado_carga", length = 15)
	public String getCadEstadoCarga() {
		return this.cadEstadoCarga;
	}

	public void setCadEstadoCarga(String cadEstadoCarga) {
		this.cadEstadoCarga = cadEstadoCarga;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cad_fecha_inicio", length = 29)
	public Date getCadFechaInicio() {
		return this.cadFechaInicio;
	}

	public void setCadFechaInicio(Date cadFechaInicio) {
		this.cadFechaInicio = cadFechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cad_fecha_termino", length = 29)
	public Date getCadFechaTermino() {
		return this.cadFechaTermino;
	}

	public void setCadFechaTermino(Date cadFechaTermino) {
		this.cadFechaTermino = cadFechaTermino;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cadCargaDatos")
	public Set<ResumenCarga> getResumenCargas() {
		return this.resumenCargas;
	}

	public void setResumenCargas(Set<ResumenCarga> resumenCargas) {
		this.resumenCargas = resumenCargas;
	}

}
	