package cl.servel.gasto.entity;
// Generated 14-05-2019 9:47:29 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * CelCelula generated by hbm2java
 */
@Entity
@Table(name = "cel_celula")
public class CelCelula implements java.io.Serializable {

	private Integer celId;
	private EveEventoEleccionario eveEventoEleccionario;
	private String celDescripcion;
	private boolean celActiva;
	private Set<GutGrupoUsuarioTarea> gutGrupoUsuarioTareas = new HashSet<GutGrupoUsuarioTarea>(0);

	public CelCelula() {
	}

	public CelCelula(EveEventoEleccionario eveEventoEleccionario, String celDescripcion, boolean celActiva) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.celDescripcion = celDescripcion;
		this.celActiva = celActiva;
	}

	public CelCelula(EveEventoEleccionario eveEventoEleccionario, String celDescripcion, boolean celActiva, Set<GutGrupoUsuarioTarea> gutGrupoUsuarioTareas) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.celDescripcion = celDescripcion;
		this.celActiva = celActiva;
		this.gutGrupoUsuarioTareas = gutGrupoUsuarioTareas;
	}

	@SequenceGenerator(name = "CelCelulaIdGenerator", sequenceName = "cel_celula_cel_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "CelCelulaIdGenerator")

	@Column(name = "cel_id", unique = true, nullable = false)
	public Integer getCelId() {
		return this.celId;
	}

	public void setCelId(Integer celId) {
		this.celId = celId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@Column(name = "cel_descripcion", nullable = false, length = 50)
	public String getCelDescripcion() {
		return this.celDescripcion;
	}

	public void setCelDescripcion(String celDescripcion) {
		this.celDescripcion = celDescripcion;
	}

	@Column(name = "cel_activa", nullable = false)
	public boolean isCelActiva() {
		return this.celActiva;
	}

	public void setCelActiva(boolean celActiva) {
		this.celActiva = celActiva;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "celCelula")
	public Set<GutGrupoUsuarioTarea> getGutGrupoUsuarioTareas() {
		return this.gutGrupoUsuarioTareas;
	}

	public void setGutGrupoUsuarioTareas(Set<GutGrupoUsuarioTarea> gutGrupoUsuarioTareas) {
		this.gutGrupoUsuarioTareas = gutGrupoUsuarioTareas;
	}

}
