package cl.servel.gasto.entity;
// Generated 27-11-2019 11:30:22 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConConfiguracion generated by hbm2java
 */
@Entity
@Table(name = "con_configuracion")
public class ConConfiguracion implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1L;
	private Integer conId;
	private EveEventoEleccionario eveEventoEleccionario;
	private TpoEleccion tpoEleccion;
	private TpoEvento tpoEvento;
	private String estado;
	private Date created;
	private Date modified;
	private Boolean conEliminado;
	private Boolean activo;
	private Boolean estadocarga;
	private Integer dexId;
	private Set<RlcConfiguracionParametro> rlcConfiguracionParametros = new HashSet<RlcConfiguracionParametro>(0);

	public ConConfiguracion() {
	}

	public ConConfiguracion(EveEventoEleccionario eveEventoEleccionario, TpoEleccion tpoEleccion, TpoEvento tpoEvento) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoEleccion = tpoEleccion;
		this.tpoEvento = tpoEvento;
	}

	public ConConfiguracion(EveEventoEleccionario eveEventoEleccionario, TpoEleccion tpoEleccion, TpoEvento tpoEvento, String estado, Date created, Date modified, Boolean conEliminado, Boolean activo, Boolean estadocarga, Integer dexId, Set<RlcConfiguracionParametro> rlcConfiguracionParametros) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoEleccion = tpoEleccion;
		this.tpoEvento = tpoEvento;
		this.estado = estado;
		this.created = created;
		this.modified = modified;
		this.conEliminado = conEliminado;
		this.activo = activo;
		this.estadocarga = estadocarga;
		this.dexId = dexId;
		this.rlcConfiguracionParametros = rlcConfiguracionParametros;
	}

	@SequenceGenerator(name = "cl.servel.gasto.entity.ConConfiguracionIdGenerator", sequenceName = "con_configuracion_con_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.entity.ConConfiguracionIdGenerator")

	@Column(name = "con_id", unique = true, nullable = false)
	public Integer getConId() {
		return this.conId;
	}

	public void setConId(Integer conId) {
		this.conId = conId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_eleccion_id", nullable = false)
	public TpoEleccion getTpoEleccion() {
		return this.tpoEleccion;
	}

	public void setTpoEleccion(TpoEleccion tpoEleccion) {
		this.tpoEleccion = tpoEleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_evento_id", nullable = false)
	public TpoEvento getTpoEvento() {
		return this.tpoEvento;
	}

	public void setTpoEvento(TpoEvento tpoEvento) {
		this.tpoEvento = tpoEvento;
	}

	@Column(name = "estado", length = 15)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_", length = 13)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified", length = 13)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "con_eliminado")
	public Boolean getConEliminado() {
		return this.conEliminado;
	}

	public void setConEliminado(Boolean conEliminado) {
		this.conEliminado = conEliminado;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Column(name = "estadocarga")
	public Boolean getEstadocarga() {
		return this.estadocarga;
	}

	public void setEstadocarga(Boolean estadocarga) {
		this.estadocarga = estadocarga;
	}

	@Column(name = "dex_id")
	public Integer getDexId() {
		return this.dexId;
	}

	public void setDexId(Integer dexId) {
		this.dexId = dexId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conConfiguracion")
	public Set<RlcConfiguracionParametro> getRlcConfiguracionParametros() {
		return this.rlcConfiguracionParametros;
	}

	public void setRlcConfiguracionParametros(Set<RlcConfiguracionParametro> rlcConfiguracionParametros) {
		this.rlcConfiguracionParametros = rlcConfiguracionParametros;
	}

}
