package cl.servel.gasto.entity;
// Generated 12-06-2019 11:13:58 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DacDetalleActividad generated by hbm2java
 */
@Entity
@Table(name = "dac_detalle_actividad")
public class DacDetalleActividad implements java.io.Serializable {

	private Integer dacId;
	private ActActividad actActividad;
	private DeaDefinicionActividad deaDefinicionActividad;
	private boolean dacActividadCompletada;

	public DacDetalleActividad() {
	}

	public DacDetalleActividad(ActActividad actActividad, DeaDefinicionActividad deaDefinicionActividad, boolean dacActividadCompletada) {
		this.actActividad = actActividad;
		this.deaDefinicionActividad = deaDefinicionActividad;
		this.dacActividadCompletada = dacActividadCompletada;
	}

	@SequenceGenerator(name = "DacDetalleActividadIdGenerator", sequenceName = "dac_detalle_actividad_dac_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "DacDetalleActividadIdGenerator")

	@Column(name = "dac_id", unique = true, nullable = false)
	public Integer getDacId() {
		return this.dacId;
	}

	public void setDacId(Integer dacId) {
		this.dacId = dacId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "act_id", nullable = false)
	public ActActividad getActActividad() {
		return this.actActividad;
	}

	public void setActActividad(ActActividad actActividad) {
		this.actActividad = actActividad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dea_id", nullable = false)
	public DeaDefinicionActividad getDeaDefinicionActividad() {
		return this.deaDefinicionActividad;
	}

	public void setDeaDefinicionActividad(DeaDefinicionActividad deaDefinicionActividad) {
		this.deaDefinicionActividad = deaDefinicionActividad;
	}

	@Column(name = "dac_actividad_completada", nullable = false)
	public boolean isDacActividadCompletada() {
		return this.dacActividadCompletada;
	}

	public void setDacActividadCompletada(boolean dacActividadCompletada) {
		this.dacActividadCompletada = dacActividadCompletada;
	}
}
