package cl.servel.gasto.entity;
// Generated 21-01-2019 10:12:03 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DarDetalleActaRecepcion generated by hbm2java
 */
@Entity
@Table(name = "dar_detalle_acta_recepcion")
public class DarDetalleActaRecepcion implements java.io.Serializable {

	private Integer darId;
	private AcrActaRecepcion acrActaRecepcion;
	private CanCandidato canCandidato;
	private ParPartido parPartido;
	private Date darCreated;

	public DarDetalleActaRecepcion() {
	}

	public DarDetalleActaRecepcion(AcrActaRecepcion acrActaRecepcion, CanCandidato canCandidato,
			ParPartido parPartido) {
		this.acrActaRecepcion = acrActaRecepcion;
		this.canCandidato = canCandidato;
		this.parPartido = parPartido;
	}

	public DarDetalleActaRecepcion(AcrActaRecepcion acrActaRecepcion, CanCandidato canCandidato, ParPartido parPartido,
			Date darCreated) {
		this.acrActaRecepcion = acrActaRecepcion;
		this.canCandidato = canCandidato;
		this.parPartido = parPartido;
		this.darCreated = darCreated;
	}

	@SequenceGenerator(name = "DarDetalleActaRecepcionIdGenerator", sequenceName = "dar_detalle_acta_recepcion_dar_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "DarDetalleActaRecepcionIdGenerator")

	@Column(name = "dar_id", unique = true, nullable = false)
	public Integer getDarId() {
		return this.darId;
	}

	public void setDarId(Integer darId) {
		this.darId = darId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "acr_id", nullable = false)
	public AcrActaRecepcion getAcrActaRecepcion() {
		return this.acrActaRecepcion;
	}

	public void setAcrActaRecepcion(AcrActaRecepcion acrActaRecepcion) {
		this.acrActaRecepcion = acrActaRecepcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "can_id", nullable = false)
	public CanCandidato getCanCandidato() {
		return this.canCandidato;
	}

	public void setCanCandidato(CanCandidato canCandidato) {
		this.canCandidato = canCandidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id", nullable = false)
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dar_created", length = 13)
	public Date getDarCreated() {
		return this.darCreated;
	}

	public void setDarCreated(Date darCreated) {
		this.darCreated = darCreated;
	}

}
