package cl.servel.gasto.entity;
// Generated 10-07-2019 17:11:40 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DdeDetalleDocumentosExternos generated by hbm2java
 */
@Entity
@Table(name = "dde_detalle_documentos_externos")
public class DdeDetalleDocumentosExternos implements java.io.Serializable {

	private Integer ddeId;
	private DexDocumentoExterno dexDocumentoExterno;
	private String ddeNombreDocumento;
	private String ddeMimeType;
	private String ddeIdRepositorioDocumental;
	private Date ddeCreated;
	private String ddeTipoDocumento;
	private String folio;

	public DdeDetalleDocumentosExternos() {
	}

	public DdeDetalleDocumentosExternos(DexDocumentoExterno dexDocumentoExterno) {
		this.dexDocumentoExterno = dexDocumentoExterno;
	}

	public DdeDetalleDocumentosExternos(DexDocumentoExterno dexDocumentoExterno, String ddeNombreDocumento,
			String ddeMimeType, String ddeIdRepositorioDocumental, Date ddeCreated, String ddeTipoDocumento,
			String folio) {
		this.dexDocumentoExterno = dexDocumentoExterno;
		this.ddeNombreDocumento = ddeNombreDocumento;
		this.ddeMimeType = ddeMimeType;
		this.ddeIdRepositorioDocumental = ddeIdRepositorioDocumental;
		this.ddeCreated = ddeCreated;
		this.ddeTipoDocumento = ddeTipoDocumento;
		this.folio = folio;
	}

	@SequenceGenerator(name = "cl.servel.gasto.temporal.DdeDetalleDocumentosExternosIdGenerator", sequenceName = "dde_detalle_documentos_externos_dde_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.temporal.DdeDetalleDocumentosExternosIdGenerator")

	@Column(name = "dde_id", unique = true, nullable = false)
	public Integer getDdeId() {
		return this.ddeId;
	}

	public void setDdeId(Integer ddeId) {
		this.ddeId = ddeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dex_id", nullable = false)
	public DexDocumentoExterno getDexDocumentoExterno() {
		return this.dexDocumentoExterno;
	}

	public void setDexDocumentoExterno(DexDocumentoExterno dexDocumentoExterno) {
		this.dexDocumentoExterno = dexDocumentoExterno;
	}

	@Column(name = "dde_nombre_documento", length = 300)
	public String getDdeNombreDocumento() {
		return this.ddeNombreDocumento;
	}

	public void setDdeNombreDocumento(String ddeNombreDocumento) {
		this.ddeNombreDocumento = ddeNombreDocumento;
	}

	@Column(name = "dde_mime_type", length = 200)
	public String getDdeMimeType() {
		return this.ddeMimeType;
	}

	public void setDdeMimeType(String ddeMimeType) {
		this.ddeMimeType = ddeMimeType;
	}

	@Column(name = "dde_id_repositorio_documental", length = 500)
	public String getDdeIdRepositorioDocumental() {
		return this.ddeIdRepositorioDocumental;
	}

	public void setDdeIdRepositorioDocumental(String ddeIdRepositorioDocumental) {
		this.ddeIdRepositorioDocumental = ddeIdRepositorioDocumental;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dde_created", length = 29)
	public Date getDdeCreated() {
		return this.ddeCreated;
	}

	public void setDdeCreated(Date ddeCreated) {
		this.ddeCreated = ddeCreated;
	}

	@Column(name = "dde_tipo_documento", length = 50)
	public String getDdeTipoDocumento() {
		return this.ddeTipoDocumento;
	}

	public void setDdeTipoDocumento(String ddeTipoDocumento) {
		this.ddeTipoDocumento = ddeTipoDocumento;
	}

	@Column(name = "folio", length = 20)
	public String getFolio() {
		return this.folio;
	}

	public void setFolio(String folio) {
		this.folio = folio;
	}

}
