package cl.servel.gasto.entity;
// Generated 11-03-2019 10:17:14 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DecDetalleCarga generated by hbm2java
 */
@Entity
@Table(name = "dec_detalle_carga")
public class DecDetalleCarga implements java.io.Serializable {

	private Integer decId;
	private ResumenCarga resumenCarga;
	private String decDescripcion;

	public DecDetalleCarga() {
	}

	public DecDetalleCarga(ResumenCarga resumenCarga) {
		this.resumenCarga = resumenCarga;
	}

	public DecDetalleCarga(ResumenCarga resumenCarga, String decDescripcion) {
		this.resumenCarga = resumenCarga;
		this.decDescripcion = decDescripcion;
	}

	@SequenceGenerator(name = "DecDetalleCargaIdGenerator", sequenceName = "dec_detalle_carga_dec_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "DecDetalleCargaIdGenerator")

	@Column(name = "dec_id", unique = true, nullable = false)
	public Integer getDecId() {
		return this.decId;
	}

	public void setDecId(Integer decId) {
		this.decId = decId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rec_id", nullable = false)
	public ResumenCarga getResumenCarga() {
		return this.resumenCarga;
	}

	public void setResumenCarga(ResumenCarga resumenCarga) {
		this.resumenCarga = resumenCarga;
	}

	@Column(name = "dec_descripcion")
	public String getDecDescripcion() {
		return this.decDescripcion;
	}

	public void setDecDescripcion(String decDescripcion) {
		this.decDescripcion = decDescripcion;
	}

}
