package cl.servel.gasto.entity;
// Generated 11-09-2019 16:41:08 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DetDetalleRendicion generated by hbm2java
 */
@Entity
@Table(name = "det_detalle_rendicion")
public class DetDetalleRendicion implements java.io.Serializable {

	private Integer detId;
	private RenRendicion renRendicion;
	private TpoSeccionRendicion tpoSeccionRendicion;
	private String detValor;
	private Integer detLineaDetalle;
	private String detValorPresentado;
	private String detValorPreCalculoReembolso;
	private String detValorCalculoReembolsoPrimeraInstancia;
	private Set<DetDetalleNomina> detDetalleNominas = new HashSet<DetDetalleNomina>(0);

	public DetDetalleRendicion() {
	}

	public DetDetalleRendicion(RenRendicion renRendicion, TpoSeccionRendicion tpoSeccionRendicion) {
		this.renRendicion = renRendicion;
		this.tpoSeccionRendicion = tpoSeccionRendicion;
	}

	public DetDetalleRendicion(RenRendicion renRendicion, TpoSeccionRendicion tpoSeccionRendicion, String detValor,
			Integer detLineaDetalle, String detValorPresentado, String detValorPreCalculoReembolso,
			String detValorCalculoReembolsoPrimeraInstancia, Set<DetDetalleNomina> detDetalleNominas) {
		this.renRendicion = renRendicion;
		this.tpoSeccionRendicion = tpoSeccionRendicion;
		this.detValor = detValor;
		this.detLineaDetalle = detLineaDetalle;
		this.detValorPresentado = detValorPresentado;
		this.detValorPreCalculoReembolso = detValorPreCalculoReembolso;
		this.detValorCalculoReembolsoPrimeraInstancia = detValorCalculoReembolsoPrimeraInstancia;
		this.detDetalleNominas = detDetalleNominas;
	}

	@SequenceGenerator(name = "cl.servel.gasto.temporal.DetDetalleRendicionIdGenerator", sequenceName = "det_detalle_rendicion_det_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.temporal.DetDetalleRendicionIdGenerator")

	@Column(name = "det_id", unique = true, nullable = false)
	public Integer getDetId() {
		return this.detId;
	}

	public void setDetId(Integer detId) {
		this.detId = detId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ren_id", nullable = false)
	public RenRendicion getRenRendicion() {
		return this.renRendicion;
	}

	public void setRenRendicion(RenRendicion renRendicion) {
		this.renRendicion = renRendicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_seccion", nullable = false)
	public TpoSeccionRendicion getTpoSeccionRendicion() {
		return this.tpoSeccionRendicion;
	}

	public void setTpoSeccionRendicion(TpoSeccionRendicion tpoSeccionRendicion) {
		this.tpoSeccionRendicion = tpoSeccionRendicion;
	}

	@Column(name = "det_valor")
	public String getDetValor() {
		return this.detValor;
	}

	public void setDetValor(String detValor) {
		this.detValor = detValor;
	}

	@Column(name = "det_linea_detalle")
	public Integer getDetLineaDetalle() {
		return this.detLineaDetalle;
	}

	public void setDetLineaDetalle(Integer detLineaDetalle) {
		this.detLineaDetalle = detLineaDetalle;
	}

	@Column(name = "det_valor_presentado")
	public String getDetValorPresentado() {
		return this.detValorPresentado;
	}

	public void setDetValorPresentado(String detValorPresentado) {
		this.detValorPresentado = detValorPresentado;
	}

	@Column(name = "det_valor_pre_calculo_reembolso")
	public String getDetValorPreCalculoReembolso() {
		return this.detValorPreCalculoReembolso;
	}

	public void setDetValorPreCalculoReembolso(String detValorPreCalculoReembolso) {
		this.detValorPreCalculoReembolso = detValorPreCalculoReembolso;
	}

	@Column(name = "det_valor_calculo_reembolso_primera_instancia")
	public String getDetValorCalculoReembolsoPrimeraInstancia() {
		return this.detValorCalculoReembolsoPrimeraInstancia;
	}

	public void setDetValorCalculoReembolsoPrimeraInstancia(String detValorCalculoReembolsoPrimeraInstancia) {
		this.detValorCalculoReembolsoPrimeraInstancia = detValorCalculoReembolsoPrimeraInstancia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detDetalleRendicion")
	public Set<DetDetalleNomina> getDetDetalleNominas() {
		return this.detDetalleNominas;
	}

	public void setDetDetalleNominas(Set<DetDetalleNomina> detDetalleNominas) {
		this.detDetalleNominas = detDetalleNominas;
	}

}
