package cl.servel.gasto.entity;
// Generated 14-08-2019 18:11:24 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DetDetalleNomina generated by hbm2java
 */
@Entity
@Table(name = "det_detalle_nomina")
public class DetDetalleNomina implements java.io.Serializable {

	private Integer detId;
	private AdmAdministradorElectoral admAdministradorElectoral;
	private CanCandidato canCandidato;
	private DetDetalleRendicion detDetalleRendicion;
	private EbaEntidadBancaria ebaEntidadBancaria;
	private NomNomina nomNomina;
	private ParPartido parPartido;
	private TpoTipos tpoTipos;
	private Integer detRut;
	private String detRutDv;
	private Double detMonto;
	private String detTransactionId;
	private Boolean detResultadoTgr;
	private Date detFechaPago;
	private String detEstado;
	private Long canIdRef;
	private Long parIdRef;
	private Long manIdRef;
	private Long folioServel;
	private Double detMontoPagado;
	private Set<IngIngresos> ingIngresoses = new HashSet<IngIngresos>(0);

	public DetDetalleNomina() {
	}

	public DetDetalleNomina(NomNomina nomNomina, TpoTipos tpoTipos, String detEstado) {
		this.nomNomina = nomNomina;
		this.tpoTipos = tpoTipos;
		this.detEstado = detEstado;
	}

	public DetDetalleNomina(AdmAdministradorElectoral admAdministradorElectoral, CanCandidato canCandidato,
			DetDetalleRendicion detDetalleRendicion, EbaEntidadBancaria ebaEntidadBancaria, NomNomina nomNomina,
			ParPartido parPartido, TpoTipos tpoTipos, Integer detRut, String detRutDv, Double detMonto,
			String detTransactionId, Boolean detResultadoTgr, Date detFechaPago, String detEstado, Long canIdRef,
			Long parIdRef, Long manIdRef, Long folioServel, Double detMontoPagado, Set<IngIngresos> ingIngresoses) {
		this.admAdministradorElectoral = admAdministradorElectoral;
		this.canCandidato = canCandidato;
		this.detDetalleRendicion = detDetalleRendicion;
		this.ebaEntidadBancaria = ebaEntidadBancaria;
		this.nomNomina = nomNomina;
		this.parPartido = parPartido;
		this.tpoTipos = tpoTipos;
		this.detRut = detRut;
		this.detRutDv = detRutDv;
		this.detMonto = detMonto;
		this.detTransactionId = detTransactionId;
		this.detResultadoTgr = detResultadoTgr;
		this.detFechaPago = detFechaPago;
		this.detEstado = detEstado;
		this.canIdRef = canIdRef;
		this.parIdRef = parIdRef;
		this.manIdRef = manIdRef;
		this.folioServel = folioServel;
		this.detMontoPagado = detMontoPagado;
		this.ingIngresoses = ingIngresoses;
	}

	@SequenceGenerator(name = "DetDetalleNominaIdGenerator", sequenceName = "det_detalle_nomina_det_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "DetDetalleNominaIdGenerator")

	@Column(name = "det_id", unique = true, nullable = false)
	public Integer getDetId() {
		return this.detId;
	}

	public void setDetId(Integer detId) {
		this.detId = detId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "adm_id")
	public AdmAdministradorElectoral getAdmAdministradorElectoral() {
		return this.admAdministradorElectoral;
	}

	public void setAdmAdministradorElectoral(AdmAdministradorElectoral admAdministradorElectoral) {
		this.admAdministradorElectoral = admAdministradorElectoral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "can_id")
	public CanCandidato getCanCandidato() {
		return this.canCandidato;
	}

	public void setCanCandidato(CanCandidato canCandidato) {
		this.canCandidato = canCandidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "det_rendicion_id")
	public DetDetalleRendicion getDetDetalleRendicion() {
		return this.detDetalleRendicion;
	}

	public void setDetDetalleRendicion(DetDetalleRendicion detDetalleRendicion) {
		this.detDetalleRendicion = detDetalleRendicion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eba_id")
	public EbaEntidadBancaria getEbaEntidadBancaria() {
		return this.ebaEntidadBancaria;
	}

	public void setEbaEntidadBancaria(EbaEntidadBancaria ebaEntidadBancaria) {
		this.ebaEntidadBancaria = ebaEntidadBancaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nom_id", nullable = false)
	public NomNomina getNomNomina() {
		return this.nomNomina;
	}

	public void setNomNomina(NomNomina nomNomina) {
		this.nomNomina = nomNomina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id")
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_moneda_id", nullable = false)
	public TpoTipos getTpoTipos() {
		return this.tpoTipos;
	}

	public void setTpoTipos(TpoTipos tpoTipos) {
		this.tpoTipos = tpoTipos;
	}

	@Column(name = "det_rut")
	public Integer getDetRut() {
		return this.detRut;
	}

	public void setDetRut(Integer detRut) {
		this.detRut = detRut;
	}

	@Column(name = "det_rut_dv", length = 1)
	public String getDetRutDv() {
		return this.detRutDv;
	}

	public void setDetRutDv(String detRutDv) {
		this.detRutDv = detRutDv;
	}

	@Column(name = "det_monto", precision = 17, scale = 17)
	public Double getDetMonto() {
		return this.detMonto;
	}

	public void setDetMonto(Double detMonto) {
		this.detMonto = detMonto;
	}

	@Column(name = "det_transaction_id", length = 50)
	public String getDetTransactionId() {
		return this.detTransactionId;
	}

	public void setDetTransactionId(String detTransactionId) {
		this.detTransactionId = detTransactionId;
	}

	@Column(name = "det_resultado_tgr")
	public Boolean getDetResultadoTgr() {
		return this.detResultadoTgr;
	}

	public void setDetResultadoTgr(Boolean detResultadoTgr) {
		this.detResultadoTgr = detResultadoTgr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "det_fecha_pago", length = 29)
	public Date getDetFechaPago() {
		return this.detFechaPago;
	}

	public void setDetFechaPago(Date detFechaPago) {
		this.detFechaPago = detFechaPago;
	}

	@Column(name = "det_estado", nullable = false, length = 20)
	public String getDetEstado() {
		return this.detEstado;
	}

	public void setDetEstado(String detEstado) {
		this.detEstado = detEstado;
	}
	
	@Column(name = "can_id_ref")
	public Long getCanIdRef() {
		return this.canIdRef;
	}

	public void setCanIdRef(Long canIdRef) {
		this.canIdRef = canIdRef;
	}

	@Column(name = "par_id_ref")
	public Long getParIdRef() {
		return this.parIdRef;
	}

	public void setParIdRef(Long parIdRef) {
		this.parIdRef = parIdRef;
	}
	@Column(name = "man_id_ref")
	public Long getManIdRef() {
		return this.manIdRef;
	}
	public void setManIdRef(Long manIdRef) {
		this.manIdRef = manIdRef;
	}

	@Column(name = "folio_servel")
	public Long getFolioServel() {
		return this.folioServel;
	}

	public void setFolioServel(Long folioServel) {
		this.folioServel = folioServel;
	}

	@Column(name = "det_monto_pagado", precision = 17, scale = 17)
	public Double getDetMontoPagado() {
		return this.detMontoPagado;
	}

	public void setDetMontoPagado(Double detMontoPagado) {
		this.detMontoPagado = detMontoPagado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detDetalleNomina")
	public Set<IngIngresos> getIngIngresoses() {
		return this.ingIngresoses;
	}

	public void setIngIngresoses(Set<IngIngresos> ingIngresoses) {
		this.ingIngresoses = ingIngresoses;
	}
}
