package cl.servel.gasto.entity;
// Generated 21-03-2019 14:36:24 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.ManyToOne;
import javax.persistence.JoinColumn;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DflDefinicionFlujo generated by hbm2java
 */
@Entity
@Table(name = "dfl_definicion_flujo")
public class DflDefinicionFlujo implements java.io.Serializable {

	private Integer dflId;
	private EveEventoEleccionario eveEventoEleccionario;
	private String dflNombreFlujo;
	private String dflCodigo;
	private int version;
	private Set<DtaDefinicionTarea> dtaDefinicionTareas = new HashSet<DtaDefinicionTarea>(0);

	public DflDefinicionFlujo() {
	}

	public DflDefinicionFlujo(EveEventoEleccionario eveEventoEleccionario, String dflCodigo, int version) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.dflCodigo = dflCodigo;
		this.version = version;
	}

	public DflDefinicionFlujo(EveEventoEleccionario eveEventoEleccionario, String dflNombreFlujo, String dflCodigo, int version, Set<DtaDefinicionTarea> dtaDefinicionTareas) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.dflNombreFlujo = dflNombreFlujo;
		this.dflCodigo = dflCodigo;
		this.version = version;
		this.dtaDefinicionTareas = dtaDefinicionTareas;
	}
	
	public DflDefinicionFlujo(String dflNombreFlujo, String dflCodigo, Set<DtaDefinicionTarea> dtaDefinicionTareas) {
		this.dflNombreFlujo = dflNombreFlujo;
		this.dflCodigo = dflCodigo;
		this.dtaDefinicionTareas = dtaDefinicionTareas;
	}

	@SequenceGenerator(name = "DflDefinicionFlujoIdGenerator", sequenceName = "dfl_definicion_flujo_dfl_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "DflDefinicionFlujoIdGenerator")

	@Column(name = "dfl_id", unique = true, nullable = false)
	public Integer getDflId() {
		return this.dflId;
	}

	public void setDflId(Integer dflId) {
		this.dflId = dflId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@Column(name = "dfl_nombre_flujo", length = 50)
	public String getDflNombreFlujo() {
		return this.dflNombreFlujo;
	}

	public void setDflNombreFlujo(String dflNombreFlujo) {
		this.dflNombreFlujo = dflNombreFlujo;
	}

	@Column(name = "dfl_codigo", nullable = false, length = 50)
	public String getDflCodigo() {
		return this.dflCodigo;
	}

	public void setDflCodigo(String dflCodigo) {
		this.dflCodigo = dflCodigo;
	}

	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dflDefinicionFlujo")
	public Set<DtaDefinicionTarea> getDtaDefinicionTareas() {
		return this.dtaDefinicionTareas;
	}

	public void setDtaDefinicionTareas(Set<DtaDefinicionTarea> dtaDefinicionTareas) {
		this.dtaDefinicionTareas = dtaDefinicionTareas;
	}
}
