package cl.servel.gasto.entity;
// Generated 02-01-2019 19:29:27 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DreDatosRendicion generated by hbm2java
 */
@Entity
@Table(name = "dre_datos_rendicion")
public class DreDatosRendicion implements java.io.Serializable {

	private Integer dreId;
	private String dreNombreDato;
	private String dreTipoDato;
	private Integer dreLargoTipo;
	
	public DreDatosRendicion() {
	}

	public DreDatosRendicion(String dreNombreDato, String dreTipoDato, Integer dreLargoTipo) {
		this.dreNombreDato = dreNombreDato;
		this.dreTipoDato = dreTipoDato;
		this.dreLargoTipo = dreLargoTipo;
	}

	@SequenceGenerator(name = "DreDatosRendicionIdGenerator", sequenceName = "dre_datos_rendicion_dre_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "DreDatosRendicionIdGenerator")

	@Column(name = "dre_id", unique = true, nullable = false)
	public Integer getDreId() {
		return this.dreId;
	}

	public void setDreId(Integer dreId) {
		this.dreId = dreId;
	}

	@Column(name = "dre_nombre_dato", length = 50)
	public String getDreNombreDato() {
		return this.dreNombreDato;
	}

	public void setDreNombreDato(String dreNombreDato) {
		this.dreNombreDato = dreNombreDato;
	}

	@Column(name = "dre_tipo_dato", length = 15)
	public String getDreTipoDato() {
		return this.dreTipoDato;
	}

	public void setDreTipoDato(String dreTipoDato) {
		this.dreTipoDato = dreTipoDato;
	}

	@Column(name = "dre_largo_tipo")
	public Integer getDreLargoTipo() {
		return this.dreLargoTipo;
	}

	public void setDreLargoTipo(Integer dreLargoTipo) {
		this.dreLargoTipo = dreLargoTipo;
	}

	

}
