package cl.servel.gasto.entity;
// Generated 21-03-2019 14:36:24 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DtaDefinicionTarea generated by hbm2java
 */
 
@Entity
@Table(name = "dta_definicion_tarea")
public class DtaDefinicionTarea implements java.io.Serializable {

	private Integer dtaId;
	private DbnDefinicionBandeja dbnDefinicionBandeja;
	private DflDefinicionFlujo dflDefinicionFlujo;
	private TpoEstadoTarea tpoEstadoTarea;
	private String dtaCodigoOrigen;
	private String dtaNombreTarea;
	private Integer dtaSlaTarea;
	private boolean dtaUsuarioRepetido;
	private boolean dtaRutaDinamica;
	private boolean dtaPermiteSubrogante;
	private boolean dtaUsuarioTransversal;
	private Set<AsgAsignacionCargaTarea> asgAsignacionCargaTareas = new HashSet<AsgAsignacionCargaTarea>(0);
	private Set<InfInstanciaFlujo> infInstanciaFlujos = new HashSet<InfInstanciaFlujo>(0);
	private Set<RlcTarea> rlcTareasForRlcIdAnterior = new HashSet<RlcTarea>(0);
	private Set<DeaDefinicionActividad> deaDefinicionActividads = new HashSet<DeaDefinicionActividad>(0);
	private Set<RlcTarea> rlcTareasForRlcIdSiguiente = new HashSet<RlcTarea>(0);
	private Set<RlcTarea> rlcTareasForDtaId = new HashSet<RlcTarea>(0);
	private Set<RlcPerfilDefinicionTarea> rlcPerfilDefinicionTareas = new HashSet<RlcPerfilDefinicionTarea>(0);
	private Set<IntInstanciaTarea> intInstanciaTareas = new HashSet<IntInstanciaTarea>(0);

	public DtaDefinicionTarea() {
	}

	public DtaDefinicionTarea(DbnDefinicionBandeja dbnDefinicionBandeja, DflDefinicionFlujo dflDefinicionFlujo, TpoEstadoTarea tpoEstadoTarea, boolean dtaUsuarioRepetido, boolean dtaRutaDinamica, boolean dtaPermiteSubrogante, boolean dtaUsuarioTransversal) {
		this.dbnDefinicionBandeja = dbnDefinicionBandeja;
		this.dflDefinicionFlujo = dflDefinicionFlujo;
		this.tpoEstadoTarea = tpoEstadoTarea;
		this.dtaUsuarioRepetido = dtaUsuarioRepetido;
		this.dtaRutaDinamica = dtaRutaDinamica;
		this.dtaPermiteSubrogante = dtaPermiteSubrogante;
		this.dtaUsuarioTransversal = dtaUsuarioTransversal;
	}

	public DtaDefinicionTarea(DbnDefinicionBandeja dbnDefinicionBandeja, DflDefinicionFlujo dflDefinicionFlujo, TpoEstadoTarea tpoEstadoTarea, String dtaCodigoOrigen, String dtaNombreTarea, Integer dtaSlaTarea, boolean dtaUsuarioRepetido, boolean dtaRutaDinamica, boolean dtaPermiteSubrogante, boolean dtaUsuarioTransversal, Set<AsgAsignacionCargaTarea> asgAsignacionCargaTareas,
			Set<InfInstanciaFlujo> infInstanciaFlujos, Set<RlcTarea> rlcTareasForRlcIdAnterior, Set<DeaDefinicionActividad> deaDefinicionActividads, Set<RlcTarea> rlcTareasForRlcIdSiguiente, Set<RlcTarea> rlcTareasForDtaId, Set<RlcPerfilDefinicionTarea> rlcPerfilDefinicionTareas, Set<IntInstanciaTarea> intInstanciaTareas) {
		this.dbnDefinicionBandeja = dbnDefinicionBandeja;
		this.dflDefinicionFlujo = dflDefinicionFlujo;
		this.tpoEstadoTarea = tpoEstadoTarea;
		this.dtaCodigoOrigen = dtaCodigoOrigen;
		this.dtaNombreTarea = dtaNombreTarea;
		this.dtaSlaTarea = dtaSlaTarea;
		this.dtaUsuarioRepetido = dtaUsuarioRepetido;
		this.dtaRutaDinamica = dtaRutaDinamica;
		this.dtaPermiteSubrogante = dtaPermiteSubrogante;
		this.dtaUsuarioTransversal = dtaUsuarioTransversal;
		this.asgAsignacionCargaTareas = asgAsignacionCargaTareas;
		this.infInstanciaFlujos = infInstanciaFlujos;
		this.rlcTareasForRlcIdAnterior = rlcTareasForRlcIdAnterior;
		this.deaDefinicionActividads = deaDefinicionActividads;
		this.rlcTareasForRlcIdSiguiente = rlcTareasForRlcIdSiguiente;
		this.rlcTareasForDtaId = rlcTareasForDtaId;
		this.rlcPerfilDefinicionTareas = rlcPerfilDefinicionTareas;
		this.intInstanciaTareas = intInstanciaTareas;
	}

	@SequenceGenerator(name = "DtaDefinicionTareaIdGenerator", sequenceName = "dta_definicion_tarea_dta_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "DtaDefinicionTareaIdGenerator")

	@Column(name = "dta_id", unique = true, nullable = false)
	public Integer getDtaId() {
		return this.dtaId;
	}

	public void setDtaId(Integer dtaId) {
		this.dtaId = dtaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dbn_id", nullable = false)
	public DbnDefinicionBandeja getDbnDefinicionBandeja() {
		return this.dbnDefinicionBandeja;
	}

	public void setDbnDefinicionBandeja(DbnDefinicionBandeja dbnDefinicionBandeja) {
		this.dbnDefinicionBandeja = dbnDefinicionBandeja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dfl_id", nullable = false)
	public DflDefinicionFlujo getDflDefinicionFlujo() {
		return this.dflDefinicionFlujo;
	}

	public void setDflDefinicionFlujo(DflDefinicionFlujo dflDefinicionFlujo) {
		this.dflDefinicionFlujo = dflDefinicionFlujo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_tarea_id", nullable = false)
	public TpoEstadoTarea getTpoEstadoTarea() {
		return this.tpoEstadoTarea;
	}

	public void setTpoEstadoTarea(TpoEstadoTarea tpoEstadoTarea) {
		this.tpoEstadoTarea = tpoEstadoTarea;
	}

	@Column(name = "dta_codigo_origen", length = 50)
	public String getDtaCodigoOrigen() {
		return this.dtaCodigoOrigen;
	}

	public void setDtaCodigoOrigen(String dtaCodigoOrigen) {
		this.dtaCodigoOrigen = dtaCodigoOrigen;
	}

	@Column(name = "dta_nombre_tarea", length = 60)
	public String getDtaNombreTarea() {
		return this.dtaNombreTarea;
	}

	public void setDtaNombreTarea(String dtaNombreTarea) {
		this.dtaNombreTarea = dtaNombreTarea;
	}

	@Column(name = "dta_sla_tarea")
	public Integer getDtaSlaTarea() {
		return this.dtaSlaTarea;
	}

	public void setDtaSlaTarea(Integer dtaSlaTarea) {
		this.dtaSlaTarea = dtaSlaTarea;
	}

	@Column(name = "dta_usuario_repetido", nullable = false)
	public boolean isDtaUsuarioRepetido() {
		return this.dtaUsuarioRepetido;
	}

	public void setDtaUsuarioRepetido(boolean dtaUsuarioRepetido) {
		this.dtaUsuarioRepetido = dtaUsuarioRepetido;
	}

	@Column(name = "dta_ruta_dinamica", nullable = false)
	public boolean isDtaRutaDinamica() {
		return this.dtaRutaDinamica;
	}

	public void setDtaRutaDinamica(boolean dtaRutaDinamica) {
		this.dtaRutaDinamica = dtaRutaDinamica;
	}

	@Column(name = "dta_permite_subrogante", nullable = false)
	public boolean isDtaPermiteSubrogante() {
		return this.dtaPermiteSubrogante;
	}

	public void setDtaPermiteSubrogante(boolean dtaPermiteSubrogante) {
		this.dtaPermiteSubrogante = dtaPermiteSubrogante;
	}

	@Column(name = "dta_usuario_transversal", nullable = false)
	public boolean isDtaUsuarioTransversal() {
		return this.dtaUsuarioTransversal;
	}

	public void setDtaUsuarioTransversal(boolean dtaUsuarioTransversal) {
		this.dtaUsuarioTransversal = dtaUsuarioTransversal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtaDefinicionTarea")
	public Set<AsgAsignacionCargaTarea> getAsgAsignacionCargaTareas() {
		return this.asgAsignacionCargaTareas;
	}

	public void setAsgAsignacionCargaTareas(Set<AsgAsignacionCargaTarea> asgAsignacionCargaTareas) {
		this.asgAsignacionCargaTareas = asgAsignacionCargaTareas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtaDefinicionTarea")
	public Set<InfInstanciaFlujo> getInfInstanciaFlujos() {
		return this.infInstanciaFlujos;
	}

	public void setInfInstanciaFlujos(Set<InfInstanciaFlujo> infInstanciaFlujos) {
		this.infInstanciaFlujos = infInstanciaFlujos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtaDefinicionTareaByRlcIdAnterior")
	public Set<RlcTarea> getRlcTareasForRlcIdAnterior() {
		return this.rlcTareasForRlcIdAnterior;
	}

	public void setRlcTareasForRlcIdAnterior(Set<RlcTarea> rlcTareasForRlcIdAnterior) {
		this.rlcTareasForRlcIdAnterior = rlcTareasForRlcIdAnterior;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtaDefinicionTarea")
	public Set<DeaDefinicionActividad> getDeaDefinicionActividads() {
		return this.deaDefinicionActividads;
	}

	public void setDeaDefinicionActividads(Set<DeaDefinicionActividad> deaDefinicionActividads) {
		this.deaDefinicionActividads = deaDefinicionActividads;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtaDefinicionTareaByRlcIdSiguiente")
	public Set<RlcTarea> getRlcTareasForRlcIdSiguiente() {
		return this.rlcTareasForRlcIdSiguiente;
	}

	public void setRlcTareasForRlcIdSiguiente(Set<RlcTarea> rlcTareasForRlcIdSiguiente) {
		this.rlcTareasForRlcIdSiguiente = rlcTareasForRlcIdSiguiente;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtaDefinicionTareaByDtaId")
	public Set<RlcTarea> getRlcTareasForDtaId() {
		return this.rlcTareasForDtaId;
	}

	public void setRlcTareasForDtaId(Set<RlcTarea> rlcTareasForDtaId) {
		this.rlcTareasForDtaId = rlcTareasForDtaId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtaDefinicionTarea")
	public Set<RlcPerfilDefinicionTarea> getRlcPerfilDefinicionTareas() {
		return this.rlcPerfilDefinicionTareas;
	}

	public void setRlcPerfilDefinicionTareas(Set<RlcPerfilDefinicionTarea> rlcPerfilDefinicionTareas) {
		this.rlcPerfilDefinicionTareas = rlcPerfilDefinicionTareas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dtaDefinicionTarea")
	public Set<IntInstanciaTarea> getIntInstanciaTareas() {
		return this.intInstanciaTareas;
	}

	public void setIntInstanciaTareas(Set<IntInstanciaTarea> intInstanciaTareas) {
		this.intInstanciaTareas = intInstanciaTareas;
	}
}
