package cl.servel.gasto.entity;
// Generated 03-12-2018 11:52:46 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * EleEleccion generated by hbm2java
 */
@Entity
@Table(name = "ele_eleccion")
public class EleEleccion implements java.io.Serializable {

	private Integer eleId;
	private EveEventoEleccionario eveEventoEleccionario;
	private TpoEleccion tpoEleccion;
	private TpoEvento tpoEvento;
	private TpoNivel tpoNivel;
	private String eleCodigoOrigen;
	private String eleNombre;
	private Date eleFecha;
	private Boolean eleEliminado;
	private Date eleCreated;
	private Date eleModified;
	private boolean aplicaResumenCalculo;
	private boolean aplicaLimiteGasto;
	private Set<PacPacto> pacPactos = new HashSet<PacPacto>(0);
	private Set<ParPartido> parPartidos = new HashSet<ParPartido>(0);
	private Set<SelSubEleccion> selSubEleccions = new HashSet<SelSubEleccion>(0);
	private Set<ResResumenCalculos> resResumenCalculoses = new HashSet<ResResumenCalculos>(0);
	private Set<ResumenCarga> resumenCargas = new HashSet<ResumenCarga>(0);
	private Set<RenRendicion> renRendicions = new HashSet<RenRendicion>(0);
	private Set<SpaPacto> spaPactos = new HashSet<SpaPacto>(0);
	private Set<RlcSubpactoPartido> rlcSubpactoPartidos = new HashSet<RlcSubpactoPartido>(0);
	private Set<LimLimiteGasto> limLimiteGastos = new HashSet<LimLimiteGasto>(0);

	public EleEleccion() {
	}

	public EleEleccion(EveEventoEleccionario eveEventoEleccionario, TpoEleccion tpoEleccion, TpoEvento tpoEvento,
			TpoNivel tpoNivel, boolean aplicaResumenCalculo, boolean aplicaLimiteGasto) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoEleccion = tpoEleccion;
		this.tpoEvento = tpoEvento;
		this.tpoNivel = tpoNivel;
		this.aplicaResumenCalculo = aplicaResumenCalculo;
		this.aplicaLimiteGasto = aplicaLimiteGasto;
	}

	public EleEleccion(EveEventoEleccionario eveEventoEleccionario, TpoEleccion tpoEleccion, TpoEvento tpoEvento,
			TpoNivel tpoNivel, String eleCodigoOrigen, String eleNombre, Date eleFecha, Boolean eleEliminado,
			Date eleCreated, Date eleModified, boolean aplicaResumenCalculo, boolean aplicaLimiteGasto, Set<PacPacto> pacPactos, Set<ParPartido> parPartidos,
			Set<SelSubEleccion> selSubEleccions, Set<ResResumenCalculos> resResumenCalculoses, Set<ResumenCarga> resumenCargas,
			Set<SpaPacto> spaPactos,Set<RenRendicion> renRendicions,Set<RlcSubpactoPartido> rlcSubpactoPartidos, Set<LimLimiteGasto> limLimiteGastos) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoEleccion = tpoEleccion;
		this.tpoEvento = tpoEvento;
		this.tpoNivel = tpoNivel;
		this.eleCodigoOrigen = eleCodigoOrigen;
		this.eleNombre = eleNombre;
		this.eleFecha = eleFecha;
		this.eleEliminado = eleEliminado;
		this.eleCreated = eleCreated;
		this.eleModified = eleModified;
		this.aplicaResumenCalculo = aplicaResumenCalculo;
		this.aplicaLimiteGasto = aplicaLimiteGasto;
		this.pacPactos = pacPactos;
		this.parPartidos = parPartidos;
		this.selSubEleccions = selSubEleccions;
		this.resResumenCalculoses = resResumenCalculoses;
		this.resumenCargas = resumenCargas;
		this.renRendicions = renRendicions;
		this.spaPactos = spaPactos;
		this.rlcSubpactoPartidos = rlcSubpactoPartidos;
		this.limLimiteGastos = limLimiteGastos;
	}

	@SequenceGenerator(name = "EleEleccionIdGenerator", sequenceName = "ele_eleccion_ele_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "EleEleccionIdGenerator")

	@Column(name = "ele_id", unique = true, nullable = false)
	public Integer getEleId() {
		return this.eleId;
	}

	public void setEleId(Integer eleId) {
		this.eleId = eleId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id_eve", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_eleccion_id", nullable = false)
	public TpoEleccion getTpoEleccion() {
		return this.tpoEleccion;
	}

	public void setTpoEleccion(TpoEleccion tpoEleccion) {
		this.tpoEleccion = tpoEleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_evento_id", nullable = false)
	public TpoEvento getTpoEvento() {
		return this.tpoEvento;
	}

	public void setTpoEvento(TpoEvento tpoEvento) {
		this.tpoEvento = tpoEvento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_niv_id", nullable = false)
	public TpoNivel getTpoNivel() {
		return this.tpoNivel;
	}

	public void setTpoNivel(TpoNivel tpoNivel) {
		this.tpoNivel = tpoNivel;
	}

	@Column(name = "ele_codigo_origen", length = 5)
	public String getEleCodigoOrigen() {
		return this.eleCodigoOrigen;
	}

	public void setEleCodigoOrigen(String eleCodigoOrigen) {
		this.eleCodigoOrigen = eleCodigoOrigen;
	}

	@Column(name = "ele_nombre", length = 50)
	public String getEleNombre() {
		return this.eleNombre;
	}

	public void setEleNombre(String eleNombre) {
		this.eleNombre = eleNombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ele_fecha", length = 13)
	public Date getEleFecha() {
		return this.eleFecha;
	}

	public void setEleFecha(Date eleFecha) {
		this.eleFecha = eleFecha;
	}

	@Column(name = "ele_eliminado")
	public Boolean getEleEliminado() {
		return this.eleEliminado;
	}

	public void setEleEliminado(Boolean eleEliminado) {
		this.eleEliminado = eleEliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ele_created", length = 13)
	public Date getEleCreated() {
		return this.eleCreated;
	}

	public void setEleCreated(Date eleCreated) {
		this.eleCreated = eleCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ele_modified", length = 13)
	public Date getEleModified() {
		return this.eleModified;
	}

	public void setEleModified(Date eleModified) {
		this.eleModified = eleModified;
	}
	
	@Column(name = "aplica_resumen_calculo", nullable = false)
	public boolean isAplicaResumenCalculo() {
		return this.aplicaResumenCalculo;
	}

	public void setAplicaResumenCalculo(boolean aplicaResumenCalculo) {
		this.aplicaResumenCalculo = aplicaResumenCalculo;
	}

	@Column(name = "aplica_limite_gasto", nullable = false)
	public boolean isAplicaLimiteGasto() {
		return this.aplicaLimiteGasto;
	}

	public void setAplicaLimiteGasto(boolean aplicaLimiteGasto) {
		this.aplicaLimiteGasto = aplicaLimiteGasto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleEleccion")
	public Set<PacPacto> getPacPactos() {
		return this.pacPactos;
	}

	public void setPacPactos(Set<PacPacto> pacPactos) {
		this.pacPactos = pacPactos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleEleccion")
	public Set<ParPartido> getParPartidos() {
		return this.parPartidos;
	}

	public void setParPartidos(Set<ParPartido> parPartidos) {
		this.parPartidos = parPartidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleEleccion")
	public Set<SelSubEleccion> getSelSubEleccions() {
		return this.selSubEleccions;
	}

	public void setSelSubEleccions(Set<SelSubEleccion> selSubEleccions) {
		this.selSubEleccions = selSubEleccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleEleccion")
	public Set<ResResumenCalculos> getResResumenCalculoses() {
		return this.resResumenCalculoses;
	}

	public void setResResumenCalculoses(Set<ResResumenCalculos> resResumenCalculoses) {
		this.resResumenCalculoses = resResumenCalculoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleEleccion")
	public Set<ResumenCarga> getResumenCargas() {
		return this.resumenCargas;
	}

	public void setResumenCargas(Set<ResumenCarga> resumenCargas) {
		this.resumenCargas = resumenCargas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleEleccion")
	public Set<SpaPacto> getSpaPactos() {
		return this.spaPactos;
	}

	public void setSpaPactos(Set<SpaPacto> spaPactos) {
		this.spaPactos = spaPactos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleEleccion")
	public Set<RenRendicion> getRenRendicions() {
		return this.renRendicions;
	}

	public void setRenRendicions(Set<RenRendicion> renRendicions) {
		this.renRendicions = renRendicions;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleEleccion")
	public Set<RlcSubpactoPartido> getRlcSubpactoPartidos() {
		return this.rlcSubpactoPartidos;
	}

	public void setRlcSubpactoPartidos(Set<RlcSubpactoPartido> rlcSubpactoPartidos) {
		this.rlcSubpactoPartidos = rlcSubpactoPartidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "eleEleccion")
	public Set<LimLimiteGasto> getLimLimiteGastos() {
		return this.limLimiteGastos;
	}

	public void setLimLimiteGastos(Set<LimLimiteGasto> limLimiteGastos) {
		this.limLimiteGastos = limLimiteGastos;
	}

}
