package cl.servel.gasto.entity;
// Generated 21-08-2019 12:50:12 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExExpediente generated by hbm2java
 */
@Entity
@Table(name = "ex_expediente")
public class ExExpediente implements java.io.Serializable {

	private Integer exId;
	private CanCandidato canCandidato;
	private DexDocumentoExterno dexDocumentoExterno;
	private ParPartido parPartido;
	private Date exFechaCreacion;
	private String exNroFolio;

	public ExExpediente() {
	}

	public ExExpediente(DexDocumentoExterno dexDocumentoExterno) {
		this.dexDocumentoExterno = dexDocumentoExterno;
	}

	public ExExpediente(CanCandidato canCandidato, DexDocumentoExterno dexDocumentoExterno, ParPartido parPartido,
			Date exFechaCreacion, String exNroFolio) {
		this.canCandidato = canCandidato;
		this.dexDocumentoExterno = dexDocumentoExterno;
		this.parPartido = parPartido;
		this.exFechaCreacion = exFechaCreacion;
		this.exNroFolio = exNroFolio;
	}

	@SequenceGenerator(name = "cl.servel.gasto.temporal.ExExpedienteIdGenerator", sequenceName = "ex_expediente_ex_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.temporal.ExExpedienteIdGenerator")

	@Column(name = "ex_id", unique = true, nullable = false)
	public Integer getExId() {
		return this.exId;
	}

	public void setExId(Integer exId) {
		this.exId = exId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "can_id")
	public CanCandidato getCanCandidato() {
		return this.canCandidato;
	}

	public void setCanCandidato(CanCandidato canCandidato) {
		this.canCandidato = canCandidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dex_id", nullable = false)
	public DexDocumentoExterno getDexDocumentoExterno() {
		return this.dexDocumentoExterno;
	}

	public void setDexDocumentoExterno(DexDocumentoExterno dexDocumentoExterno) {
		this.dexDocumentoExterno = dexDocumentoExterno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id")
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ex_fecha_creacion", length = 29)
	public Date getExFechaCreacion() {
		return this.exFechaCreacion;
	}

	public void setExFechaCreacion(Date exFechaCreacion) {
		this.exFechaCreacion = exFechaCreacion;
	}

	@Column(name = "ex_nro_folio", length = 10)
	public String getExNroFolio() {
		return this.exNroFolio;
	}

	public void setExNroFolio(String exNroFolio) {
		this.exNroFolio = exNroFolio;
	}

}
