package cl.servel.gasto.entity;
// Generated 28-05-2019 17:59:23 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * InbInstanciaBandeja generated by hbm2java
 */
@Entity
@Table(name = "inb_instancia_bandeja")
public class InbInstanciaBandeja implements java.io.Serializable {

	private Integer inbId;
	private DbnDefinicionBandeja dbnDefinicionBandeja;
	private EveEventoEleccionario eveEventoEleccionario;
	private UsuUsuarios usuUsuarios;
	private Set<InfInstanciaFlujo> infInstanciaFlujos = new HashSet<InfInstanciaFlujo>(0);

	public InbInstanciaBandeja() {
	}

	public InbInstanciaBandeja(DbnDefinicionBandeja dbnDefinicionBandeja, EveEventoEleccionario eveEventoEleccionario, UsuUsuarios usuUsuarios) {
		this.dbnDefinicionBandeja = dbnDefinicionBandeja;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.usuUsuarios = usuUsuarios;
	}

	public InbInstanciaBandeja(DbnDefinicionBandeja dbnDefinicionBandeja, EveEventoEleccionario eveEventoEleccionario, UsuUsuarios usuUsuarios, Set<InfInstanciaFlujo> infInstanciaFlujos) {
		this.dbnDefinicionBandeja = dbnDefinicionBandeja;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.usuUsuarios = usuUsuarios;
		this.infInstanciaFlujos = infInstanciaFlujos;
	}

	@SequenceGenerator(name = "InbInstanciaBandejaIdGenerator", sequenceName = "inb_instancia_bandeja_inb_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "InbInstanciaBandejaIdGenerator")

	@Column(name = "inb_id", unique = true, nullable = false)
	public Integer getInbId() {
		return this.inbId;
	}

	public void setInbId(Integer inbId) {
		this.inbId = inbId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dbn_id", nullable = false)
	public DbnDefinicionBandeja getDbnDefinicionBandeja() {
		return this.dbnDefinicionBandeja;
	}

	public void setDbnDefinicionBandeja(DbnDefinicionBandeja dbnDefinicionBandeja) {
		this.dbnDefinicionBandeja = dbnDefinicionBandeja;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usu_id", nullable = false)
	public UsuUsuarios getUsuUsuarios() {
		return this.usuUsuarios;
	}

	public void setUsuUsuarios(UsuUsuarios usuUsuarios) {
		this.usuUsuarios = usuUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inbInstanciaBandeja")
	public Set<InfInstanciaFlujo> getInfInstanciaFlujos() {
		return this.infInstanciaFlujos;
	}

	public void setInfInstanciaFlujos(Set<InfInstanciaFlujo> infInstanciaFlujos) {
		this.infInstanciaFlujos = infInstanciaFlujos;
	}
}
