package cl.servel.gasto.entity;
// Generated 19-12-2019 12:02:04 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IntInstanciaTarea generated by hbm2java
 */
@Entity
@Table(name = "int_instancia_tarea")
public class IntInstanciaTarea implements java.io.Serializable {

	private Integer intId;
	private DtaDefinicionTarea dtaDefinicionTarea;
	private InfInstanciaFlujo infInstanciaFlujo;
	private TpoEstadoTarea tpoEstadoTarea;
	private UstUsuarioTarea ustUsuarioTarea;
	private UsuUsuarios usuUsuarios;
	private Date intFechaInicio;
	private Date intFechaTermino;
	private Date intFechaAsignacion;
	private boolean intReasignada;
	private String intEstadoFlujo;
	private String intFolio;
	private Set<ActActividad> actActividads = new HashSet<ActActividad>(0);

	public IntInstanciaTarea() {
	}

	public IntInstanciaTarea(DtaDefinicionTarea dtaDefinicionTarea, InfInstanciaFlujo infInstanciaFlujo,
			TpoEstadoTarea tpoEstadoTarea, UstUsuarioTarea ustUsuarioTarea, UsuUsuarios usuUsuarios,
			boolean intReasignada) {
		this.dtaDefinicionTarea = dtaDefinicionTarea;
		this.infInstanciaFlujo = infInstanciaFlujo;
		this.tpoEstadoTarea = tpoEstadoTarea;
		this.ustUsuarioTarea = ustUsuarioTarea;
		this.usuUsuarios = usuUsuarios;
		this.intReasignada = intReasignada;
	}

	public IntInstanciaTarea(DtaDefinicionTarea dtaDefinicionTarea, InfInstanciaFlujo infInstanciaFlujo,
			TpoEstadoTarea tpoEstadoTarea, UstUsuarioTarea ustUsuarioTarea, UsuUsuarios usuUsuarios,
			Date intFechaInicio, Date intFechaTermino, Date intFechaAsignacion, boolean intReasignada,
			String intEstadoFlujo, String intFolio, Set<ActActividad> actActividads) {
		this.dtaDefinicionTarea = dtaDefinicionTarea;
		this.infInstanciaFlujo = infInstanciaFlujo;
		this.tpoEstadoTarea = tpoEstadoTarea;
		this.ustUsuarioTarea = ustUsuarioTarea;
		this.usuUsuarios = usuUsuarios;
		this.intFechaInicio = intFechaInicio;
		this.intFechaTermino = intFechaTermino;
		this.intFechaAsignacion = intFechaAsignacion;
		this.intReasignada = intReasignada;
		this.intEstadoFlujo = intEstadoFlujo;
		this.intFolio = intFolio;
		this.actActividads = actActividads;
	}

	@SequenceGenerator(name = "cl.servel.gasto.entity.IntInstanciaTareaIdGenerator", sequenceName = "int_instancia_tarea_int_id_seq" , initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.entity.IntInstanciaTareaIdGenerator")

	@Column(name = "int_id", unique = true, nullable = false)
	public Integer getIntId() {
		return this.intId;
	}

	public void setIntId(Integer intId) {
		this.intId = intId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dta_id", nullable = false)
	public DtaDefinicionTarea getDtaDefinicionTarea() {
		return this.dtaDefinicionTarea;
	}

	public void setDtaDefinicionTarea(DtaDefinicionTarea dtaDefinicionTarea) {
		this.dtaDefinicionTarea = dtaDefinicionTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "inf_id", nullable = false)
	public InfInstanciaFlujo getInfInstanciaFlujo() {
		return this.infInstanciaFlujo;
	}

	public void setInfInstanciaFlujo(InfInstanciaFlujo infInstanciaFlujo) {
		this.infInstanciaFlujo = infInstanciaFlujo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_tarea_id", nullable = false)
	public TpoEstadoTarea getTpoEstadoTarea() {
		return this.tpoEstadoTarea;
	}

	public void setTpoEstadoTarea(TpoEstadoTarea tpoEstadoTarea) {
		this.tpoEstadoTarea = tpoEstadoTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ust_id", nullable = false)
	public UstUsuarioTarea getUstUsuarioTarea() {
		return this.ustUsuarioTarea;
	}

	public void setUstUsuarioTarea(UstUsuarioTarea ustUsuarioTarea) {
		this.ustUsuarioTarea = ustUsuarioTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usu_id", nullable = false)
	public UsuUsuarios getUsuUsuarios() {
		return this.usuUsuarios;
	}

	public void setUsuUsuarios(UsuUsuarios usuUsuarios) {
		this.usuUsuarios = usuUsuarios;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "int_fecha_inicio", length = 29)
	public Date getIntFechaInicio() {
		return this.intFechaInicio;
	}

	public void setIntFechaInicio(Date intFechaInicio) {
		this.intFechaInicio = intFechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "int_fecha_termino", length = 29)
	public Date getIntFechaTermino() {
		return this.intFechaTermino;
	}

	public void setIntFechaTermino(Date intFechaTermino) {
		this.intFechaTermino = intFechaTermino;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "int_fecha_asignacion", length = 29)
	public Date getIntFechaAsignacion() {
		return this.intFechaAsignacion;
	}

	public void setIntFechaAsignacion(Date intFechaAsignacion) {
		this.intFechaAsignacion = intFechaAsignacion;
	}

	@Column(name = "int_reasignada", nullable = false)
	public boolean isIntReasignada() {
		return this.intReasignada;
	}

	public void setIntReasignada(boolean intReasignada) {
		this.intReasignada = intReasignada;
	}

	@Column(name = "int_estado_flujo", length = 50)
	public String getIntEstadoFlujo() {
		return this.intEstadoFlujo;
	}

	public void setIntEstadoFlujo(String intEstadoFlujo) {
		this.intEstadoFlujo = intEstadoFlujo;
	}

	@Column(name = "int_folio", length = 50)
	public String getIntFolio() {
		return this.intFolio;
	}

	public void setIntFolio(String intFolio) {
		this.intFolio = intFolio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intInstanciaTarea")
	public Set<ActActividad> getActActividads() {
		return this.actActividads;
	}

	public void setActActividads(Set<ActActividad> actActividads) {
		this.actActividads = actActividads;
	}

}
