package cl.servel.gasto.entity;
// Generated 04-07-2019 12:10:19 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObrObservacionRendicion generated by hbm2java
 */
@Entity
@Table(name = "obr_observacion_rendicion")
public class ObrObservacionRendicion implements java.io.Serializable {

	private Integer obrId;
	private DexDocumentoExterno dexDocumentoExterno;
	private RenRendicion renRendicion;
	private TpoRecomendacion tpoRecomendacion;
	private Integer obrNumeroLinea;
	private Integer obrNumeroPagina;
	private Boolean obrHabilitada;
	private String obrRespuesta;
	private Date obrFechaRespuesta;
	private String obrTipoIngresoRespuesta;
	private String obrAnalisisRespuesta;

	public ObrObservacionRendicion() {
	}

	public ObrObservacionRendicion(RenRendicion renRendicion) {
		this.renRendicion = renRendicion;
	}

	public ObrObservacionRendicion(DexDocumentoExterno dexDocumentoExterno, RenRendicion renRendicion, TpoRecomendacion tpoRecomendacion, Integer obrNumeroLinea, Integer obrNumeroPagina, Boolean obrHabilitada, String obrRespuesta, Date obrFechaRespuesta, String obrTipoIngresoRespuesta, String obrAnalisisRespuesta) {		this.dexDocumentoExterno = dexDocumentoExterno;
		this.renRendicion = renRendicion;
		this.obrNumeroLinea = obrNumeroLinea;
		this.tpoRecomendacion = tpoRecomendacion;
		this.obrNumeroPagina = obrNumeroPagina;
		this.obrHabilitada = obrHabilitada;
		this.obrRespuesta = obrRespuesta;
		this.obrFechaRespuesta = obrFechaRespuesta;
		this.obrTipoIngresoRespuesta = obrTipoIngresoRespuesta;
		this.obrAnalisisRespuesta = obrAnalisisRespuesta;
	}

	@SequenceGenerator(name = "ObrObservacionRendicionIdGenerator", sequenceName = "obr_observacion_rendicion_obr_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "ObrObservacionRendicionIdGenerator")

	@Column(name = "obr_id", unique = true, nullable = false)
	public Integer getObrId() {
		return this.obrId;
	}

	public void setObrId(Integer obrId) {
		this.obrId = obrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dex_id")
	public DexDocumentoExterno getDexDocumentoExterno() {
		return this.dexDocumentoExterno;
	}

	public void setDexDocumentoExterno(DexDocumentoExterno dexDocumentoExterno) {
		this.dexDocumentoExterno = dexDocumentoExterno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ren_id", nullable = false)
	public RenRendicion getRenRendicion() {
		return this.renRendicion;
	}

	public void setRenRendicion(RenRendicion renRendicion) {
		this.renRendicion = renRendicion;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_rec_id")
	public TpoRecomendacion getTpoRecomendacion() {
		return this.tpoRecomendacion;
	}

	public void setTpoRecomendacion(TpoRecomendacion tpoRecomendacion) {
		this.tpoRecomendacion = tpoRecomendacion;
	}

	@Column(name = "obr_numero_linea")
	public Integer getObrNumeroLinea() {
		return this.obrNumeroLinea;
	}

	public void setObrNumeroLinea(Integer obrNumeroLinea) {
		this.obrNumeroLinea = obrNumeroLinea;
	}

	@Column(name = "obr_numero_pagina")
	public Integer getObrNumeroPagina() {
		return this.obrNumeroPagina;
	}

	public void setObrNumeroPagina(Integer obrNumeroPagina) {
		this.obrNumeroPagina = obrNumeroPagina;
	}

	@Column(name = "obr_habilitada")
	public Boolean getObrHabilitada() {
		return this.obrHabilitada;
	}

	public void setObrHabilitada(Boolean obrHabilitada) {
		this.obrHabilitada = obrHabilitada;
	}

	@Column(name = "obr_respuesta")
	public String getObrRespuesta() {
		return this.obrRespuesta;
	}

	public void setObrRespuesta(String obrRespuesta) {
		this.obrRespuesta = obrRespuesta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "obr_fecha_respuesta", length = 29)
	public Date getObrFechaRespuesta() {
		return this.obrFechaRespuesta;
	}

	public void setObrFechaRespuesta(Date obrFechaRespuesta) {
		this.obrFechaRespuesta = obrFechaRespuesta;
	}

	@Column(name = "obr_tipo_ingreso_respuesta", length = 20)
	public String getObrTipoIngresoRespuesta() {
		return this.obrTipoIngresoRespuesta;
	}

	public void setObrTipoIngresoRespuesta(String obrTipoIngresoRespuesta) {
		this.obrTipoIngresoRespuesta = obrTipoIngresoRespuesta;
	}
	
	@Column(name = "obr_analisis_respuesta")
	public String getObrAnalisisRespuesta() {
		return this.obrAnalisisRespuesta;
	}

	public void setObrAnalisisRespuesta(String obrAnalisisRespuesta) {
		this.obrAnalisisRespuesta = obrAnalisisRespuesta;
	}

}
