package cl.servel.gasto.entity;
// Generated 10-07-2019 17:11:40 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import cl.servel.gasto.entity.DetDetalleNomina;
import cl.servel.gasto.entity.IngIngresos;

/**
 * ParPartido generated by hbm2java
 */
@Entity
@Table(name = "par_partido")
public class ParPartido implements java.io.Serializable {

	private Integer parId;
	private EleEleccion eleEleccion;
	private PacPacto pacPacto;
	private String parNombre;
	private String parSigla;
	private Date parCreated;
	private String parCodigoOrigen;
	private Date parFechaConstitucion;
	private Date parFechaDisolucion;
	private Boolean parEliminado;
	private String parRut;
	private String parNombreAdm;
	private String parMail;
	private String parDireccion;
	private String parCiudad;
	private String parTelefonoCelu;
	private String parEstado;
	private String parComuna;
	private Set<CanCandidato> canCandidatos = new HashSet<CanCandidato>(0);
	private Set<LimLimiteGasto> limLimiteGastos = new HashSet<LimLimiteGasto>(0);
	private Set<ExExpediente> exExpedientes = new HashSet<ExExpediente>(0);
	private Set<ResResumenCalculos> resResumenCalculoses = new HashSet<ResResumenCalculos>(0);
	private Set<DarDetalleActaRecepcion> darDetalleActaRecepcions = new HashSet<DarDetalleActaRecepcion>(0);
	private Set<ManMandato> manMandatos = new HashSet<ManMandato>(0);
	private Set<RlcSubpactoPartido> rlcSubpactoPartidos = new HashSet<RlcSubpactoPartido>(0);
	private Set<CctCuentaContable> cctCuentaContables = new HashSet<CctCuentaContable>(0);
	private Set<InfInstanciaFlujo> infInstanciaFlujos = new HashSet<InfInstanciaFlujo>(0);
	private Set<AdmAdministradorElectoral> admAdministradorElectorals = new HashSet<AdmAdministradorElectoral>(0);
	private Set<RenRendicion> renRendicions = new HashSet<RenRendicion>(0);
	private Set<DetDetalleNomina> detDetalleNominas = new HashSet<DetDetalleNomina>(0);
	private Set<IngIngresos> ingIngresoses = new HashSet<IngIngresos>(0);
	private Set<HisHistorico> hisHistoricos = new HashSet<HisHistorico>(0);

	public ParPartido() {
	}

	public ParPartido(EleEleccion eleEleccion) {
		this.eleEleccion = eleEleccion;
	}

	public ParPartido(EleEleccion eleEleccion, PacPacto pacPacto, String parNombre, String parSigla, Date parCreated,
			String parCodigoOrigen, Date parFechaConstitucion, Date parFechaDisolucion, Boolean parEliminado,
			String parRut, String parNombreAdm, String parMail, String parDireccion, String parCiudad,
			String parTelefonoCelu, String parEstado, String parComuna, Set<CanCandidato> canCandidatos,
			Set<LimLimiteGasto> limLimiteGastos, Set<ExExpediente> exExpedientes,
			Set<ResResumenCalculos> resResumenCalculoses, Set<DarDetalleActaRecepcion> darDetalleActaRecepcions,
			Set<ManMandato> manMandatos, Set<RlcSubpactoPartido> rlcSubpactoPartidos,
			Set<CctCuentaContable> cctCuentaContables, Set<InfInstanciaFlujo> infInstanciaFlujos,
			Set<AdmAdministradorElectoral> admAdministradorElectorals, Set<RenRendicion> renRendicions,
			Set<DetDetalleNomina> detDetalleNominas, Set<IngIngresos> ingIngresoses, Set<HisHistorico> hisHistoricos) {
		this.eleEleccion = eleEleccion;
		this.pacPacto = pacPacto;
		this.parNombre = parNombre;
		this.parSigla = parSigla;
		this.parCreated = parCreated;
		this.parCodigoOrigen = parCodigoOrigen;
		this.parFechaConstitucion = parFechaConstitucion;
		this.parFechaDisolucion = parFechaDisolucion;
		this.parEliminado = parEliminado;
		this.parRut = parRut;
		this.parNombreAdm = parNombreAdm;
		this.parMail = parMail;
		this.parDireccion = parDireccion;
		this.parCiudad = parCiudad;
		this.parTelefonoCelu = parTelefonoCelu;
		this.parEstado = parEstado;
		this.parComuna = parComuna;
		this.canCandidatos = canCandidatos;
		this.limLimiteGastos = limLimiteGastos;
		this.exExpedientes = exExpedientes;
		this.resResumenCalculoses = resResumenCalculoses;
		this.darDetalleActaRecepcions = darDetalleActaRecepcions;
		this.manMandatos = manMandatos;
		this.rlcSubpactoPartidos = rlcSubpactoPartidos;
		this.cctCuentaContables = cctCuentaContables;
		this.infInstanciaFlujos = infInstanciaFlujos;
		this.admAdministradorElectorals = admAdministradorElectorals;
		this.renRendicions = renRendicions;
		this.detDetalleNominas = detDetalleNominas;
		this.ingIngresoses = ingIngresoses;
		this.hisHistoricos = hisHistoricos;
	}

	@SequenceGenerator(name = "cl.servel.gasto.temporal.ParPartidoIdGenerator", sequenceName = "par_partido_par_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.temporal.ParPartidoIdGenerator")

	@Column(name = "par_id", unique = true, nullable = false)
	public Integer getParId() {
		return this.parId;
	}

	public void setParId(Integer parId) {
		this.parId = parId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ele_id", nullable = false)
	public EleEleccion getEleEleccion() {
		return this.eleEleccion;
	}

	public void setEleEleccion(EleEleccion eleEleccion) {
		this.eleEleccion = eleEleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pac_id")
	public PacPacto getPacPacto() {
		return this.pacPacto;
	}

	public void setPacPacto(PacPacto pacPacto) {
		this.pacPacto = pacPacto;
	}

	@Column(name = "par_nombre", length = 80)
	public String getParNombre() {
		return this.parNombre;
	}

	public void setParNombre(String parNombre) {
		this.parNombre = parNombre;
	}

	@Column(name = "par_sigla", length = 15)
	public String getParSigla() {
		return this.parSigla;
	}

	public void setParSigla(String parSigla) {
		this.parSigla = parSigla;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "par_created", length = 13)
	public Date getParCreated() {
		return this.parCreated;
	}

	public void setParCreated(Date parCreated) {
		this.parCreated = parCreated;
	}

	@Column(name = "par_codigo_origen", length = 10)
	public String getParCodigoOrigen() {
		return this.parCodigoOrigen;
	}

	public void setParCodigoOrigen(String parCodigoOrigen) {
		this.parCodigoOrigen = parCodigoOrigen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "par_fecha_constitucion", length = 13)
	public Date getParFechaConstitucion() {
		return this.parFechaConstitucion;
	}

	public void setParFechaConstitucion(Date parFechaConstitucion) {
		this.parFechaConstitucion = parFechaConstitucion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "par_fecha_disolucion", length = 13)
	public Date getParFechaDisolucion() {
		return this.parFechaDisolucion;
	}

	public void setParFechaDisolucion(Date parFechaDisolucion) {
		this.parFechaDisolucion = parFechaDisolucion;
	}

	@Column(name = "par_eliminado")
	public Boolean getParEliminado() {
		return this.parEliminado;
	}

	public void setParEliminado(Boolean parEliminado) {
		this.parEliminado = parEliminado;
	}

	@Column(name = "par_rut", length = 10)
	public String getParRut() {
		return this.parRut;
	}

	public void setParRut(String parRut) {
		this.parRut = parRut;
	}

	@Column(name = "par_nombre_adm", length = 30)
	public String getParNombreAdm() {
		return this.parNombreAdm;
	}

	public void setParNombreAdm(String parNombreAdm) {
		this.parNombreAdm = parNombreAdm;
	}

	@Column(name = "par_mail", length = 50)
	public String getParMail() {
		return this.parMail;
	}

	public void setParMail(String parMail) {
		this.parMail = parMail;
	}

	@Column(name = "par_direccion", length = 50)
	public String getParDireccion() {
		return this.parDireccion;
	}

	public void setParDireccion(String parDireccion) {
		this.parDireccion = parDireccion;
	}

	@Column(name = "par_ciudad", length = 50)
	public String getParCiudad() {
		return this.parCiudad;
	}

	public void setParCiudad(String parCiudad) {
		this.parCiudad = parCiudad;
	}

	@Column(name = "par_telefono_celu", length = 10)
	public String getParTelefonoCelu() {
		return this.parTelefonoCelu;
	}

	public void setParTelefonoCelu(String parTelefonoCelu) {
		this.parTelefonoCelu = parTelefonoCelu;
	}

	@Column(name = "par_estado", length = 15)
	public String getParEstado() {
		return this.parEstado;
	}

	public void setParEstado(String parEstado) {
		this.parEstado = parEstado;
	}

	@Column(name = "par_comuna", length = 30)
	public String getParComuna() {
		return this.parComuna;
	}

	public void setParComuna(String parComuna) {
		this.parComuna = parComuna;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<CanCandidato> getCanCandidatos() {
		return this.canCandidatos;
	}

	public void setCanCandidatos(Set<CanCandidato> canCandidatos) {
		this.canCandidatos = canCandidatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<LimLimiteGasto> getLimLimiteGastos() {
		return this.limLimiteGastos;
	}

	public void setLimLimiteGastos(Set<LimLimiteGasto> limLimiteGastos) {
		this.limLimiteGastos = limLimiteGastos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<ExExpediente> getExExpedientes() {
		return this.exExpedientes;
	}

	public void setExExpedientes(Set<ExExpediente> exExpedientes) {
		this.exExpedientes = exExpedientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<ResResumenCalculos> getResResumenCalculoses() {
		return this.resResumenCalculoses;
	}

	public void setResResumenCalculoses(Set<ResResumenCalculos> resResumenCalculoses) {
		this.resResumenCalculoses = resResumenCalculoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<DarDetalleActaRecepcion> getDarDetalleActaRecepcions() {
		return this.darDetalleActaRecepcions;
	}

	public void setDarDetalleActaRecepcions(Set<DarDetalleActaRecepcion> darDetalleActaRecepcions) {
		this.darDetalleActaRecepcions = darDetalleActaRecepcions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<ManMandato> getManMandatos() {
		return this.manMandatos;
	}

	public void setManMandatos(Set<ManMandato> manMandatos) {
		this.manMandatos = manMandatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<RlcSubpactoPartido> getRlcSubpactoPartidos() {
		return this.rlcSubpactoPartidos;
	}

	public void setRlcSubpactoPartidos(Set<RlcSubpactoPartido> rlcSubpactoPartidos) {
		this.rlcSubpactoPartidos = rlcSubpactoPartidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<CctCuentaContable> getCctCuentaContables() {
		return this.cctCuentaContables;
	}

	public void setCctCuentaContables(Set<CctCuentaContable> cctCuentaContables) {
		this.cctCuentaContables = cctCuentaContables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<InfInstanciaFlujo> getInfInstanciaFlujos() {
		return this.infInstanciaFlujos;
	}

	public void setInfInstanciaFlujos(Set<InfInstanciaFlujo> infInstanciaFlujos) {
		this.infInstanciaFlujos = infInstanciaFlujos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<AdmAdministradorElectoral> getAdmAdministradorElectorals() {
		return this.admAdministradorElectorals;
	}

	public void setAdmAdministradorElectorals(Set<AdmAdministradorElectoral> admAdministradorElectorals) {
		this.admAdministradorElectorals = admAdministradorElectorals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<RenRendicion> getRenRendicions() {
		return this.renRendicions;
	}

	public void setRenRendicions(Set<RenRendicion> renRendicions) {
		this.renRendicions = renRendicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<DetDetalleNomina> getDetDetalleNominas() {
		return this.detDetalleNominas;
	}

	public void setDetDetalleNominas(Set<DetDetalleNomina> detDetalleNominas) {
		this.detDetalleNominas = detDetalleNominas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<IngIngresos> getIngIngresoses() {
		return this.ingIngresoses;
	}

	public void setIngIngresoses(Set<IngIngresos> ingIngresoses) {
		this.ingIngresoses = ingIngresoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartido")
	public Set<HisHistorico> getHisHistoricos() {
		return this.hisHistoricos;
	}

	public void setHisHistoricos(Set<HisHistorico> hisHistoricos) {
		this.hisHistoricos = hisHistoricos;
	}

}
