package cl.servel.gasto.entity;
// Generated 02-01-2019 19:29:27 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * RenRendicion generated by hbm2java
 */
@Entity
@Table(name = "ren_rendicion")
public class RenRendicion implements java.io.Serializable {

	private Integer renId;
	private CanCandidato canCandidato;
	private EleEleccion eleEleccion;
	private EveEventoEleccionario eveEventoEleccionario;
	private ParPartido parPartido;
	private TpoRendicion tpoRendicion;
	private Integer renNumeroRendicion;
	private Date renFecha;
	private String renEstado;
	private Long renTotalRendicion;
	private Integer renNumeroDocumento;
	private int renTotalLineas;
	private String renLineasRevisadas;
	private Set<ObrObservacionRendicion> obrObservacionRendicions = new HashSet<ObrObservacionRendicion>(0);
	private Set<RlcDetalleActaRendicion> rlcDetalleActaRendicions = new HashSet<RlcDetalleActaRendicion>(0);
	private Set<DocDocumentoAdjunto> docDocumentoAdjuntos = new HashSet<DocDocumentoAdjunto>(0);
	private Set<DetDetalleRendicion> detDetalleRendicions = new HashSet<DetDetalleRendicion>(0);

	public RenRendicion() {
	}

	public RenRendicion(EleEleccion eleEleccion, EveEventoEleccionario eveEventoEleccionario, TpoRendicion tpoRendicion, int renTotalLineas, String renLineasRevisadas) {
		this.eleEleccion = eleEleccion;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoRendicion = tpoRendicion;
		this.renTotalLineas = renTotalLineas;
		this.renLineasRevisadas = renLineasRevisadas;
	}

	public RenRendicion(CanCandidato canCandidato, EleEleccion eleEleccion, EveEventoEleccionario eveEventoEleccionario, ParPartido parPartido, TpoRendicion tpoRendicion, Integer renNumeroRendicion, Date renFecha, String renEstado, Long renTotalRendicion, Integer renNumeroDocumento, int renTotalLineas, String renLineasRevisadas, Set<ObrObservacionRendicion> obrObservacionRendicions,
			Set<RlcDetalleActaRendicion> rlcDetalleActaRendicions, Set<DocDocumentoAdjunto> docDocumentoAdjuntos, Set<DetDetalleRendicion> detDetalleRendicions) {
		this.canCandidato = canCandidato;
		this.eleEleccion = eleEleccion;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.parPartido = parPartido;
		this.tpoRendicion = tpoRendicion;
		this.renNumeroRendicion = renNumeroRendicion;
		this.renFecha = renFecha;
		this.renEstado = renEstado;
		this.renTotalRendicion = renTotalRendicion;
		this.renNumeroDocumento = renNumeroDocumento;
		this.renTotalLineas = renTotalLineas;
		this.renLineasRevisadas = renLineasRevisadas;
		this.obrObservacionRendicions = obrObservacionRendicions;
		this.rlcDetalleActaRendicions = rlcDetalleActaRendicions;
		this.docDocumentoAdjuntos = docDocumentoAdjuntos;
		this.detDetalleRendicions = detDetalleRendicions;
	}

	@SequenceGenerator(name = "RenRendicionIdGenerator", sequenceName = "ren_rendicion_ren_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "RenRendicionIdGenerator")

	@Column(name = "ren_id", unique = true, nullable = false)
	public Integer getRenId() {
		return this.renId;
	}

	public void setRenId(Integer renId) {
		this.renId = renId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "can_id")
	public CanCandidato getCanCandidato() {
		return this.canCandidato;
	}

	public void setCanCandidato(CanCandidato canCandidato) {
		this.canCandidato = canCandidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ele_id", nullable = false)
	public EleEleccion getEleEleccion() {
		return this.eleEleccion;
	}

	public void setEleEleccion(EleEleccion eleEleccion) {
		this.eleEleccion = eleEleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id")
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_rendicion_id", nullable = false)
	public TpoRendicion getTpoRendicion() {
		return this.tpoRendicion;
	}

	public void setTpoRendicion(TpoRendicion tpoRendicion) {
		this.tpoRendicion = tpoRendicion;
	}

	@Column(name = "ren_numero_rendicion")
	public Integer getRenNumeroRendicion() {
		return this.renNumeroRendicion;
	}

	public void setRenNumeroRendicion(Integer renNumeroRendicion) {
		this.renNumeroRendicion = renNumeroRendicion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ren_fecha", length = 13)
	public Date getRenFecha() {
		return this.renFecha;
	}

	public void setRenFecha(Date renFecha) {
		this.renFecha = renFecha;
	}

	@Column(name = "ren_estado", length = 15)
	public String getRenEstado() {
		return this.renEstado;
	}

	public void setRenEstado(String renEstado) {
		this.renEstado = renEstado;
	}

	@Column(name = "ren_total_rendicion")
	public Long getRenTotalRendicion() {
		return this.renTotalRendicion;
	}

	public void setRenTotalRendicion(Long renTotalRendicion) {
		this.renTotalRendicion = renTotalRendicion;
	}

	@Column(name = "ren_numero_documento")
	public Integer getRenNumeroDocumento() {
		return this.renNumeroDocumento;
	}

	public void setRenNumeroDocumento(Integer renNumeroDocumento) {
		this.renNumeroDocumento = renNumeroDocumento;
	}

	@Column(name = "ren_total_lineas", nullable = false)
	public int getRenTotalLineas() {
		return this.renTotalLineas;
	}

	public void setRenTotalLineas(int renTotalLineas) {
		this.renTotalLineas = renTotalLineas;
	}

	@Column(name = "ren_lineas_revisadas")
	public String getRenLineasRevisadas() {
		return this.renLineasRevisadas;
	}

	public void setRenLineasRevisadas(String renLineasRevisadas) {
		this.renLineasRevisadas = renLineasRevisadas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "renRendicion")
	public Set<ObrObservacionRendicion> getObrObservacionRendicions() {
		return this.obrObservacionRendicions;
	}

	public void setObrObservacionRendicions(Set<ObrObservacionRendicion> obrObservacionRendicions) {
		this.obrObservacionRendicions = obrObservacionRendicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "renRendicion")
	public Set<RlcDetalleActaRendicion> getRlcDetalleActaRendicions() {
		return this.rlcDetalleActaRendicions;
	}

	public void setRlcDetalleActaRendicions(Set<RlcDetalleActaRendicion> rlcDetalleActaRendicions) {
		this.rlcDetalleActaRendicions = rlcDetalleActaRendicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "renRendicion")
	public Set<DocDocumentoAdjunto> getDocDocumentoAdjuntos() {
		return this.docDocumentoAdjuntos;
	}

	public void setDocDocumentoAdjuntos(Set<DocDocumentoAdjunto> docDocumentoAdjuntos) {
		this.docDocumentoAdjuntos = docDocumentoAdjuntos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "renRendicion")
	public Set<DetDetalleRendicion> getDetDetalleRendicions() {
		return this.detDetalleRendicions;
	}

	public void setDetDetalleRendicions(Set<DetDetalleRendicion> detDetalleRendicions) {
		this.detDetalleRendicions = detDetalleRendicions;
	}

}