package cl.servel.gasto.entity;
// Generated 11-03-2019 10:17:14 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ResumenCarga generated by hbm2java
 */
@Entity
@Table(name = "resumen_carga")
public class ResumenCarga implements java.io.Serializable {

	private Integer recId;
	private CadCargaDatos cadCargaDatos;
	private EleEleccion eleEleccion;
	private String recTipoCarga;
	private Integer recTotalRegistros;
	private Integer recRegistrosBuenos;
	private Integer recRegistrosMalos;
	private Date recFechaInicio;
	private Date recFechaTermino;
	private String recEstadoCarga;
	private Set<DecDetalleCarga> decDetalleCargas = new HashSet<DecDetalleCarga>(0);

	public ResumenCarga() {
	}

	public ResumenCarga(CadCargaDatos cadCargaDatos, EleEleccion eleEleccion) {
		this.cadCargaDatos = cadCargaDatos;
		this.eleEleccion = eleEleccion;
	}

	public ResumenCarga(CadCargaDatos cadCargaDatos, EleEleccion eleEleccion, String recTipoCarga,
			Integer recTotalRegistros, Integer recRegistrosBuenos, Integer recRegistrosMalos, Date recFechaInicio,
			Date recFechaTermino, String recEstadoCarga, Set<DecDetalleCarga> decDetalleCargas) {
		this.cadCargaDatos = cadCargaDatos;
		this.eleEleccion = eleEleccion;
		this.recTipoCarga = recTipoCarga;
		this.recTotalRegistros = recTotalRegistros;
		this.recRegistrosBuenos = recRegistrosBuenos;
		this.recRegistrosMalos = recRegistrosMalos;
		this.recFechaInicio = recFechaInicio;
		this.recFechaTermino = recFechaTermino;
		this.recEstadoCarga = recEstadoCarga;
		this.decDetalleCargas = decDetalleCargas;
	}

	@SequenceGenerator(name = "ResumenCargaIdGenerator", sequenceName = "resumen_carga_rec_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "ResumenCargaIdGenerator")

	@Column(name = "rec_id", unique = true, nullable = false)
	public Integer getRecId() {
		return this.recId;
	}

	public void setRecId(Integer recId) {
		this.recId = recId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cad_id", nullable = false)
	public CadCargaDatos getCadCargaDatos() {
		return this.cadCargaDatos;
	}

	public void setCadCargaDatos(CadCargaDatos cadCargaDatos) {
		this.cadCargaDatos = cadCargaDatos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ele_id", nullable = false)
	public EleEleccion getEleEleccion() {
		return this.eleEleccion;
	}

	public void setEleEleccion(EleEleccion eleEleccion) {
		this.eleEleccion = eleEleccion;
	}

	@Column(name = "rec_tipo_carga", length = 30)
	public String getRecTipoCarga() {
		return this.recTipoCarga;
	}

	public void setRecTipoCarga(String recTipoCarga) {
		this.recTipoCarga = recTipoCarga;
	}

	@Column(name = "rec_total_registros")
	public Integer getRecTotalRegistros() {
		return this.recTotalRegistros;
	}

	public void setRecTotalRegistros(Integer recTotalRegistros) {
		this.recTotalRegistros = recTotalRegistros;
	}

	@Column(name = "rec_registros_buenos")
	public Integer getRecRegistrosBuenos() {
		return this.recRegistrosBuenos;
	}

	public void setRecRegistrosBuenos(Integer recRegistrosBuenos) {
		this.recRegistrosBuenos = recRegistrosBuenos;
	}

	@Column(name = "rec_registros_malos")
	public Integer getRecRegistrosMalos() {
		return this.recRegistrosMalos;
	}

	public void setRecRegistrosMalos(Integer recRegistrosMalos) {
		this.recRegistrosMalos = recRegistrosMalos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_fecha_inicio", length = 29)
	public Date getRecFechaInicio() {
		return this.recFechaInicio;
	}

	public void setRecFechaInicio(Date recFechaInicio) {
		this.recFechaInicio = recFechaInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rec_fecha_termino", length = 29)
	public Date getRecFechaTermino() {
		return this.recFechaTermino;
	}

	public void setRecFechaTermino(Date recFechaTermino) {
		this.recFechaTermino = recFechaTermino;
	}

	@Column(name = "rec_estado_carga", length = 15)
	public String getRecEstadoCarga() {
		return this.recEstadoCarga;
	}

	public void setRecEstadoCarga(String recEstadoCarga) {
		this.recEstadoCarga = recEstadoCarga;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resumenCarga")
	public Set<DecDetalleCarga> getDecDetalleCargas() {
		return this.decDetalleCargas;
	}

	public void setDecDetalleCargas(Set<DecDetalleCarga> decDetalleCargas) {
		this.decDetalleCargas = decDetalleCargas;
	}

}
