package cl.servel.gasto.entity;
// Generated 04-10-2018 19:09:57 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * RlcAdminCandidato generated by hbm2java
 */
@Entity
@Table(name = "rlc_admin_candidato")
public class RlcAdminCandidato implements java.io.Serializable {

	private Integer rlcId;
	private AdmAdministradorElectoral admAdministradorElectoral;
	private CanCandidato canCandidato;
	private EveEventoEleccionario eveEventoEleccionario;
	private String rlcAdminEstado;
	private Date rlcAdminFecha;
	private Date rlcAdminFechaTermino;
	private Boolean rlcAdminEliminado;
	private Date rlcAdminCreated;
	private Date rlcAdminModified;

	public RlcAdminCandidato() {
	}

	public RlcAdminCandidato(AdmAdministradorElectoral admAdministradorElectoral, CanCandidato canCandidato,
			EveEventoEleccionario eveEventoEleccionario) {
		this.admAdministradorElectoral = admAdministradorElectoral;
		this.canCandidato = canCandidato;
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	public RlcAdminCandidato(AdmAdministradorElectoral admAdministradorElectoral, CanCandidato canCandidato,
			EveEventoEleccionario eveEventoEleccionario, String rlcAdminEstado, Date rlcAdminFecha, Date rlcAdminFechaTermino,
			Boolean rlcAdminEliminado, Date rlcAdminCreated, Date rlcAdminModified) {
		this.admAdministradorElectoral = admAdministradorElectoral;
		this.canCandidato = canCandidato;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.rlcAdminEstado = rlcAdminEstado;
		this.rlcAdminFecha = rlcAdminFecha;
		this.rlcAdminFechaTermino = rlcAdminFechaTermino;
		this.rlcAdminEliminado = rlcAdminEliminado;
		this.rlcAdminCreated = rlcAdminCreated;
		this.rlcAdminModified = rlcAdminModified;
	}

	@SequenceGenerator(name = "cl.servel.gasto.entity.RlcAdminCandidatoIdGenerator", sequenceName = "rlc_admin_candidato_rlc_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.entity.RlcAdminCandidatoIdGenerator")

	@Column(name = "rlc_id", unique = true, nullable = false)
	public Integer getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(Integer rlcId) {
		this.rlcId = rlcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "adm_id", nullable = false)
	public AdmAdministradorElectoral getAdmAdministradorElectoral() {
		return this.admAdministradorElectoral;
	}

	public void setAdmAdministradorElectoral(AdmAdministradorElectoral admAdministradorElectoral) {
		this.admAdministradorElectoral = admAdministradorElectoral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "can_id", nullable = false)
	public CanCandidato getCanCandidato() {
		return this.canCandidato;
	}

	public void setCanCandidato(CanCandidato canCandidato) {
		this.canCandidato = canCandidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@Column(name = "rlc_admin_estado", length = 5)
	public String getRlcAdminEstado() {
		return this.rlcAdminEstado;
	}

	public void setRlcAdminEstado(String rlcAdminEstado) {
		this.rlcAdminEstado = rlcAdminEstado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rlc_admin_fecha", length = 13)
	public Date getRlcAdminFecha() {
		return this.rlcAdminFecha;
	}

	public void setRlcAdminFecha(Date rlcAdminFecha) {
		this.rlcAdminFecha = rlcAdminFecha;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rlc_admin_fecha_termino", length = 13)
	public Date getRlcAdminFechaTermino() {
		return this.rlcAdminFecha;
	}

	public void setRlcAdminFechaTermino(Date rlcAdminFechaTermino) {
		this.rlcAdminFechaTermino = rlcAdminFechaTermino;
	}
	
	@Column(name = "rlc_admin_eliminado")
	public Boolean getRlcAdminEliminado() {
		return this.rlcAdminEliminado;
	}

	public void setRlcAdminEliminado(Boolean rlcAdminEliminado) {
		this.rlcAdminEliminado = rlcAdminEliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rlc_admin_created", length = 13)
	public Date getRlcAdminCreated() {
		return this.rlcAdminCreated;
	}

	public void setRlcAdminCreated(Date rlcAdminCreated) {
		this.rlcAdminCreated = rlcAdminCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rlc_admin_modified", length = 13)
	public Date getRlcAdminModified() {
		return this.rlcAdminModified;
	}

	public void setRlcAdminModified(Date rlcAdminModified) {
		this.rlcAdminModified = rlcAdminModified;
	}

}
