package cl.servel.gasto.entity;
// Generated 12-02-2019 12:52:01 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RlcDetalleActaRendicion generated by hbm2java
 */
@Entity
@Table(name = "rlc_detalle_acta_rendicion")
public class RlcDetalleActaRendicion implements java.io.Serializable {

	private Integer rlcDarId;
	private DarDetalleActaRecepcion darDetalleActaRecepcion;
	private RenRendicion renRendicion;

	public RlcDetalleActaRendicion() {
	}

	public RlcDetalleActaRendicion(DarDetalleActaRecepcion darDetalleActaRecepcion, RenRendicion renRendicion) {
		this.darDetalleActaRecepcion = darDetalleActaRecepcion;
		this.renRendicion = renRendicion;
	}

	@SequenceGenerator(name = "RlcDetalleActaRendicionIdGenerator", sequenceName = "rlc_detalle_acta_rendicion_rlc_dar_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "RlcDetalleActaRendicionIdGenerator")

	@Column(name = "rlc_dar_id", unique = true, nullable = false)
	public Integer getRlcDarId() {
		return this.rlcDarId;
	}

	public void setRlcDarId(Integer rlcDarId) {
		this.rlcDarId = rlcDarId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dar_id", nullable = false)
	public DarDetalleActaRecepcion getDarDetalleActaRecepcion() {
		return this.darDetalleActaRecepcion;
	}

	public void setDarDetalleActaRecepcion(DarDetalleActaRecepcion darDetalleActaRecepcion) {
		this.darDetalleActaRecepcion = darDetalleActaRecepcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ren_id", nullable = false)
	public RenRendicion getRenRendicion() {
		return this.renRendicion;
	}

	public void setRenRendicion(RenRendicion renRendicion) {
		this.renRendicion = renRendicion;
	}

}
