package cl.servel.gasto.entity;
// Generated 21-03-2019 14:36:24 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RlcTarea generated by hbm2java
 */
@Entity
@Table(name = "rlc_tarea")
public class RlcTarea implements java.io.Serializable {

	private Integer rlcId;
	private DtaDefinicionTarea dtaDefinicionTareaByRlcIdAnterior;
	private DtaDefinicionTarea dtaDefinicionTareaByRlcIdSiguiente;
	private DtaDefinicionTarea dtaDefinicionTareaByDtaId;
	private String rlcCondicion;
	private boolean rlcRutaActiva;

	public RlcTarea() {
	}

	public RlcTarea(DtaDefinicionTarea dtaDefinicionTareaByRlcIdAnterior, DtaDefinicionTarea dtaDefinicionTareaByRlcIdSiguiente, DtaDefinicionTarea dtaDefinicionTareaByDtaId, boolean rlcRutaActiva) {
		this.dtaDefinicionTareaByRlcIdAnterior = dtaDefinicionTareaByRlcIdAnterior;
		this.dtaDefinicionTareaByRlcIdSiguiente = dtaDefinicionTareaByRlcIdSiguiente;
		this.dtaDefinicionTareaByDtaId = dtaDefinicionTareaByDtaId;
		this.rlcRutaActiva = rlcRutaActiva;
	}

	public RlcTarea(DtaDefinicionTarea dtaDefinicionTareaByRlcIdAnterior, DtaDefinicionTarea dtaDefinicionTareaByRlcIdSiguiente, DtaDefinicionTarea dtaDefinicionTareaByDtaId, String rlcCondicion, boolean rlcRutaActiva) {
		this.dtaDefinicionTareaByRlcIdAnterior = dtaDefinicionTareaByRlcIdAnterior;
		this.dtaDefinicionTareaByRlcIdSiguiente = dtaDefinicionTareaByRlcIdSiguiente;
		this.dtaDefinicionTareaByDtaId = dtaDefinicionTareaByDtaId;
		this.rlcCondicion = rlcCondicion;
		this.rlcRutaActiva = rlcRutaActiva;
	}

	@SequenceGenerator(name = "RlcTareaIdGenerator", sequenceName = "rlc_tarea_rlc_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "RlcTareaIdGenerator")

	@Column(name = "rlc_id", unique = true, nullable = false)
	public Integer getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(Integer rlcId) {
		this.rlcId = rlcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rlc_id_anterior", nullable = false)
	public DtaDefinicionTarea getDtaDefinicionTareaByRlcIdAnterior() {
		return this.dtaDefinicionTareaByRlcIdAnterior;
	}

	public void setDtaDefinicionTareaByRlcIdAnterior(DtaDefinicionTarea dtaDefinicionTareaByRlcIdAnterior) {
		this.dtaDefinicionTareaByRlcIdAnterior = dtaDefinicionTareaByRlcIdAnterior;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rlc_id_siguiente", nullable = false)
	public DtaDefinicionTarea getDtaDefinicionTareaByRlcIdSiguiente() {
		return this.dtaDefinicionTareaByRlcIdSiguiente;
	}

	public void setDtaDefinicionTareaByRlcIdSiguiente(DtaDefinicionTarea dtaDefinicionTareaByRlcIdSiguiente) {
		this.dtaDefinicionTareaByRlcIdSiguiente = dtaDefinicionTareaByRlcIdSiguiente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dta_id", nullable = false)
	public DtaDefinicionTarea getDtaDefinicionTareaByDtaId() {
		return this.dtaDefinicionTareaByDtaId;
	}

	public void setDtaDefinicionTareaByDtaId(DtaDefinicionTarea dtaDefinicionTareaByDtaId) {
		this.dtaDefinicionTareaByDtaId = dtaDefinicionTareaByDtaId;
	}

	@Column(name = "rlc_condicion", length = 100)
	public String getRlcCondicion() {
		return this.rlcCondicion;
	}

	public void setRlcCondicion(String rlcCondicion) {
		this.rlcCondicion = rlcCondicion;
	}

	@Column(name = "rlc_ruta_activa", nullable = false)
	public boolean isRlcRutaActiva() {
		return this.rlcRutaActiva;
	}

	public void setRlcRutaActiva(boolean rlcRutaActiva) {
		this.rlcRutaActiva = rlcRutaActiva;
	}

}
