package cl.servel.gasto.entity;
// Generated 12-06-2019 10:30:57 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RlcUsuarioRolUsuario generated by hbm2java
 */
@Entity
@Table(name = "rlc_usuario_rol_usuario")
public class RlcUsuarioRolUsuario implements java.io.Serializable {

	private Integer rlcId;
	private RolUsuario rolUsuario;
	private UsuUsuarios usuUsuarios;

	public RlcUsuarioRolUsuario() {
	}

	public RlcUsuarioRolUsuario(RolUsuario rolUsuario, UsuUsuarios usuUsuarios) {
		this.rolUsuario = rolUsuario;
		this.usuUsuarios = usuUsuarios;
	}

	@SequenceGenerator(name = "RlcUsuarioRolUsuarioIdGenerator", sequenceName = "rlc_usuario_rol_usuario_rlc_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "RlcUsuarioRolUsuarioIdGenerator")

	@Column(name = "rlc_id", unique = true, nullable = false)
	public Integer getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(Integer rlcId) {
		this.rlcId = rlcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_id", nullable = false)
	public RolUsuario getRolUsuario() {
		return this.rolUsuario;
	}

	public void setRolUsuario(RolUsuario rolUsuario) {
		this.rolUsuario = rolUsuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usu_id", nullable = false)
	public UsuUsuarios getUsuUsuarios() {
		return this.usuUsuarios;
	}

	public void setUsuUsuarios(UsuUsuarios usuUsuarios) {
		this.usuUsuarios = usuUsuarios;
	}

}
