package cl.servel.gasto.entity;
// default package
// Generated 09-04-2019 10:17:53 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TpoConceptoCtaGasto generated by hbm2java
 */
@Entity
@Table(name = "tpo_concepto_cta_gasto")
public class TpoConceptoCtaGasto implements java.io.Serializable {
	
	private Integer tpoConceptoId;
	private EveEventoEleccionario eveEventoEleccionario;
	private TpoRendicion tpoRendicion;
	private String tpoConceptoCodigo;
	private String tpoConceptoNombre;
	private Set<RlcConceptoCtaGasto> rlcConceptoCtaGastos = new HashSet<RlcConceptoCtaGasto>(0);

	public TpoConceptoCtaGasto() {
	}

	public TpoConceptoCtaGasto(EveEventoEleccionario eveEventoEleccionario, TpoRendicion tpoRendicion) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoRendicion = tpoRendicion;
	}

	public TpoConceptoCtaGasto(EveEventoEleccionario eveEventoEleccionario, TpoRendicion tpoRendicion,
			String tpoConceptoCodigo, String tpoConceptoNombre, Set<RlcConceptoCtaGasto> rlcConceptoCtaGastos) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoRendicion = tpoRendicion;
		this.tpoConceptoCodigo = tpoConceptoCodigo;
		this.tpoConceptoNombre = tpoConceptoNombre;
		this.rlcConceptoCtaGastos = rlcConceptoCtaGastos;
	}

	@SequenceGenerator(name = "TpoConceptoCtaGastoIdGenerator", sequenceName = "tpo_concepto_cta_gasto_tpo_concepto_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "TpoConceptoCtaGastoIdGenerator")

	@Column(name = "tpo_concepto_id", unique = true, nullable = false)
	public Integer getTpoConceptoId() {
		return this.tpoConceptoId;
	}

	public void setTpoConceptoId(Integer tpoConceptoId) {
		this.tpoConceptoId = tpoConceptoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_rendicion_id", nullable = false)
	public TpoRendicion getTpoRendicion() {
		return this.tpoRendicion;
	}

	public void setTpoRendicion(TpoRendicion tpoRendicion) {
		this.tpoRendicion = tpoRendicion;
	}

	@Column(name = "tpo_concepto_codigo", length = 10)
	public String getTpoConceptoCodigo() {
		return this.tpoConceptoCodigo;
	}

	public void setTpoConceptoCodigo(String tpoConceptoCodigo) {
		this.tpoConceptoCodigo = tpoConceptoCodigo;
	}

	@Column(name = "tpo_concepto_nombre", length = 80)
	public String getTpoConceptoNombre() {
		return this.tpoConceptoNombre;
	}

	public void setTpoConceptoNombre(String tpoConceptoNombre) {
		this.tpoConceptoNombre = tpoConceptoNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoConceptoCtaGasto")
	public Set<RlcConceptoCtaGasto> getRlcConceptoCtaGastos() {
		return this.rlcConceptoCtaGastos;
	}

	public void setRlcConceptoCtaGastos(Set<RlcConceptoCtaGasto> rlcConceptoCtaGastos) {
		this.rlcConceptoCtaGastos = rlcConceptoCtaGastos;
	}

}
