package cl.servel.gasto.entity;
// Generated 21-06-2019 12:42:33 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TpoEvento generated by hbm2java
 */
@Entity
@Table(name = "tpo_evento")
public class TpoEvento implements java.io.Serializable {

	private Integer tpoEventoId;
	private String tpoEventoNombre;
	private Integer tpoEventoOrden;
	private String tpoCodigoOrigen;
	private Set<ConConfiguracion> conConfiguracions = new HashSet<ConConfiguracion>(0);
	private Set<EleEleccion> eleEleccions = new HashSet<EleEleccion>(0);
	private Set<AcrActaRecepcion> acrActaRecepcions = new HashSet<AcrActaRecepcion>(0);

	public TpoEvento() {
	}

	public TpoEvento(String tpoEventoNombre, Integer tpoEventoOrden, String tpoCodigoOrigen,
			Set<ConConfiguracion> conConfiguracions, Set<EleEleccion> eleEleccions,
			Set<AcrActaRecepcion> acrActaRecepcions) {
		this.tpoEventoNombre = tpoEventoNombre;
		this.tpoEventoOrden = tpoEventoOrden;
		this.tpoCodigoOrigen = tpoCodigoOrigen;
		this.conConfiguracions = conConfiguracions;
		this.eleEleccions = eleEleccions;
		this.acrActaRecepcions = acrActaRecepcions;
	}

	@Id
	@Column(name = "tpo_evento_id", unique = true, nullable = false)
	public Integer getTpoEventoId() {
		return this.tpoEventoId;
	}

	public void setTpoEventoId(Integer tpoEventoId) {
		this.tpoEventoId = tpoEventoId;
	}

	@Column(name = "tpo_evento_nombre", length = 40)
	public String getTpoEventoNombre() {
		return this.tpoEventoNombre;
	}

	public void setTpoEventoNombre(String tpoEventoNombre) {
		this.tpoEventoNombre = tpoEventoNombre;
	}

	@Column(name = "tpo_evento_orden")
	public Integer getTpoEventoOrden() {
		return this.tpoEventoOrden;
	}

	public void setTpoEventoOrden(Integer tpoEventoOrden) {
		this.tpoEventoOrden = tpoEventoOrden;
	}

	@Column(name = "tpo_codigo_origen", length = 15)
	public String getTpoCodigoOrigen() {
		return this.tpoCodigoOrigen;
	}

	public void setTpoCodigoOrigen(String tpoCodigoOrigen) {
		this.tpoCodigoOrigen = tpoCodigoOrigen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoEvento")
	public Set<ConConfiguracion> getConConfiguracions() {
		return this.conConfiguracions;
	}

	public void setConConfiguracions(Set<ConConfiguracion> conConfiguracions) {
		this.conConfiguracions = conConfiguracions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoEvento")
	public Set<EleEleccion> getEleEleccions() {
		return this.eleEleccions;
	}

	public void setEleEleccions(Set<EleEleccion> eleEleccions) {
		this.eleEleccions = eleEleccions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoEvento")
	public Set<AcrActaRecepcion> getAcrActaRecepcions() {
		return this.acrActaRecepcions;
	}

	public void setAcrActaRecepcions(Set<AcrActaRecepcion> acrActaRecepcions) {
		this.acrActaRecepcions = acrActaRecepcions;
	}

}
