package cl.servel.gasto.entity;
// Generated 28-03-2019 15:27:25 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TpoObservacion generated by hbm2java
 */
@Entity
@Table(name = "tpo_observacion")
public class TpoObservacion implements java.io.Serializable {

	private Integer tpoObsId;
	private EveEventoEleccionario eveEventoEleccionario;												 
	private TpoCtaGasto tpoCtaGasto;
	private String tpoNombreCorto;
	private String tpoDescripcion;

	public TpoObservacion() {
	}

	public TpoObservacion(EveEventoEleccionario eveEventoEleccionario, TpoCtaGasto tpoCtaGasto) {
		this.eveEventoEleccionario = eveEventoEleccionario;										 
		this.tpoCtaGasto = tpoCtaGasto;
	}

	public TpoObservacion(EveEventoEleccionario eveEventoEleccionario, TpoCtaGasto tpoCtaGasto, String tpoNombreCorto, 
		String tpoDescripcion) {
		this.eveEventoEleccionario = eveEventoEleccionario;											 
		this.tpoCtaGasto = tpoCtaGasto;
		this.tpoNombreCorto = tpoNombreCorto;
		this.tpoDescripcion = tpoDescripcion;
	}

	@SequenceGenerator(name = "TpoObservacionIdGenerator", sequenceName = "tpo_observacion_tpo_obs_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "TpoObservacionIdGenerator")
	@Column(name = "tpo_obs_id", unique = true, nullable = false)
	public Integer getTpoObsId() {
		return this.tpoObsId;
	}

	public void setTpoObsId(Integer tpoObsId) {
		this.tpoObsId = tpoObsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}
										   
	@ManyToOne(fetch = FetchType.LAZY)							   
	@JoinColumn(name = "tpo_cta_id", nullable = false)
	public TpoCtaGasto getTpoCtaGasto() {
		return this.tpoCtaGasto;
	}

	public void setTpoCtaGasto(TpoCtaGasto tpoCtaGasto) {
		this.tpoCtaGasto = tpoCtaGasto;
	}

	@Column(name = "tpo_nombre_corto", length = 30)
	public String getTpoNombreCorto() {
		return this.tpoNombreCorto;
	}

	public void setTpoNombreCorto(String tpoNombreCorto) {
		this.tpoNombreCorto = tpoNombreCorto;
	}

	@Column(name = "tpo_descripcion")
	public String getTpoDescripcion() {
		return this.tpoDescripcion;
	}

	public void setTpoDescripcion(String tpoDescripcion) {
		this.tpoDescripcion = tpoDescripcion;
	}

}
