package cl.servel.gasto.entity;
// Generated 10-06-2019 12:32:07 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UsuUsuarios generated by hbm2java
 */
@Entity
@Table(name = "usu_usuarios", uniqueConstraints = @UniqueConstraint(columnNames = "usu_nombre_acceso"))
public class UsuUsuarios implements java.io.Serializable {

	private Integer usuId;
	private DexDocumentoExterno dexDocumentoExterno;
	private String usuRut;
	private String usuRutDv;
	private Boolean usuEliminado;
	private Date created;
	private Date modified;
	private String usuNombreAcceso;
	private String usuNombre;
	private String usuApellidoPaterno;
	private String usuApellidoMaterno;
	private Integer usuIdSubrogante;
	private Set<InfInstanciaFlujo> infInstanciaFlujos = new HashSet<InfInstanciaFlujo>(0);
	private Set<BitBitacora> bitBitacoras = new HashSet<BitBitacora>(0);
	private Set<NomNomina> nomNominas = new HashSet<NomNomina>(0);
	private Set<InbInstanciaBandeja> inbInstanciaBandejas = new HashSet<InbInstanciaBandeja>(0);
	private Set<IntInstanciaTarea> intInstanciaTareas = new HashSet<IntInstanciaTarea>(0);
	private Set<RlcUsuarioRolUsuario> rlcUsuarioRolUsuarios = new HashSet<RlcUsuarioRolUsuario>(0);
	private Set<IngIngresos> ingIngresoses = new HashSet<IngIngresos>(0);
	private Set<RlcUsuarioPerfil> rlcUsuarioPerfils = new HashSet<RlcUsuarioPerfil>(0);
	private Set<UstUsuarioTarea> ustUsuarioTareas = new HashSet<UstUsuarioTarea>(0);

	public UsuUsuarios() {
	}

	public UsuUsuarios(DexDocumentoExterno dexDocumentoExterno, String usuRut, String usuRutDv, Boolean usuEliminado, Date created, Date modified, String usuNombreAcceso, String usuNombre, String usuApellidoPaterno, String usuApellidoMaterno, Integer usuIdSubrogante, Set<InfInstanciaFlujo> infInstanciaFlujos, Set<BitBitacora> bitBitacoras, Set<NomNomina> nomNominas,
			Set<InbInstanciaBandeja> inbInstanciaBandejas, Set<IntInstanciaTarea> intInstanciaTareas, Set<RlcUsuarioRolUsuario> rlcUsuarioRolUsuarios, Set<IngIngresos> ingIngresoses, Set<RlcUsuarioPerfil> rlcUsuarioPerfils, Set<UstUsuarioTarea> ustUsuarioTareas) {
		this.dexDocumentoExterno = dexDocumentoExterno;
		this.usuRut = usuRut;
		this.usuRutDv = usuRutDv;
		this.usuEliminado = usuEliminado;
		this.created = created;
		this.modified = modified;
		this.usuNombreAcceso = usuNombreAcceso;
		this.usuNombre = usuNombre;
		this.usuApellidoPaterno = usuApellidoPaterno;
		this.usuApellidoMaterno = usuApellidoMaterno;
		this.usuIdSubrogante = usuIdSubrogante;
		this.infInstanciaFlujos = infInstanciaFlujos;
		this.bitBitacoras = bitBitacoras;
		this.nomNominas = nomNominas;
		this.inbInstanciaBandejas = inbInstanciaBandejas;
		this.intInstanciaTareas = intInstanciaTareas;
		this.rlcUsuarioRolUsuarios = rlcUsuarioRolUsuarios;
		this.ingIngresoses = ingIngresoses;
		this.rlcUsuarioPerfils = rlcUsuarioPerfils;
		this.ustUsuarioTareas = ustUsuarioTareas;
	}

	@SequenceGenerator(name = "UsuUsuariosIdGenerator", sequenceName = "usu_usuarios_usu_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "UsuUsuariosIdGenerator")

	@Column(name = "usu_id", unique = true, nullable = false)
	public Integer getUsuId() {
		return this.usuId;
	}

	public void setUsuId(Integer usuId) {
		this.usuId = usuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dex_id")
	public DexDocumentoExterno getDexDocumentoExterno() {
		return this.dexDocumentoExterno;
	}

	public void setDexDocumentoExterno(DexDocumentoExterno dexDocumentoExterno) {
		this.dexDocumentoExterno = dexDocumentoExterno;
	}

	@Column(name = "usu_rut")
	public String getUsuRut() {
		return this.usuRut;
	}

	public void setUsuRut(String usuRut) {
		this.usuRut = usuRut;
	}

	@Column(name = "usu_rut_dv", length = 1)
	public String getUsuRutDv() {
		return this.usuRutDv;
	}

	public void setUsuRutDv(String usuRutDv) {
		this.usuRutDv = usuRutDv;
	}

	@Column(name = "usu_eliminado")
	public Boolean getUsuEliminado() {
		return this.usuEliminado;
	}

	public void setUsuEliminado(Boolean usuEliminado) {
		this.usuEliminado = usuEliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", length = 13)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified", length = 13)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "usu_nombre_acceso", unique = true, length = 20)
	public String getUsuNombreAcceso() {
		return this.usuNombreAcceso;
	}

	public void setUsuNombreAcceso(String usuNombreAcceso) {
		this.usuNombreAcceso = usuNombreAcceso;
	}

	@Column(name = "usu_nombre", length = 50)
	public String getUsuNombre() {
		return this.usuNombre;
	}

	public void setUsuNombre(String usuNombre) {
		this.usuNombre = usuNombre;
	}

	@Column(name = "usu_apellido_paterno", length = 50)
	public String getUsuApellidoPaterno() {
		return this.usuApellidoPaterno;
	}

	public void setUsuApellidoPaterno(String usuApellidoPaterno) {
		this.usuApellidoPaterno = usuApellidoPaterno;
	}

	@Column(name = "usu_apellido_materno", length = 50)
	public String getUsuApellidoMaterno() {
		return this.usuApellidoMaterno;
	}

	public void setUsuApellidoMaterno(String usuApellidoMaterno) {
		this.usuApellidoMaterno = usuApellidoMaterno;
	}

	@Column(name = "usu_id_subrogante")
	public Integer getUsuIdSubrogante() {
		return this.usuIdSubrogante;
	}

	public void setUsuIdSubrogante(Integer usuIdSubrogante) {
		this.usuIdSubrogante = usuIdSubrogante;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuUsuarios")
	public Set<InfInstanciaFlujo> getInfInstanciaFlujos() {
		return this.infInstanciaFlujos;
	}

	public void setInfInstanciaFlujos(Set<InfInstanciaFlujo> infInstanciaFlujos) {
		this.infInstanciaFlujos = infInstanciaFlujos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuUsuarios")
	public Set<BitBitacora> getBitBitacoras() {
		return this.bitBitacoras;
	}

	public void setBitBitacoras(Set<BitBitacora> bitBitacoras) {
		this.bitBitacoras = bitBitacoras;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuUsuarios")
	public Set<NomNomina> getNomNominas() {
		return this.nomNominas;
	}

	public void setNomNominas(Set<NomNomina> nomNominas) {
		this.nomNominas = nomNominas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuUsuarios")
	public Set<InbInstanciaBandeja> getInbInstanciaBandejas() {
		return this.inbInstanciaBandejas;
	}

	public void setInbInstanciaBandejas(Set<InbInstanciaBandeja> inbInstanciaBandejas) {
		this.inbInstanciaBandejas = inbInstanciaBandejas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuUsuarios")
	public Set<IntInstanciaTarea> getIntInstanciaTareas() {
		return this.intInstanciaTareas;
	}

	public void setIntInstanciaTareas(Set<IntInstanciaTarea> intInstanciaTareas) {
		this.intInstanciaTareas = intInstanciaTareas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuUsuarios")
	public Set<RlcUsuarioRolUsuario> getRlcUsuarioRolUsuarios() {
		return this.rlcUsuarioRolUsuarios;
	}

	public void setRlcUsuarioRolUsuarios(Set<RlcUsuarioRolUsuario> rlcUsuarioRolUsuarios) {
		this.rlcUsuarioRolUsuarios = rlcUsuarioRolUsuarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuUsuarios")
	public Set<IngIngresos> getIngIngresoses() {
		return this.ingIngresoses;
	}

	public void setIngIngresoses(Set<IngIngresos> ingIngresoses) {
		this.ingIngresoses = ingIngresoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuUsuarios")
	public Set<RlcUsuarioPerfil> getRlcUsuarioPerfils() {
		return this.rlcUsuarioPerfils;
	}

	public void setRlcUsuarioPerfils(Set<RlcUsuarioPerfil> rlcUsuarioPerfils) {
		this.rlcUsuarioPerfils = rlcUsuarioPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuUsuarios")
	public Set<UstUsuarioTarea> getUstUsuarioTareas() {
		return this.ustUsuarioTareas;
	}

	public void setUstUsuarioTareas(Set<UstUsuarioTarea> ustUsuarioTareas) {
		this.ustUsuarioTareas = ustUsuarioTareas;
	}
}
