package cl.servel.gasto.entity;
// Generated 22-01-2019 15:33:10 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AcrActaRecepcion generated by hbm2java
 */
@Entity
@Table(name = "acr_acta_recepcion")
public class AcrActaRecepcion implements java.io.Serializable {

	private Integer acrId;
	private EveEventoEleccionario eveEventoEleccionario;
	private TpoEvento tpoEvento;
	private Date acrFechaRecepcion;
	private String acrObservaciones;
	private String rutResponsable;
	private Character dvResponsable;
	private String nombreResponsable;
	private Date acrCreated;
	private String acrEstado;
	private String acrGlosaSuperior;
	private String acrGlosaInferior;
	private String acrCorreo;
	private Set<DarDetalleActaRecepcion> darDetalleActaRecepcions = new HashSet<DarDetalleActaRecepcion>(0);

	public AcrActaRecepcion() {
	}

	public AcrActaRecepcion(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	public AcrActaRecepcion(EveEventoEleccionario eveEventoEleccionario, TpoEvento tpoEvento, Date acrFechaRecepcion,
			String acrObservaciones, String rutResponsable, Character dvResponsable, String nombreResponsable,
			Date acrCreated, String acrEstado, String acrGlosaSuperior, String acrGlosaInferior, String acrCorreo,Set<DarDetalleActaRecepcion> darDetalleActaRecepcions) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoEvento = tpoEvento;
		this.acrFechaRecepcion = acrFechaRecepcion;
		this.acrObservaciones = acrObservaciones;
		this.rutResponsable = rutResponsable;
		this.dvResponsable = dvResponsable;
		this.nombreResponsable = nombreResponsable;
		this.acrCreated = acrCreated;
		this.acrEstado = acrEstado;
		this.acrGlosaSuperior = acrGlosaSuperior;
		this.acrGlosaInferior = acrGlosaInferior;
		this.acrCorreo = acrCorreo;
		this.darDetalleActaRecepcions = darDetalleActaRecepcions;
	}

	@SequenceGenerator(name = "AcrActaRecepcionIdGenerator", sequenceName = "acr_acta_recepcion_acr_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "AcrActaRecepcionIdGenerator")

	@Column(name = "acr_id", unique = true, nullable = false)
	public Integer getAcrId() {
		return this.acrId;
	}

	public void setAcrId(Integer acrId) {
		this.acrId = acrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_evento_id", nullable = false)
	public TpoEvento getTpoEvento() {
		return this.tpoEvento;
	}

	public void setTpoEvento(TpoEvento tpoEvento) {
		this.tpoEvento = tpoEvento;
	}

	@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "acr_fecha_recepcion", length = 29)
    public Date getAcrFechaRecepcion() {
        return this.acrFechaRecepcion;
    }
	
	public void setAcrFechaRecepcion(Date acrFechaRecepcion) {
		this.acrFechaRecepcion = acrFechaRecepcion;
	}

	@Column(name = "acr_observaciones", length = 200)
	public String getAcrObservaciones() {
		return this.acrObservaciones;
	}

	public void setAcrObservaciones(String acrObservaciones) {
		this.acrObservaciones = acrObservaciones;
	}

	@Column(name = "rut_responsable", length = 10)
	public String getRutResponsable() {
		return this.rutResponsable;
	}

	public void setRutResponsable(String rutResponsable) {
		this.rutResponsable = rutResponsable;
	}

	@Column(name = "dv_responsable", length = 1)
	public Character getDvResponsable() {
		return this.dvResponsable;
	}

	public void setDvResponsable(Character dvResponsable) {
		this.dvResponsable = dvResponsable;
	}

	@Column(name = "nombre_responsable", length = 100)
	public String getNombreResponsable() {
		return this.nombreResponsable;
	}

	public void setNombreResponsable(String nombreResponsable) {
		this.nombreResponsable = nombreResponsable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "acr_created", length = 29)
	public Date getAcrCreated() {
		return this.acrCreated;
	}

	public void setAcrCreated(Date acrCreated) {
		this.acrCreated = acrCreated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acrActaRecepcion")
	public Set<DarDetalleActaRecepcion> getDarDetalleActaRecepcions() {
		return this.darDetalleActaRecepcions;
	}

	public void setDarDetalleActaRecepcions(Set<DarDetalleActaRecepcion> darDetalleActaRecepcions) {
		this.darDetalleActaRecepcions = darDetalleActaRecepcions;
	}

	@Column(name = "acr_estado", length = 10)
	public String getAcrEstado() {
		return this.acrEstado;
	}

	public void setAcrEstado(String acrEstado) {
		this.acrEstado = acrEstado;
	}

	@Column(name = "acr_glosa_superior", length = 5000)
	public String getAcrGlosaSuperior() {
		return this.acrGlosaSuperior;
	}

	public void setAcrGlosaSuperior(String acrGlosaSuperior) {
		this.acrGlosaSuperior = acrGlosaSuperior;
	}

	@Column(name = "acr_glosa_inferior", length = 5000)
	public String getAcrGlosaInferior() {
		return this.acrGlosaInferior;
	}

	public void setAcrGlosaInferior(String acrGlosaInferior) {
		this.acrGlosaInferior = acrGlosaInferior;
	}

	@Column(name = "acr_correo", length = 20)
	public String getAcrCorreo() {
		return this.acrCorreo;
	}

	public void setAcrCorreo(String acrCorreo) {
		this.acrCorreo = acrCorreo;
	}
	
}
