package cl.servel.gasto.entity;
// Generated 28-05-2019 17:59:23 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * ActActividad generated by hbm2java
 */
@Entity
@Table(name = "act_actividad")
public class ActActividad implements java.io.Serializable {

	private Integer actId;
	private IntInstanciaTarea intInstanciaTarea;
	private String actCodigo;
	private String actValorActividad;
	private Date actFechaActividad;
	private Boolean actActividadCompleta;
	private Set<DacDetalleActividad> dacDetalleActividads = new HashSet<DacDetalleActividad>(0);

	public ActActividad() {
	}

	public ActActividad(IntInstanciaTarea intInstanciaTarea, String actCodigo, Date actFechaActividad) {
		this.intInstanciaTarea = intInstanciaTarea;
		this.actCodigo = actCodigo;
		this.actFechaActividad = actFechaActividad;
	}

	public ActActividad(IntInstanciaTarea intInstanciaTarea, String actCodigo, String actValorActividad, Date actFechaActividad, Boolean actActividadCompleta, Set<DacDetalleActividad> dacDetalleActividads) {
		this.intInstanciaTarea = intInstanciaTarea;
		this.actCodigo = actCodigo;
		this.actValorActividad = actValorActividad;
		this.actFechaActividad = actFechaActividad;
		this.actActividadCompleta = actActividadCompleta;
		this.dacDetalleActividads = dacDetalleActividads;
	}

	@SequenceGenerator(name = "ActActividadIdGenerator", sequenceName = "act_actividad_act_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "ActActividadIdGenerator")

	@Column(name = "act_id", unique = true, nullable = false)
	public Integer getActId() {
		return this.actId;
	}

	public void setActId(Integer actId) {
		this.actId = actId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "int_id", nullable = false)
	public IntInstanciaTarea getIntInstanciaTarea() {
		return this.intInstanciaTarea;
	}

	public void setIntInstanciaTarea(IntInstanciaTarea intInstanciaTarea) {
		this.intInstanciaTarea = intInstanciaTarea;
	}

	@Column(name = "act_codigo", nullable = false, length = 50)
	public String getActCodigo() {
		return this.actCodigo;
	}

	public void setActCodigo(String actCodigo) {
		this.actCodigo = actCodigo;
	}

	@Column(name = "act_valor_actividad")
	public String getActValorActividad() {
		return this.actValorActividad;
	}

	public void setActValorActividad(String actValorActividad) {
		this.actValorActividad = actValorActividad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "act_fecha_actividad", length = 29)
	public Date getActFechaActividad() {
		return this.actFechaActividad;
	}

	public void setActFechaActividad(Date actFechaActividad) {
		this.actFechaActividad = actFechaActividad;
	}

	@Column(name = "act_actividad_completa")
	public Boolean getActActividadCompleta() {
		return this.actActividadCompleta;
	}

	public void setActActividadCompleta(Boolean actActividadCompleta) {
		this.actActividadCompleta = actActividadCompleta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actActividad")
	public Set<DacDetalleActividad> getDacDetalleActividads() {
		return this.dacDetalleActividads;
	}

	public void setDacDetalleActividads(Set<DacDetalleActividad> dacDetalleActividads) {
		this.dacDetalleActividads = dacDetalleActividads;
	}

}
