package cl.servel.gasto.entity;
// Generated 18-10-2018 17:36:13 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import cl.servel.gasto.entity.DetDetalleNomina;
import cl.servel.gasto.entity.IngIngresos;

/**
 * AdmAdministradorElectoral generated by hbm2java
 */
@Entity
@Table(name = "adm_administrador_electoral")
public class AdmAdministradorElectoral implements java.io.Serializable {

	private Integer admId;
	private EveEventoEleccionario eveEventoEleccionario;
	private ParPartido parPartido;
	private TpoAdministrador tpoAdministrador;
	private String admNombre;
	private String admAppPaterno;
	private String admAppMaterno;
	private String admRut;
	private Character admRutDv;
	private String admMail;
	private String admTelefonoFijo;
	private String admTelefonoCelu;
	private String admCtaBanco;
	private String admEstado;
	private String admCodigoOrigen;
	private Date admCreated;
	private Date admModified;
	private Boolean admEliminado;
	private String admDireccion;
	private String admComuna;
	private Set<RlcAdminCandidato> rlcAdminCandidatos = new HashSet<RlcAdminCandidato>(0);
	private Set<HisHistorico> hisHistoricos = new HashSet<HisHistorico>(0);
	private Set<DetDetalleNomina> detDetalleNominas = new HashSet<DetDetalleNomina>(0);
	private Set<IngIngresos> ingIngresoses = new HashSet<IngIngresos>(0);

	public AdmAdministradorElectoral() {
	}

	public AdmAdministradorElectoral(EveEventoEleccionario eveEventoEleccionario, TpoAdministrador tpoAdministrador) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoAdministrador = tpoAdministrador;
	}

	public AdmAdministradorElectoral(EveEventoEleccionario eveEventoEleccionario, ParPartido parPartido,
			TpoAdministrador tpoAdministrador, String admNombre, String admAppPaterno, String admAppMaterno,
			String admRut, Character admRutDv, String admMail, String admTelefonoFijo, String admTelefonoCelu,
			String admCtaBanco, String admEstado, String admCodigoOrigen, Date admCreated, Date admModified,
			Boolean admEliminado, String admDireccion, String admComuna, Set<RlcAdminCandidato> rlcAdminCandidatos,
			Set<HisHistorico> hisHistoricos, Set<DetDetalleNomina> detDetalleNominas, Set<IngIngresos> ingIngresoses) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.parPartido = parPartido;
		this.tpoAdministrador = tpoAdministrador;
		this.admNombre = admNombre;
		this.admAppPaterno = admAppPaterno;
		this.admAppMaterno = admAppMaterno;
		this.admRut = admRut;
		this.admRutDv = admRutDv;
		this.admMail = admMail;
		this.admTelefonoFijo = admTelefonoFijo;
		this.admTelefonoCelu = admTelefonoCelu;
		this.admCtaBanco = admCtaBanco;
		this.admEstado = admEstado;
		this.admCodigoOrigen = admCodigoOrigen;
		this.admCreated = admCreated;
		this.admModified = admModified;
		this.admEliminado = admEliminado;
		this.admDireccion = admDireccion;
		this.admComuna = admComuna;
		this.rlcAdminCandidatos = rlcAdminCandidatos;
		this.hisHistoricos = hisHistoricos;
		this.detDetalleNominas = detDetalleNominas;
		this.ingIngresoses = ingIngresoses;
	}

	@SequenceGenerator(name = "AdmAdministradorElectoralIdGenerator", sequenceName = "adm_administrador_electoral_adm_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "AdmAdministradorElectoralIdGenerator")

	@Column(name = "adm_id", unique = true, nullable = false)
	public Integer getAdmId() {
		return this.admId;
	}

	public void setAdmId(Integer admId) {
		this.admId = admId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id")
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_adm_id", nullable = false)
	public TpoAdministrador getTpoAdministrador() {
		return this.tpoAdministrador;
	}

	public void setTpoAdministrador(TpoAdministrador tpoAdministrador) {
		this.tpoAdministrador = tpoAdministrador;
	}

	@Column(name = "adm_nombre", length = 50)
	public String getAdmNombre() {
		return this.admNombre;
	}

	public void setAdmNombre(String admNombre) {
		this.admNombre = admNombre;
	}

	@Column(name = "adm_app_paterno", length = 50)
	public String getAdmAppPaterno() {
		return this.admAppPaterno;
	}

	public void setAdmAppPaterno(String admAppPaterno) {
		this.admAppPaterno = admAppPaterno;
	}

	@Column(name = "adm_app_materno", length = 50)
	public String getAdmAppMaterno() {
		return this.admAppMaterno;
	}

	public void setAdmAppMaterno(String admAppMaterno) {
		this.admAppMaterno = admAppMaterno;
	}

	@Column(name = "adm_rut", length = 10)
	public String getAdmRut() {
		return this.admRut;
	}

	public void setAdmRut(String admRut) {
		this.admRut = admRut;
	}

	@Column(name = "adm_rut_dv", length = 1)
	public Character getAdmRutDv() {
		return this.admRutDv;
	}

	public void setAdmRutDv(Character admRutDv) {
		this.admRutDv = admRutDv;
	}

	@Column(name = "adm_mail", length = 50)
	public String getAdmMail() {
		return this.admMail;
	}

	public void setAdmMail(String admMail) {
		this.admMail = admMail;
	}

	@Column(name = "adm_telefono_fijo", length = 10)
	public String getAdmTelefonoFijo() {
		return this.admTelefonoFijo;
	}

	public void setAdmTelefonoFijo(String admTelefonoFijo) {
		this.admTelefonoFijo = admTelefonoFijo;
	}

	@Column(name = "adm_telefono_celu", length = 10)
	public String getAdmTelefonoCelu() {
		return this.admTelefonoCelu;
	}

	public void setAdmTelefonoCelu(String admTelefonoCelu) {
		this.admTelefonoCelu = admTelefonoCelu;
	}

	@Column(name = "adm_cta_banco", length = 10)
	public String getAdmCtaBanco() {
		return this.admCtaBanco;
	}

	public void setAdmCtaBanco(String admCtaBanco) {
		this.admCtaBanco = admCtaBanco;
	}

	@Column(name = "adm_estado", length = 5)
	public String getAdmEstado() {
		return this.admEstado;
	}

	public void setAdmEstado(String admEstado) {
		this.admEstado = admEstado;
	}

	@Column(name = "adm_codigo_origen", length = 10)
	public String getAdmCodigoOrigen() {
		return this.admCodigoOrigen;
	}

	public void setAdmCodigoOrigen(String admCodigoOrigen) {
		this.admCodigoOrigen = admCodigoOrigen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adm_created", length = 13)
	public Date getAdmCreated() {
		return this.admCreated;
	}

	public void setAdmCreated(Date admCreated) {
		this.admCreated = admCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "adm_modified", length = 13)
	public Date getAdmModified() {
		return this.admModified;
	}

	public void setAdmModified(Date admModified) {
		this.admModified = admModified;
	}

	@Column(name = "adm_eliminado")
	public Boolean getAdmEliminado() {
		return this.admEliminado;
	}

	public void setAdmEliminado(Boolean admEliminado) {
		this.admEliminado = admEliminado;
	}

	@Column(name = "adm_direccion", length = 50)
	public String getAdmDireccion() {
		return this.admDireccion;
	}

	public void setAdmDireccion(String admDireccion) {
		this.admDireccion = admDireccion;
	}

	@Column(name = "adm_comuna", length = 30)
	public String getAdmComuna() {
		return this.admComuna;
	}

	public void setAdmComuna(String admComuna) {
		this.admComuna = admComuna;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admAdministradorElectoral")
	public Set<RlcAdminCandidato> getRlcAdminCandidatos() {
		return this.rlcAdminCandidatos;
	}

	public void setRlcAdminCandidatos(Set<RlcAdminCandidato> rlcAdminCandidatos) {
		this.rlcAdminCandidatos = rlcAdminCandidatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admAdministradorElectoral")
	public Set<HisHistorico> getHisHistoricos() {
		return this.hisHistoricos;
	}

	public void setHisHistoricos(Set<HisHistorico> hisHistoricos) {
		this.hisHistoricos = hisHistoricos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admAdministradorElectoral")
	public Set<DetDetalleNomina> getDetDetalleNominas() {
		return this.detDetalleNominas;
	}

	public void setDetDetalleNominas(Set<DetDetalleNomina> detDetalleNominas) {
		this.detDetalleNominas = detDetalleNominas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admAdministradorElectoral")
	public Set<IngIngresos> getIngIngresoses() {
		return this.ingIngresoses;
	}

	public void setIngIngresoses(Set<IngIngresos> ingIngresoses) {
		this.ingIngresoses = ingIngresoses;
	}

}
