package cl.servel.gasto.entity;
// Generated 12-06-2019 11:13:58 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * AsgAsignacionCargaTarea generated by hbm2java
 */
@Entity
@Table(name = "asg_asignacion_carga_tarea")
public class AsgAsignacionCargaTarea implements java.io.Serializable {

	private Integer asgId;
	private DtaDefinicionTarea dtaDefinicionTarea;
	private GutGrupoUsuarioTarea gutGrupoUsuarioTarea;
	private TpoEleccion tpoEleccion;
	private Long asgCantidadLineas;
	private Long asgIdAsignacionDeGrupo;
	private Boolean asgAltaComplejidad;

	public AsgAsignacionCargaTarea() {
	}

	public AsgAsignacionCargaTarea(DtaDefinicionTarea dtaDefinicionTarea, GutGrupoUsuarioTarea gutGrupoUsuarioTarea, TpoEleccion tpoEleccion) {
		this.dtaDefinicionTarea = dtaDefinicionTarea;
		this.gutGrupoUsuarioTarea = gutGrupoUsuarioTarea;
		this.tpoEleccion = tpoEleccion;
	}

	public AsgAsignacionCargaTarea(DtaDefinicionTarea dtaDefinicionTarea, GutGrupoUsuarioTarea gutGrupoUsuarioTarea, TpoEleccion tpoEleccion, Long asgCantidadLineas, Long asgIdAsignacionDeGrupo, Boolean asgAltaComplejidad) {
		this.dtaDefinicionTarea = dtaDefinicionTarea;
		this.gutGrupoUsuarioTarea = gutGrupoUsuarioTarea;
		this.tpoEleccion = tpoEleccion;
		this.asgCantidadLineas = asgCantidadLineas;
		this.asgIdAsignacionDeGrupo = asgIdAsignacionDeGrupo;
		this.asgAltaComplejidad = asgAltaComplejidad;
	}

	@SequenceGenerator(name = "AsgAsignacionCargaTareaIdGenerator", sequenceName = "asg_asignacion_carga_tarea_asg_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "AsgAsignacionCargaTareaIdGenerator")

	@Column(name = "asg_id", unique = true, nullable = false)
	public Integer getAsgId() {
		return this.asgId;
	}

	public void setAsgId(Integer asgId) {
		this.asgId = asgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dta_id", nullable = false)
	public DtaDefinicionTarea getDtaDefinicionTarea() {
		return this.dtaDefinicionTarea;
	}

	public void setDtaDefinicionTarea(DtaDefinicionTarea dtaDefinicionTarea) {
		this.dtaDefinicionTarea = dtaDefinicionTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gut_id", nullable = false)
	public GutGrupoUsuarioTarea getGutGrupoUsuarioTarea() {
		return this.gutGrupoUsuarioTarea;
	}

	public void setGutGrupoUsuarioTarea(GutGrupoUsuarioTarea gutGrupoUsuarioTarea) {
		this.gutGrupoUsuarioTarea = gutGrupoUsuarioTarea;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_eleccion_id", nullable = false)
	public TpoEleccion getTpoEleccion() {
		return this.tpoEleccion;
	}

	public void setTpoEleccion(TpoEleccion tpoEleccion) {
		this.tpoEleccion = tpoEleccion;
	}

	@Column(name = "asg_cantidad_lineas")
	public Long getAsgCantidadLineas() {
		return this.asgCantidadLineas;
	}

	public void setAsgCantidadLineas(Long asgCantidadLineas) {
		this.asgCantidadLineas = asgCantidadLineas;
	}

	@Column(name = "asg_id_asignacion_de_grupo")
	public Long getAsgIdAsignacionDeGrupo() {
		return this.asgIdAsignacionDeGrupo;
	}

	public void setAsgIdAsignacionDeGrupo(Long asgIdAsignacionDeGrupo) {
		this.asgIdAsignacionDeGrupo = asgIdAsignacionDeGrupo;
	}

	@Column(name = "asg_alta_complejidad")
	public Boolean getAsgAltaComplejidad() {
		return this.asgAltaComplejidad;
	}

	public void setAsgAltaComplejidad(Boolean asgAltaComplejidad) {
		this.asgAltaComplejidad = asgAltaComplejidad;
	}

}
