package cl.servel.gasto.entity;
// Generated 17-10-2018 19:38:14 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CctCuentaContable generated by hbm2java
 */
@Entity
@Table(name = "cct_cuenta_contable")
public class CctCuentaContable implements java.io.Serializable {

	private Integer cctId;
	private CanCandidato canCandidato;
	private EbaEntidadBancaria ebaEntidadBancaria;
	private ParPartido parPartido;
	private TpoCtaBancaria tpoCtaBancaria;
	private TpoCtaContable tpoCtaContable;
	private String cctNumeroCuenta;
	private Boolean cctEliminado;
	private Date cctCreated;
	private Date cctModified;

	public CctCuentaContable() {
	}

	public CctCuentaContable(CanCandidato canCandidato, EbaEntidadBancaria ebaEntidadBancaria, ParPartido parPartido,
			TpoCtaBancaria tpoCtaBancaria, TpoCtaContable tpoCtaContable) {
		this.canCandidato = canCandidato;
		this.ebaEntidadBancaria = ebaEntidadBancaria;
		this.parPartido = parPartido;
		this.tpoCtaBancaria = tpoCtaBancaria;
		this.tpoCtaContable = tpoCtaContable;
	}

	public CctCuentaContable(CanCandidato canCandidato, EbaEntidadBancaria ebaEntidadBancaria, ParPartido parPartido,
			TpoCtaBancaria tpoCtaBancaria, TpoCtaContable tpoCtaContable, String cctNumeroCuenta, Boolean cctEliminado,
			Date cctCreated, Date cctModified) {
		this.canCandidato = canCandidato;
		this.ebaEntidadBancaria = ebaEntidadBancaria;
		this.parPartido = parPartido;
		this.tpoCtaBancaria = tpoCtaBancaria;
		this.tpoCtaContable = tpoCtaContable;
		this.cctNumeroCuenta = cctNumeroCuenta;
		this.cctEliminado = cctEliminado;
		this.cctCreated = cctCreated;
		this.cctModified = cctModified;
	}

	@SequenceGenerator(name = "cl.servel.gasto.entity.CctCuentaContableIdGenerator", sequenceName = "cct_cuenta_contable_cct_id_seq", initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.entity.CctCuentaContableIdGenerator")

	@Column(name = "cct_id", unique = true, nullable = false)
	public Integer getCctId() {
		return this.cctId;
	}

	public void setCctId(Integer cctId) {
		this.cctId = cctId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "can_id", nullable = false)
	public CanCandidato getCanCandidato() {
		return this.canCandidato;
	}

	public void setCanCandidato(CanCandidato canCandidato) {
		this.canCandidato = canCandidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eba_id", nullable = false)
	public EbaEntidadBancaria getEbaEntidadBancaria() {
		return this.ebaEntidadBancaria;
	}

	public void setEbaEntidadBancaria(EbaEntidadBancaria ebaEntidadBancaria) {
		this.ebaEntidadBancaria = ebaEntidadBancaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id", nullable = false)
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_cta_bancaria_id", nullable = false)
	public TpoCtaBancaria getTpoCtaBancaria() {
		return this.tpoCtaBancaria;
	}

	public void setTpoCtaBancaria(TpoCtaBancaria tpoCtaBancaria) {
		this.tpoCtaBancaria = tpoCtaBancaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_cta_contable_id", nullable = false)
	public TpoCtaContable getTpoCtaContable() {
		return this.tpoCtaContable;
	}

	public void setTpoCtaContable(TpoCtaContable tpoCtaContable) {
		this.tpoCtaContable = tpoCtaContable;
	}

	@Column(name = "cct_numero_cuenta", length = 30)
	public String getCctNumeroCuenta() {
		return this.cctNumeroCuenta;
	}

	public void setCctNumeroCuenta(String cctNumeroCuenta) {
		this.cctNumeroCuenta = cctNumeroCuenta;
	}

	@Column(name = "cct_eliminado")
	public Boolean getCctEliminado() {
		return this.cctEliminado;
	}

	public void setCctEliminado(Boolean cctEliminado) {
		this.cctEliminado = cctEliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cct_created", length = 13)
	public Date getCctCreated() {
		return this.cctCreated;
	}

	public void setCctCreated(Date cctCreated) {
		this.cctCreated = cctCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "cct_modified", length = 13)
	public Date getCctModified() {
		return this.cctModified;
	}

	public void setCctModified(Date cctModified) {
		this.cctModified = cctModified;
	}

}
