package cl.servel.gasto.entity;
// Generated 12-06-2019 11:26:14 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DeaDefinicionActividad generated by hbm2java
 */
@Entity
@Table(name = "dea_definicion_actividad")
public class DeaDefinicionActividad implements java.io.Serializable {

	private Integer deaId;
	private DtaDefinicionTarea dtaDefinicionTarea;
	private String deaCodigo;
	private String deaValor;
	private String deaDescripcion;
	private String deaCodigoActividad;
	private Set<DacDetalleActividad> dacDetalleActividads = new HashSet<DacDetalleActividad>(0);

	public DeaDefinicionActividad() {
	}

	public DeaDefinicionActividad(DtaDefinicionTarea dtaDefinicionTarea, String deaCodigo) {
		this.dtaDefinicionTarea = dtaDefinicionTarea;
		this.deaCodigo = deaCodigo;
	}

	public DeaDefinicionActividad(DtaDefinicionTarea dtaDefinicionTarea, String deaCodigo, String deaValor, String deaDescripcion, String deaCodigoActividad, Set<DacDetalleActividad> dacDetalleActividads) {
		this.dtaDefinicionTarea = dtaDefinicionTarea;
		this.deaCodigo = deaCodigo;
		this.deaValor = deaValor;
		this.deaDescripcion = deaDescripcion;
		this.deaCodigoActividad = deaCodigoActividad;
		this.dacDetalleActividads = dacDetalleActividads;
	}

	@SequenceGenerator(name = "DeaDefinicionActividadIdGenerator", sequenceName = "dea_definicion_actividad_dea_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "DeaDefinicionActividadIdGenerator")

	@Column(name = "dea_id", unique = true, nullable = false)
	public Integer getDeaId() {
		return this.deaId;
	}

	public void setDeaId(Integer deaId) {
		this.deaId = deaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dta_id", nullable = false)
	public DtaDefinicionTarea getDtaDefinicionTarea() {
		return this.dtaDefinicionTarea;
	}

	public void setDtaDefinicionTarea(DtaDefinicionTarea dtaDefinicionTarea) {
		this.dtaDefinicionTarea = dtaDefinicionTarea;
	}

	@Column(name = "dea_codigo", nullable = false, length = 50)
	public String getDeaCodigo() {
		return this.deaCodigo;
	}

	public void setDeaCodigo(String deaCodigo) {
		this.deaCodigo = deaCodigo;
	}

	@Column(name = "dea_valor", length = 100)
	public String getDeaValor() {
		return this.deaValor;
	}

	public void setDeaValor(String deaValor) {
		this.deaValor = deaValor;
	}

	@Column(name = "dea_descripcion")
	public String getDeaDescripcion() {
		return this.deaDescripcion;
	}

	public void setDeaDescripcion(String deaDescripcion) {
		this.deaDescripcion = deaDescripcion;
	}

	@Column(name = "dea_codigo_actividad", length = 50)
	public String getDeaCodigoActividad() {
		return this.deaCodigoActividad;
	}

	public void setDeaCodigoActividad(String deaCodigoActividad) {
		this.deaCodigoActividad = deaCodigoActividad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deaDefinicionActividad")
	public Set<DacDetalleActividad> getDacDetalleActividads() {
		return this.dacDetalleActividads;
	}

	public void setDacDetalleActividads(Set<DacDetalleActividad> dacDetalleActividads) {
		this.dacDetalleActividads = dacDetalleActividads;
	}

}
