package cl.servel.gasto.entity;
// Generated 10-07-2019 17:11:40 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DexDocumentoExterno generated by hbm2java
 */
@Entity
@Table(name = "dex_documento_externo")
public class DexDocumentoExterno implements java.io.Serializable {

	private Integer dexId;
	private Date dexCreated;
	private Set<DdeDetalleDocumentosExternos> ddeDetalleDocumentosExternoses = new HashSet<DdeDetalleDocumentosExternos>(
			0);
	private Set<ExExpediente> exExpedientes = new HashSet<ExExpediente>(0);
	private Set<ManMandato> manMandatos = new HashSet<ManMandato>(0);
	private Set<ObrObservacionRendicion> obrObservacionRendicions = new HashSet<ObrObservacionRendicion>(0);
	private Set<UsuUsuarios> usuUsuarioses = new HashSet<UsuUsuarios>(0);

	public DexDocumentoExterno() {
	}

	public DexDocumentoExterno(Date dexCreated, Set<DdeDetalleDocumentosExternos> ddeDetalleDocumentosExternoses,
			Set<ExExpediente> exExpedientes, Set<ManMandato> manMandatos,
			Set<ObrObservacionRendicion> obrObservacionRendicions, Set<UsuUsuarios> usuUsuarioses) {
		this.dexCreated = dexCreated;
		this.ddeDetalleDocumentosExternoses = ddeDetalleDocumentosExternoses;
		this.exExpedientes = exExpedientes;
		this.manMandatos = manMandatos;
		this.obrObservacionRendicions = obrObservacionRendicions;
		this.usuUsuarioses = usuUsuarioses;
	}

	@SequenceGenerator(name = "cl.servel.gasto.temporal.DexDocumentoExternoIdGenerator", sequenceName = "dex_documento_externo_dex_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.temporal.DexDocumentoExternoIdGenerator")

	@Column(name = "dex_id", unique = true, nullable = false)
	public Integer getDexId() {
		return this.dexId;
	}

	public void setDexId(Integer dexId) {
		this.dexId = dexId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dex_created", length = 29)
	public Date getDexCreated() {
		return this.dexCreated;
	}

	public void setDexCreated(Date dexCreated) {
		this.dexCreated = dexCreated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dexDocumentoExterno")
	public Set<DdeDetalleDocumentosExternos> getDdeDetalleDocumentosExternoses() {
		return this.ddeDetalleDocumentosExternoses;
	}

	public void setDdeDetalleDocumentosExternoses(Set<DdeDetalleDocumentosExternos> ddeDetalleDocumentosExternoses) {
		this.ddeDetalleDocumentosExternoses = ddeDetalleDocumentosExternoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dexDocumentoExterno")
	public Set<ExExpediente> getExExpedientes() {
		return this.exExpedientes;
	}

	public void setExExpedientes(Set<ExExpediente> exExpedientes) {
		this.exExpedientes = exExpedientes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dexDocumentoExterno")
	public Set<ManMandato> getManMandatos() {
		return this.manMandatos;
	}

	public void setManMandatos(Set<ManMandato> manMandatos) {
		this.manMandatos = manMandatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dexDocumentoExterno")
	public Set<ObrObservacionRendicion> getObrObservacionRendicions() {
		return this.obrObservacionRendicions;
	}

	public void setObrObservacionRendicions(Set<ObrObservacionRendicion> obrObservacionRendicions) {
		this.obrObservacionRendicions = obrObservacionRendicions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dexDocumentoExterno")
	public Set<UsuUsuarios> getUsuUsuarioses() {
		return this.usuUsuarioses;
	}

	public void setUsuUsuarioses(Set<UsuUsuarios> usuUsuarioses) {
		this.usuUsuarioses = usuUsuarioses;
	}

}
