package cl.servel.gasto.entity;
// Generated 14-08-2019 18:11:24 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * DinDetalleIngresos generated by hbm2java
 */
@Entity
@Table(name = "din_detalle_ingresos")
public class DinDetalleIngresos implements java.io.Serializable {

	private Integer dinId;
	private IngIngresos ingIngresos;
	private String dinNombreAtributo;
	private String dinValorAtributo;

	public DinDetalleIngresos() {
	}

	public DinDetalleIngresos(IngIngresos ingIngresos, String dinNombreAtributo) {
		this.ingIngresos = ingIngresos;
		this.dinNombreAtributo = dinNombreAtributo;
	}

	public DinDetalleIngresos(IngIngresos ingIngresos, String dinNombreAtributo, String dinValorAtributo) {
		this.ingIngresos = ingIngresos;
		this.dinNombreAtributo = dinNombreAtributo;
		this.dinValorAtributo = dinValorAtributo;
	}

	@SequenceGenerator(name = "DinDetalleIngresosIdGenerator", sequenceName = "din_detalle_ingresos_din_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "DinDetalleIngresosIdGenerator")

	@Column(name = "din_id", unique = true, nullable = false)
	public Integer getDinId() {
		return this.dinId;
	}

	public void setDinId(Integer dinId) {
		this.dinId = dinId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ing_id", nullable = false)
	public IngIngresos getIngIngresos() {
		return this.ingIngresos;
	}

	public void setIngIngresos(IngIngresos ingIngresos) {
		this.ingIngresos = ingIngresos;
	}

	@Column(name = "din_nombre_atributo", nullable = false, length = 50)
	public String getDinNombreAtributo() {
		return this.dinNombreAtributo;
	}

	public void setDinNombreAtributo(String dinNombreAtributo) {
		this.dinNombreAtributo = dinNombreAtributo;
	}

	@Column(name = "din_valor_atributo", length = 200)
	public String getDinValorAtributo() {
		return this.dinValorAtributo;
	}

	public void setDinValorAtributo(String dinValorAtributo) {
		this.dinValorAtributo = dinValorAtributo;
	}

}
