package cl.servel.gasto.entity;
// Generated 26-08-2019 10:28:58 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * EbaEntidadBancaria generated by hbm2java
 */
@Entity
@Table(name = "eba_entidad_bancaria")
public class EbaEntidadBancaria implements java.io.Serializable {

	private Integer ebaId;
	private String ebaNombreBanco;
	private String ebaCodSbif;
	private String ebaRut;
	private String ebaNroCuenta;
	private String ebaDireccion;
	private String ebaComuna;
	private String ebaTelefono;
	private String ebaEmail;
	private Set<ManMandato> manMandatos = new HashSet<ManMandato>(0);
	private Set<CctCuentaContable> cctCuentaContables = new HashSet<CctCuentaContable>(0);
	private Set<DetDetalleNomina> detDetalleNominas = new HashSet<DetDetalleNomina>(0);

	public EbaEntidadBancaria() {
	}

	public EbaEntidadBancaria(String ebaCodSbif) {
		this.ebaCodSbif = ebaCodSbif;
	}

	public EbaEntidadBancaria(String ebaNombreBanco, String ebaCodSbif, String ebaRut, String ebaNroCuenta, String ebaDireccion, String ebaComuna, String ebaTelefono, String ebaEmail, Set<ManMandato> manMandatos, Set<CctCuentaContable> cctCuentaContables, Set<DetDetalleNomina> detDetalleNominas) {
		this.ebaNombreBanco = ebaNombreBanco;
		this.ebaCodSbif = ebaCodSbif;
		this.ebaRut = ebaRut;
		this.ebaNroCuenta = ebaNroCuenta;
		this.ebaDireccion = ebaDireccion;
		this.ebaComuna = ebaComuna;
		this.ebaTelefono = ebaTelefono;
		this.ebaEmail = ebaEmail;
		this.manMandatos = manMandatos;
		this.cctCuentaContables = cctCuentaContables;
		this.detDetalleNominas = detDetalleNominas;
	}

	@SequenceGenerator(name = "cl.servel.gasto.temporal.EbaEntidadBancariaIdGenerator", sequenceName = "eba_entidad_bancaria_eba_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.temporal.EbaEntidadBancariaIdGenerator")

	@Column(name = "eba_id", unique = true, nullable = false)
	public Integer getEbaId() {
		return this.ebaId;
	}

	public void setEbaId(Integer ebaId) {
		this.ebaId = ebaId;
	}

	@Column(name = "eba_nombre_banco", length = 50)
	public String getEbaNombreBanco() {
		return this.ebaNombreBanco;
	}

	public void setEbaNombreBanco(String ebaNombreBanco) {
		this.ebaNombreBanco = ebaNombreBanco;
	}

	@Column(name = "eba_cod_sbif", nullable = false, length = 15)
	public String getEbaCodSbif() {
		return this.ebaCodSbif;
	}

	public void setEbaCodSbif(String ebaCodSbif) {
		this.ebaCodSbif = ebaCodSbif;
	}

	@Column(name = "eba_rut", length = 15)
	public String getEbaRut() {
		return this.ebaRut;
	}

	public void setEbaRut(String ebaRut) {
		this.ebaRut = ebaRut;
	}

	@Column(name = "eba_nro_cuenta", length = 50)
	public String getEbaNroCuenta() {
		return this.ebaNroCuenta;
	}

	public void setEbaNroCuenta(String ebaNroCuenta) {
		this.ebaNroCuenta = ebaNroCuenta;
	}

	@Column(name = "eba_direccion", length = 50)
	public String getEbaDireccion() {
		return this.ebaDireccion;
	}

	public void setEbaDireccion(String ebaDireccion) {
		this.ebaDireccion = ebaDireccion;
	}

	@Column(name = "eba_comuna", length = 50)
	public String getEbaComuna() {
		return this.ebaComuna;
	}

	public void setEbaComuna(String ebaComuna) {
		this.ebaComuna = ebaComuna;
	}

	@Column(name = "eba_telefono", length = 20)
	public String getEbaTelefono() {
		return this.ebaTelefono;
	}

	public void setEbaTelefono(String ebaTelefono) {
		this.ebaTelefono = ebaTelefono;
	}

	@Column(name = "eba_email", length = 50)
	public String getEbaEmail() {
		return this.ebaEmail;
	}

	public void setEbaEmail(String ebaEmail) {
		this.ebaEmail = ebaEmail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ebaEntidadBancaria")
	public Set<ManMandato> getManMandatos() {
		return this.manMandatos;
	}

	public void setManMandatos(Set<ManMandato> manMandatos) {
		this.manMandatos = manMandatos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ebaEntidadBancaria")
	public Set<CctCuentaContable> getCctCuentaContables() {
		return this.cctCuentaContables;
	}

	public void setCctCuentaContables(Set<CctCuentaContable> cctCuentaContables) {
		this.cctCuentaContables = cctCuentaContables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ebaEntidadBancaria")
	public Set<DetDetalleNomina> getDetDetalleNominas() {
		return this.detDetalleNominas;
	}

	public void setDetDetalleNominas(Set<DetDetalleNomina> detDetalleNominas) {
		this.detDetalleNominas = detDetalleNominas;
	}
}
