package cl.servel.gasto.entity;
// Generated 21-03-2019 14:36:24 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * GutGrupoUsuarioTarea generated by hbm2java
 */
@Entity
@Table(name = "gut_grupo_usuario_tarea")
public class GutGrupoUsuarioTarea implements java.io.Serializable {

	private Integer gutId;
	private CelCelula celCelula;
	private String gutAgrupacion;
	private Set<UstUsuarioTarea> ustUsuarioTareas = new HashSet<UstUsuarioTarea>(0);
	private Set<AsgAsignacionCargaTarea> asgAsignacionCargaTareas = new HashSet<AsgAsignacionCargaTarea>(0);

	public GutGrupoUsuarioTarea() {
	}

	public GutGrupoUsuarioTarea(CelCelula celCelula, String gutAgrupacion, Set<UstUsuarioTarea> ustUsuarioTareas, Set<AsgAsignacionCargaTarea> asgAsignacionCargaTareas) {
		this.celCelula = celCelula;
		this.gutAgrupacion = gutAgrupacion;
		this.ustUsuarioTareas = ustUsuarioTareas;
		this.asgAsignacionCargaTareas = asgAsignacionCargaTareas;
	}

	@SequenceGenerator(name = "GutGrupoUsuarioTareaIdGenerator", sequenceName = "gut_grupo_usuario_tarea_gut_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "GutGrupoUsuarioTareaIdGenerator")

	@Column(name = "gut_id", unique = true, nullable = false)
	public Integer getGutId() {
		return this.gutId;
	}

	public void setGutId(Integer gutId) {
		this.gutId = gutId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cel_id")
	public CelCelula getCelCelula() {
		return this.celCelula;
	}

	public void setCelCelula(CelCelula celCelula) {
		this.celCelula = celCelula;
	}

	@Column(name = "gut_agrupacion", length = 50)
	public String getGutAgrupacion() {
		return this.gutAgrupacion;
	}

	public void setGutAgrupacion(String gutAgrupacion) {
		this.gutAgrupacion = gutAgrupacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gutGrupoUsuarioTarea")
	public Set<UstUsuarioTarea> getUstUsuarioTareas() {
		return this.ustUsuarioTareas;
	}

	public void setUstUsuarioTareas(Set<UstUsuarioTarea> ustUsuarioTareas) {
		this.ustUsuarioTareas = ustUsuarioTareas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gutGrupoUsuarioTarea")
	public Set<AsgAsignacionCargaTarea> getAsgAsignacionCargaTareas() {
		return this.asgAsignacionCargaTareas;
	}

	public void setAsgAsignacionCargaTareas(Set<AsgAsignacionCargaTarea> asgAsignacionCargaTareas) {
		this.asgAsignacionCargaTareas = asgAsignacionCargaTareas;
	}

}
