package cl.servel.gasto.entity;
// Generated 22-08-2019 11:22:53 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IngIngresos generated by hbm2java
 */
@Entity
@Table(name = "ing_ingresos")
public class IngIngresos implements java.io.Serializable {

	private Integer ingId;
	private AdmAdministradorElectoral admAdministradorElectoral;
	private CanCandidato canCandidato;
	private DetDetalleNomina detDetalleNomina;
	private EveEventoEleccionario eveEventoEleccionario;
	private ParPartido parPartido;
	private TpoTipos tpoTipos;
	private UsuUsuarios usuUsuarios;
	private Integer ingRut;
	private String ingRutDv;
	private Date ingFechaIngreso;
	private Date ingCreated;
	private String estado;
	private Set<DinDetalleIngresos> dinDetalleIngresoses = new HashSet<DinDetalleIngresos>(0);

	public IngIngresos() {
	}

	public IngIngresos(EveEventoEleccionario eveEventoEleccionario, TpoTipos tpoTipos, UsuUsuarios usuUsuarios) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoTipos = tpoTipos;
		this.usuUsuarios = usuUsuarios;
	}

	public IngIngresos(AdmAdministradorElectoral admAdministradorElectoral, CanCandidato canCandidato, DetDetalleNomina detDetalleNomina, EveEventoEleccionario eveEventoEleccionario, ParPartido parPartido, TpoTipos tpoTipos, UsuUsuarios usuUsuarios, Integer ingRut, String ingRutDv, Date ingFechaIngreso, Date ingCreated, String estado, Set<DinDetalleIngresos> dinDetalleIngresoses) {
		this.admAdministradorElectoral = admAdministradorElectoral;
		this.canCandidato = canCandidato;
		this.detDetalleNomina = detDetalleNomina;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.parPartido = parPartido;
		this.tpoTipos = tpoTipos;
		this.usuUsuarios = usuUsuarios;
		this.ingRut = ingRut;
		this.ingRutDv = ingRutDv;
		this.ingFechaIngreso = ingFechaIngreso;
		this.ingCreated = ingCreated;
		this.estado = estado;
		this.dinDetalleIngresoses = dinDetalleIngresoses;
	}

	@SequenceGenerator(name = "IngIngresosIdGenerator", sequenceName = "ing_ingresos_ing_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "IngIngresosIdGenerator")

	@Column(name = "ing_id", unique = true, nullable = false)
	public Integer getIngId() {
		return this.ingId;
	}

	public void setIngId(Integer ingId) {
		this.ingId = ingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "adm_id")
	public AdmAdministradorElectoral getAdmAdministradorElectoral() {
		return this.admAdministradorElectoral;
	}

	public void setAdmAdministradorElectoral(AdmAdministradorElectoral admAdministradorElectoral) {
		this.admAdministradorElectoral = admAdministradorElectoral;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "can_id")
	public CanCandidato getCanCandidato() {
		return this.canCandidato;
	}

	public void setCanCandidato(CanCandidato canCandidato) {
		this.canCandidato = canCandidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "det_id")
	public DetDetalleNomina getDetDetalleNomina() {
		return this.detDetalleNomina;
	}

	public void setDetDetalleNomina(DetDetalleNomina detDetalleNomina) {
		this.detDetalleNomina = detDetalleNomina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id")
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_ingreso_id", nullable = false)
	public TpoTipos getTpoTipos() {
		return this.tpoTipos;
	}

	public void setTpoTipos(TpoTipos tpoTipos) {
		this.tpoTipos = tpoTipos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usu_id", nullable = false)
	public UsuUsuarios getUsuUsuarios() {
		return this.usuUsuarios;
	}

	public void setUsuUsuarios(UsuUsuarios usuUsuarios) {
		this.usuUsuarios = usuUsuarios;
	}

	@Column(name = "ing_rut")
	public Integer getIngRut() {
		return this.ingRut;
	}

	public void setIngRut(Integer ingRut) {
		this.ingRut = ingRut;
	}

	@Column(name = "ing_rut_dv", length = 1)
	public String getIngRutDv() {
		return this.ingRutDv;
	}

	public void setIngRutDv(String ingRutDv) {
		this.ingRutDv = ingRutDv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ing_fecha_ingreso", length = 29)
	public Date getIngFechaIngreso() {
		return this.ingFechaIngreso;
	}

	public void setIngFechaIngreso(Date ingFechaIngreso) {
		this.ingFechaIngreso = ingFechaIngreso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ing_created", length = 29)
	public Date getIngCreated() {
		return this.ingCreated;
	}

	public void setIngCreated(Date ingCreated) {
		this.ingCreated = ingCreated;
	}

	@Column(name = "estado", length = 15)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ingIngresos")
	public Set<DinDetalleIngresos> getDinDetalleIngresoses() {
		return this.dinDetalleIngresoses;
	}

	public void setDinDetalleIngresoses(Set<DinDetalleIngresos> dinDetalleIngresoses) {
		this.dinDetalleIngresoses = dinDetalleIngresoses;
	}

}
