package cl.servel.gasto.entity;
// Generated 03-12-2018 11:52:46 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * LimLimiteGasto generated by hbm2java
 */
@Entity
@Table(name = "lim_limite_gasto")
public class LimLimiteGasto implements java.io.Serializable {

	private Integer limId;
	private EleEleccion eleEleccion;
	private EveEventoEleccionario eveEventoEleccionario;
	private NivNivel nivNivelByNivHijoId;
	private NivNivel nivNivelByNivPadreId;
	private ParPartido parPartido;
	private TpoEleccion tpoEleccion;
	private Boolean limEsLimiteGastoPartido;
	private Double limMaxPersona;
	private Double limTotalLimite;
	private Integer numeroElectores;
	private Double limMaxAporteSinPub;
	private Double limMaxAportePerCan;


	public LimLimiteGasto() {
	}

	public LimLimiteGasto(EleEleccion eleEleccion, EveEventoEleccionario eveEventoEleccionario,
			TpoEleccion tpoEleccion) {
		this.eleEleccion = eleEleccion;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoEleccion = tpoEleccion;
	}

	public LimLimiteGasto(EleEleccion eleEleccion, EveEventoEleccionario eveEventoEleccionario,
			NivNivel nivNivelByNivHijoId, NivNivel nivNivelByNivPadreId, ParPartido parPartido, TpoEleccion tpoEleccion,
			Boolean limEsLimiteGastoPartido, Double limMaxPersona, Double limTotalLimite,
			Integer numeroElectores,Double limMaxAporteSinPub, Double limMaxAportePerCan) {
		this.eleEleccion = eleEleccion;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.nivNivelByNivHijoId = nivNivelByNivHijoId;
		this.nivNivelByNivPadreId = nivNivelByNivPadreId;
		this.parPartido = parPartido;
		this.tpoEleccion = tpoEleccion;
		this.limEsLimiteGastoPartido = limEsLimiteGastoPartido;
		this.limMaxPersona = limMaxPersona;
		this.limTotalLimite = limTotalLimite;
		this.numeroElectores = numeroElectores;
		this.limMaxAporteSinPub = limMaxAporteSinPub;
		this.limMaxAportePerCan = limMaxAportePerCan;
	}
	@SequenceGenerator(name = "LimLimiteGastoIdGenerator", sequenceName = "lim_limite_gasto_lim_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "LimLimiteGastoIdGenerator")

	@Column(name = "lim_id", unique = true, nullable = false)
	public Integer getLimId() {
		return this.limId;
	}

	public void setLimId(Integer limId) {
		this.limId = limId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ele_id", nullable = false)
	public EleEleccion getEleEleccion() {
		return this.eleEleccion;
	}

	public void setEleEleccion(EleEleccion eleEleccion) {
		this.eleEleccion = eleEleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "niv_hijo_id")
	public NivNivel getNivNivelByNivHijoId() {
		return this.nivNivelByNivHijoId;
	}

	public void setNivNivelByNivHijoId(NivNivel nivNivelByNivHijoId) {
		this.nivNivelByNivHijoId = nivNivelByNivHijoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "niv_padre_id")
	public NivNivel getNivNivelByNivPadreId() {
		return this.nivNivelByNivPadreId;
	}

	public void setNivNivelByNivPadreId(NivNivel nivNivelByNivPadreId) {
		this.nivNivelByNivPadreId = nivNivelByNivPadreId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id")
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_eleccion_id", nullable = false)
	public TpoEleccion getTpoEleccion() {
		return this.tpoEleccion;
	}

	public void setTpoEleccion(TpoEleccion tpoEleccion) {
		this.tpoEleccion = tpoEleccion;
	}

	@Column(name = "lim_es_limite_gasto_partido")
	public Boolean getLimEsLimiteGastoPartido() {
		return this.limEsLimiteGastoPartido;
	}

	public void setLimEsLimiteGastoPartido(Boolean limEsLimiteGastoPartido) {
		this.limEsLimiteGastoPartido = limEsLimiteGastoPartido;
	}

	@Column(name = "lim_max_persona", precision = 17, scale = 17)
	public Double getLimMaxPersona() {
		return this.limMaxPersona;
	}

	public void setLimMaxPersona(Double limMaxPersona) {
		this.limMaxPersona = limMaxPersona;
	}

	@Column(name = "lim_total_limite", precision = 17, scale = 17)
	public Double getLimTotalLimite() {
		return this.limTotalLimite;
	}

	public void setLimTotalLimite(Double limTotalLimite) {
		this.limTotalLimite = limTotalLimite;
	}
	
	@Column(name = "numero_electores")
	public Integer getNumeroElectores() {
		return this.numeroElectores;
	}

	public void setNumeroElectores(Integer numeroElectores) {
		this.numeroElectores = numeroElectores;
	}

	@Column(name = "lim_max_aporte_sin_pub", precision = 17, scale = 17)
	public Double getLimMaxAporteSinPub() {
		return this.limMaxAporteSinPub;
	}

	public void setLimMaxAporteSinPub(Double limMaxAporteSinPub) {
		this.limMaxAporteSinPub = limMaxAporteSinPub;
	}

	@Column(name = "lim_max_aporte_per_can", precision = 17, scale = 17)
	public Double getLimMaxAportePerCan() {
		return this.limMaxAportePerCan;
	}

	public void setLimMaxAportePerCan(Double limMaxAportePerCan) {
		this.limMaxAportePerCan = limMaxAportePerCan;
	}


}
