package cl.servel.gasto.entity;
// Generated 17-abr-2019 19:21:36 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ManMandato generated by hbm2java
 */
@Entity
@Table(name = "man_mandato")
public class ManMandato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private Integer manId;
	private CanCandidato canCandidato;
	private DexDocumentoExterno dexDocumentoExterno;
	private EbaEntidadBancaria ebaEntidadBancaria;
	private ParPartido parPartido;
	private Date manFechaMandato;
	private Date manCreated;
	private Double manMontoBruto;
	private Double manMontoInteres;
	private Double manMontoMandato;
	private String manCuentaBancaria;
	private Boolean manEliminado;
	private String manGlosaSuperior;
	private String manNumeroDocumento;

	public ManMandato() {
	}

	public ManMandato(EbaEntidadBancaria ebaEntidadBancaria) {
		this.ebaEntidadBancaria = ebaEntidadBancaria;
	}

	public ManMandato(CanCandidato canCandidato, DexDocumentoExterno dexDocumentoExterno,
			EbaEntidadBancaria ebaEntidadBancaria, ParPartido parPartido, Date manFechaMandato, Date manCreated,
			Double manMontoBruto, Double manMontoInteres, Double manMontoMandato, String manCuentaBancaria,
			Boolean manEliminado, String manGlosaSuperior, String manNumeroDocumento) {
		this.canCandidato = canCandidato;
		this.dexDocumentoExterno = dexDocumentoExterno;
		this.ebaEntidadBancaria = ebaEntidadBancaria;
		this.parPartido = parPartido;
		this.manFechaMandato = manFechaMandato;
		this.manCreated = manCreated;
		this.manMontoBruto = manMontoBruto;
		this.manMontoInteres = manMontoInteres;
		this.manMontoMandato = manMontoMandato;
		this.manCuentaBancaria = manCuentaBancaria;
		this.manEliminado = manEliminado;
		this.manGlosaSuperior = manGlosaSuperior;
		this.manNumeroDocumento = manNumeroDocumento;
	}

	@SequenceGenerator(name = "ManMandatoIdGenerator", sequenceName = "man_mandato_man_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "ManMandatoIdGenerator")

	@Column(name = "man_id", unique = true, nullable = false)
	public Integer getManId() {
		return this.manId;
	}

	public void setManId(Integer manId) {
		this.manId = manId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "can_id")
	public CanCandidato getCanCandidato() {
		return this.canCandidato;
	}

	public void setCanCandidato(CanCandidato canCandidato) {
		this.canCandidato = canCandidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dex_id")
	public DexDocumentoExterno getDexDocumentoExterno() {
		return this.dexDocumentoExterno;
	}

	public void setDexDocumentoExterno(DexDocumentoExterno dexDocumentoExterno) {
		this.dexDocumentoExterno = dexDocumentoExterno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eba_id", nullable = false)
	public EbaEntidadBancaria getEbaEntidadBancaria() {
		return this.ebaEntidadBancaria;
	}

	public void setEbaEntidadBancaria(EbaEntidadBancaria ebaEntidadBancaria) {
		this.ebaEntidadBancaria = ebaEntidadBancaria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id")
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "man_fecha_mandato", length = 29)
	public Date getManFechaMandato() {
		return this.manFechaMandato;
	}

	public void setManFechaMandato(Date manFechaMandato) {
		this.manFechaMandato = manFechaMandato;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "man_created", length = 29)
	public Date getManCreated() {
		return this.manCreated;
	}

	public void setManCreated(Date manCreated) {
		this.manCreated = manCreated;
	}

	@Column(name = "man_monto_bruto", precision = 17, scale = 17)
	public Double getManMontoBruto() {
		return this.manMontoBruto;
	}

	public void setManMontoBruto(Double manMontoBruto) {
		this.manMontoBruto = manMontoBruto;
	}

	@Column(name = "man_monto_interes", precision = 17, scale = 17)
	public Double getManMontoInteres() {
		return this.manMontoInteres;
	}

	public void setManMontoInteres(Double manMontoInteres) {
		this.manMontoInteres = manMontoInteres;
	}

	@Column(name = "man_monto_mandato", precision = 17, scale = 17)
	public Double getManMontoMandato() {
		return this.manMontoMandato;
	}

	public void setManMontoMandato(Double manMontoMandato) {
		this.manMontoMandato = manMontoMandato;
	}

	@Column(name = "man_cuenta_bancaria", length = 50)
	public String getManCuentaBancaria() {
		return this.manCuentaBancaria;
	}

	public void setManCuentaBancaria(String manCuentaBancaria) {
		this.manCuentaBancaria = manCuentaBancaria;
	}

	@Column(name = "man_eliminado")
	public Boolean getManEliminado() {
		return this.manEliminado;
	}

	public void setManEliminado(Boolean manEliminado) {
		this.manEliminado = manEliminado;
	}

	@Column(name = "man_glosa_superior", length = 5000)
	public String getManGlosaSuperior() {
		return this.manGlosaSuperior;
	}

	public void setManGlosaSuperior(String manGlosaSuperior) {
		this.manGlosaSuperior = manGlosaSuperior;
	}

	@Column(name = "man_numero_documento", length = 20)
	public String getManNumeroDocumento() {
		return this.manNumeroDocumento;
	}

	public void setManNumeroDocumento(String manNumeroDocumento) {
		this.manNumeroDocumento = manNumeroDocumento;
	}

}
