package cl.servel.gasto.entity;
// Generated 08-11-2018 15:30:13 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * ParPartidoMaestro generated by hbm2java
 */
@Entity
@Table(name = "par_partido_maestro")
public class ParPartidoMaestro implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private int estado;
	private String codigoOrigen;
	

	private Set<RlcPartidoNivel> rlcPartidoNivels = new HashSet<RlcPartidoNivel>(0);

	public ParPartidoMaestro() {
	}

	public ParPartidoMaestro(String nombre, int estado) {
		this.nombre = nombre;
		this.estado = estado;
	}

	public ParPartidoMaestro(String nombre, int estado, Set<RlcPartidoNivel> rlcPartidoNivels) {
		this.nombre = nombre;
		this.estado = estado;
		this.rlcPartidoNivels = rlcPartidoNivels;
	}

	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado", nullable = false)
	public int getEstado() {
		return this.estado;
	}

	public void setEstado(int estado) {
		this.estado = estado;
	}
	
	@Column(name = "codigo_origen")
	public String getCodigoOrigen() {
		return codigoOrigen;
	}

	public void setCodigoOrigen(String codigoOrigen) {
		this.codigoOrigen = codigoOrigen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parPartidoMaestro")
	public Set<RlcPartidoNivel> getRlcPartidoNivels() {
		return this.rlcPartidoNivels;
	}

	public void setRlcPartidoNivels(Set<RlcPartidoNivel> rlcPartidoNivels) {
		this.rlcPartidoNivels = rlcPartidoNivels;
	}

}
