package cl.servel.gasto.entity;
// Generated 24-04-2019 11:30:25 by Hibernate Tools 5.2.12.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PerPerfil generated by hbm2java
 */
@Entity
@Table(name = "per_perfil")
public class PerPerfil implements java.io.Serializable {

	private Integer perId;
	private String perNombrePerfil;
	private Boolean perEliminado;
	private Date created;
	private Date modified;
	private String perCodigoPerfil;
	private Set<RlcPerfilDefinicionTarea> rlcPerfilDefinicionTareas = new HashSet<RlcPerfilDefinicionTarea>(0);
	private Set<RlcUsuarioPerfil> rlcUsuarioPerfils = new HashSet<RlcUsuarioPerfil>(0);
	private Set<RlcPerfilRolUsuario> rlcPerfilRolUsuarios = new HashSet<RlcPerfilRolUsuario>(0);

	public PerPerfil() {
	}

	public PerPerfil(String perNombrePerfil, Boolean perEliminado, Date created, Date modified, String perCodigoPerfil, Set<RlcPerfilDefinicionTarea> rlcPerfilDefinicionTareas, Set<RlcUsuarioPerfil> rlcUsuarioPerfils, Set<RlcPerfilRolUsuario> rlcPerfilRolUsuarios) {
		this.perNombrePerfil = perNombrePerfil;
		this.perEliminado = perEliminado;
		this.created = created;
		this.modified = modified;
		this.perCodigoPerfil = perCodigoPerfil;
		this.rlcPerfilDefinicionTareas = rlcPerfilDefinicionTareas;
		this.rlcUsuarioPerfils = rlcUsuarioPerfils;
		this.rlcPerfilRolUsuarios = rlcPerfilRolUsuarios;
	}

	@SequenceGenerator(name = "PerPerfilIdGenerator", sequenceName = "per_perfil_per_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "PerPerfilIdGenerator")

	@Column(name = "per_id", unique = true, nullable = false)
	public Integer getPerId() {
		return this.perId;
	}

	public void setPerId(Integer perId) {
		this.perId = perId;
	}

	@Column(name = "per_nombre_perfil", length = 20)
	public String getPerNombrePerfil() {
		return this.perNombrePerfil;
	}

	public void setPerNombrePerfil(String perNombrePerfil) {
		this.perNombrePerfil = perNombrePerfil;
	}

	@Column(name = "per_eliminado")
	public Boolean getPerEliminado() {
		return this.perEliminado;
	}

	public void setPerEliminado(Boolean perEliminado) {
		this.perEliminado = perEliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", length = 13)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified", length = 13)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "per_codigo_perfil", length = 50)
	public String getPerCodigoPerfil() {
		return this.perCodigoPerfil;
	}

	public void setPerCodigoPerfil(String perCodigoPerfil) {
		this.perCodigoPerfil = perCodigoPerfil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perPerfil")
	public Set<RlcPerfilDefinicionTarea> getRlcPerfilDefinicionTareas() {
		return this.rlcPerfilDefinicionTareas;
	}

	public void setRlcPerfilDefinicionTareas(Set<RlcPerfilDefinicionTarea> rlcPerfilDefinicionTareas) {
		this.rlcPerfilDefinicionTareas = rlcPerfilDefinicionTareas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perPerfil")
	public Set<RlcUsuarioPerfil> getRlcUsuarioPerfils() {
		return this.rlcUsuarioPerfils;
	}

	public void setRlcUsuarioPerfils(Set<RlcUsuarioPerfil> rlcUsuarioPerfils) {
		this.rlcUsuarioPerfils = rlcUsuarioPerfils;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perPerfil")
	public Set<RlcPerfilRolUsuario> getRlcPerfilRolUsuarios() {
		return this.rlcPerfilRolUsuarios;
	}

	public void setRlcPerfilRolUsuarios(Set<RlcPerfilRolUsuario> rlcPerfilRolUsuarios) {
		this.rlcPerfilRolUsuarios = rlcPerfilRolUsuarios;
	}


}
