package cl.servel.gasto.entity;
// default package
// Generated 09-04-2019 10:17:53 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RlcConceptoCtaGasto generated by hbm2java
 */
@Entity
@Table(name = "rlc_concepto_cta_gasto")
public class RlcConceptoCtaGasto implements java.io.Serializable {

	private Integer rlcId;
	private TpoConceptoCtaGasto tpoConceptoCtaGasto;
	private TpoCtaGasto tpoCtaGasto;

	public RlcConceptoCtaGasto() {
	}

	public RlcConceptoCtaGasto(TpoConceptoCtaGasto tpoConceptoCtaGasto, TpoCtaGasto tpoCtaGasto) {
		this.tpoConceptoCtaGasto = tpoConceptoCtaGasto;
		this.tpoCtaGasto = tpoCtaGasto;
	}

	@SequenceGenerator(name = "RlcConceptoCtaGastoIdGenerator", sequenceName = "rlc_concepto_cta_gasto_rlc_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "RlcConceptoCtaGastoIdGenerator")

	@Column(name = "rlc_id", unique = true, nullable = false)
	public Integer getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(Integer rlcId) {
		this.rlcId = rlcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_concepto_id", nullable = false)
	public TpoConceptoCtaGasto getTpoConceptoCtaGasto() {
		return this.tpoConceptoCtaGasto;
	}

	public void setTpoConceptoCtaGasto(TpoConceptoCtaGasto tpoConceptoCtaGasto) {
		this.tpoConceptoCtaGasto = tpoConceptoCtaGasto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_cta_id", nullable = false)
	public TpoCtaGasto getTpoCtaGasto() {
		return this.tpoCtaGasto;
	}

	public void setTpoCtaGasto(TpoCtaGasto tpoCtaGasto) {
		this.tpoCtaGasto = tpoCtaGasto;
	}

}
