package cl.servel.gasto.entity;
// Generated 08-11-2018 15:30:13 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RlcPartidoNivel generated by hbm2java
 */
@Entity
@Table(name = "rlc_partido_nivel")
public class RlcPartidoNivel implements java.io.Serializable {

	private Integer rlcId;
	private NivNivel nivNivel;
	private ParPartidoMaestro parPartidoMaestro;
	private TpoNivel tpoNivel;
	private Date rlcPartidoNivelFechaVigencia;
	private int eveId;

	public RlcPartidoNivel() {
	}

	public RlcPartidoNivel(NivNivel nivNivel, ParPartidoMaestro parPartidoMaestro, TpoNivel tpoNivel, int eveId) {
		this.nivNivel = nivNivel;
		this.parPartidoMaestro = parPartidoMaestro;
		this.tpoNivel = tpoNivel;
		this.eveId = eveId;
	}

	public RlcPartidoNivel(NivNivel nivNivel, ParPartidoMaestro parPartidoMaestro, TpoNivel tpoNivel,
			Date rlcPartidoNivelFechaVigencia, int eveId) {
		this.nivNivel = nivNivel;
		this.parPartidoMaestro = parPartidoMaestro;
		this.tpoNivel = tpoNivel;
		this.rlcPartidoNivelFechaVigencia = rlcPartidoNivelFechaVigencia;
		this.eveId = eveId;
	}

	@SequenceGenerator(name = "cl.servel.gasto.entity.RlcPartidoNivelIdGenerator", sequenceName = "rlc_partido_nivel_rlc_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.entity.RlcPartidoNivelIdGenerator")

	@Column(name = "rlc_id", unique = true, nullable = false)
	public Integer getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(Integer rlcId) {
		this.rlcId = rlcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "niv_id", nullable = false)
	public NivNivel getNivNivel() {
		return this.nivNivel;
	}

	public void setNivNivel(NivNivel nivNivel) {
		this.nivNivel = nivNivel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_par_partido_maestro", nullable = false)
	public ParPartidoMaestro getParPartidoMaestro() {
		return this.parPartidoMaestro;
	}

	public void setParPartidoMaestro(ParPartidoMaestro parPartidoMaestro) {
		this.parPartidoMaestro = parPartidoMaestro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_niv_codigo", nullable = false)
	public TpoNivel getTpoNivel() {
		return this.tpoNivel;
	}

	public void setTpoNivel(TpoNivel tpoNivel) {
		this.tpoNivel = tpoNivel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "rlc_partido_nivel_fecha_vigencia", length = 13)
	public Date getRlcPartidoNivelFechaVigencia() {
		return this.rlcPartidoNivelFechaVigencia;
	}

	public void setRlcPartidoNivelFechaVigencia(Date rlcPartidoNivelFechaVigencia) {
		this.rlcPartidoNivelFechaVigencia = rlcPartidoNivelFechaVigencia;
	}

	@Column(name = "eve_id", nullable = false)
	public int getEveId() {
		return this.eveId;
	}

	public void setEveId(int eveId) {
		this.eveId = eveId;
	}

}
