package cl.servel.gasto.entity;
// Generated 04-10-2018 19:09:57 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RlcRelNivel generated by hbm2java
 */
@Entity
@Table(name = "rlc_rel_nivel")
public class RlcRelNivel implements java.io.Serializable {

	private Integer rlcId;
	private EveEventoEleccionario eveEventoEleccionario;
	private NivNivel nivNivelByNivIdPadre;
	private NivNivel nivNivelByNivIdHijo;
	private TpoNivel tpoNivelByTpoNivCodigoHijo;
	private TpoNivel tpoNivelByTpoNivCodigoPadre;
	private Integer rlcOrdenPresedencia;

	public RlcRelNivel() {
	}

	public RlcRelNivel(EveEventoEleccionario eveEventoEleccionario, NivNivel nivNivelByNivIdPadre,
			NivNivel nivNivelByNivIdHijo, TpoNivel tpoNivelByTpoNivCodigoHijo, TpoNivel tpoNivelByTpoNivCodigoPadre) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.nivNivelByNivIdPadre = nivNivelByNivIdPadre;
		this.nivNivelByNivIdHijo = nivNivelByNivIdHijo;
		this.tpoNivelByTpoNivCodigoHijo = tpoNivelByTpoNivCodigoHijo;
		this.tpoNivelByTpoNivCodigoPadre = tpoNivelByTpoNivCodigoPadre;
	}

	public RlcRelNivel(EveEventoEleccionario eveEventoEleccionario, NivNivel nivNivelByNivIdPadre,
			NivNivel nivNivelByNivIdHijo, TpoNivel tpoNivelByTpoNivCodigoHijo, TpoNivel tpoNivelByTpoNivCodigoPadre,
			Integer rlcOrdenPresedencia) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.nivNivelByNivIdPadre = nivNivelByNivIdPadre;
		this.nivNivelByNivIdHijo = nivNivelByNivIdHijo;
		this.tpoNivelByTpoNivCodigoHijo = tpoNivelByTpoNivCodigoHijo;
		this.tpoNivelByTpoNivCodigoPadre = tpoNivelByTpoNivCodigoPadre;
		this.rlcOrdenPresedencia = rlcOrdenPresedencia;
	}

	@SequenceGenerator(name = "cl.servel.gasto.entity.RlcRelNivelIdGenerator", sequenceName = "rlc_rel_nivel_rlc_id_seq", initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.entity.RlcRelNivelIdGenerator")

	@Column(name = "rlc_id", unique = true, nullable = false)
	public Integer getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(Integer rlcId) {
		this.rlcId = rlcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "niv_id_padre", nullable = false)
	public NivNivel getNivNivelByNivIdPadre() {
		return this.nivNivelByNivIdPadre;
	}

	public void setNivNivelByNivIdPadre(NivNivel nivNivelByNivIdPadre) {
		this.nivNivelByNivIdPadre = nivNivelByNivIdPadre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "niv_id_hijo", nullable = false)
	public NivNivel getNivNivelByNivIdHijo() {
		return this.nivNivelByNivIdHijo;
	}

	public void setNivNivelByNivIdHijo(NivNivel nivNivelByNivIdHijo) {
		this.nivNivelByNivIdHijo = nivNivelByNivIdHijo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_niv_codigo_hijo", nullable = false)
	public TpoNivel getTpoNivelByTpoNivCodigoHijo() {
		return this.tpoNivelByTpoNivCodigoHijo;
	}

	public void setTpoNivelByTpoNivCodigoHijo(TpoNivel tpoNivelByTpoNivCodigoHijo) {
		this.tpoNivelByTpoNivCodigoHijo = tpoNivelByTpoNivCodigoHijo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_niv_codigo_padre", nullable = false)
	public TpoNivel getTpoNivelByTpoNivCodigoPadre() {
		return this.tpoNivelByTpoNivCodigoPadre;
	}

	public void setTpoNivelByTpoNivCodigoPadre(TpoNivel tpoNivelByTpoNivCodigoPadre) {
		this.tpoNivelByTpoNivCodigoPadre = tpoNivelByTpoNivCodigoPadre;
	}

	@Column(name = "rlc_orden_presedencia")
	public Integer getRlcOrdenPresedencia() {
		return this.rlcOrdenPresedencia;
	}

	public void setRlcOrdenPresedencia(Integer rlcOrdenPresedencia) {
		this.rlcOrdenPresedencia = rlcOrdenPresedencia;
	}

}
