package cl.servel.gasto.entity;
// Generated 26-11-2018 23:25:02 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * RlcSubpactoPartido generated by hbm2java
 */
@Entity
@Table(name = "rlc_subpacto_partido")
public class RlcSubpactoPartido implements java.io.Serializable {

	private Integer rlcId;
	private EleEleccion eleEleccion;
	private ParPartido parPartido;
	private SpaPacto spaPacto;

	public RlcSubpactoPartido() {
	}

	public RlcSubpactoPartido(EleEleccion eleEleccion, ParPartido parPartido, SpaPacto spaPacto) {
		this.eleEleccion = eleEleccion;
		this.parPartido = parPartido;
		this.spaPacto = spaPacto;
	}

	@SequenceGenerator(name = "RlcSubpactoPartidoIdGenerator", sequenceName = "rlc_subpacto_partido_rlc_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "RlcSubpactoPartidoIdGenerator")

	@Column(name = "rlc_id", unique = true, nullable = false)
	public Integer getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(Integer rlcId) {
		this.rlcId = rlcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ele_id", nullable = false)
	public EleEleccion getEleEleccion() {
		return this.eleEleccion;
	}

	public void setEleEleccion(EleEleccion eleEleccion) {
		this.eleEleccion = eleEleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "par_id", nullable = false)
	public ParPartido getParPartido() {
		return this.parPartido;
	}

	public void setParPartido(ParPartido parPartido) {
		this.parPartido = parPartido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "spa_id", nullable = false)
	public SpaPacto getSpaPacto() {
		return this.spaPacto;
	}

	public void setSpaPacto(SpaPacto spaPacto) {
		this.spaPacto = spaPacto;
	}

}
