package cl.servel.gasto.entity;
// Generated 04-10-2018 19:09:57 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * SelSubEleccion generated by hbm2java
 */
@Entity
@Table(name = "sel_sub_eleccion")
public class SelSubEleccion implements java.io.Serializable {

	private Integer selId;
	private EleEleccion eleEleccion;
	private EveEventoEleccionario eveEventoEleccionario;
	private NivNivel nivNivel;
	private TpoNivel tpoNivel;
	private String selNombre;
	private String selCodigoOrigen;
	private Boolean selEliminado;
	private Date selModified;
	private Date selCreated;
	private Integer selCantidadElectores;
	private Integer selCantidadCandidatos;
	
	private Set<CanCandidato> canCandidatos = new HashSet<CanCandidato>(0);

	public SelSubEleccion() {
	}

	public SelSubEleccion(EleEleccion eleEleccion, EveEventoEleccionario eveEventoEleccionario, NivNivel nivNivel,
			TpoNivel tpoNivel) {
		this.eleEleccion = eleEleccion;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.nivNivel = nivNivel;
		this.tpoNivel = tpoNivel;
	}

	public SelSubEleccion(EleEleccion eleEleccion, EveEventoEleccionario eveEventoEleccionario, NivNivel nivNivel,
			TpoNivel tpoNivel, String selNombre, String selCodigoOrigen, Boolean selEliminado, Date selModified,
			Date selCreated, Integer selCantidadElectores,Integer selCantidadCandidatos, Set<CanCandidato> canCandidatos) {
		this.eleEleccion = eleEleccion;
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.nivNivel = nivNivel;
		this.tpoNivel = tpoNivel;
		this.selNombre = selNombre;
		this.selCodigoOrigen = selCodigoOrigen;
		this.selEliminado = selEliminado;
		this.selModified = selModified;
		this.selCreated = selCreated;
		this.selCantidadElectores = selCantidadElectores;
		this.selCantidadCandidatos = selCantidadCandidatos;
		this.canCandidatos = canCandidatos;
	}

	@SequenceGenerator(name = "cl.servel.gasto.entity.SelSubEleccionIdGenerator", sequenceName = "sel_sub_eleccion_sel_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.entity.SelSubEleccionIdGenerator")

	@Column(name = "sel_id", unique = true, nullable = false)
	public Integer getSelId() {
		return this.selId;
	}

	public void setSelId(Integer selId) {
		this.selId = selId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ele_id", nullable = false)
	public EleEleccion getEleEleccion() {
		return this.eleEleccion;
	}

	public void setEleEleccion(EleEleccion eleEleccion) {
		this.eleEleccion = eleEleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "niv_id", nullable = false)
	public NivNivel getNivNivel() {
		return this.nivNivel;
	}

	public void setNivNivel(NivNivel nivNivel) {
		this.nivNivel = nivNivel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_niv_codigo", nullable = false)
	public TpoNivel getTpoNivel() {
		return this.tpoNivel;
	}

	public void setTpoNivel(TpoNivel tpoNivel) {
		this.tpoNivel = tpoNivel;
	}

	@Column(name = "sel_nombre", length = 50)
	public String getSelNombre() {
		return this.selNombre;
	}

	public void setSelNombre(String selNombre) {
		this.selNombre = selNombre;
	}

	@Column(name = "sel_codigo_origen", length = 5)
	public String getSelCodigoOrigen() {
		return this.selCodigoOrigen;
	}

	public void setSelCodigoOrigen(String selCodigoOrigen) {
		this.selCodigoOrigen = selCodigoOrigen;
	}

	@Column(name = "sel_eliminado")
	public Boolean getSelEliminado() {
		return this.selEliminado;
	}

	public void setSelEliminado(Boolean selEliminado) {
		this.selEliminado = selEliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sel_modified", length = 13)
	public Date getSelModified() {
		return this.selModified;
	}

	public void setSelModified(Date selModified) {
		this.selModified = selModified;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sel_created", length = 13)
	public Date getSelCreated() {
		return this.selCreated;
	}

	public void setSelCreated(Date selCreated) {
		this.selCreated = selCreated;
	}

	@Column(name = "sel_cantidad_electores")
	public Integer getSelCantidadElectores() {
		return this.selCantidadElectores;
	}

	public void setSelCantidadElectores(Integer selCantidadElectores) {
		this.selCantidadElectores = selCantidadElectores;
	}

	@Column(name = "sel_cantidad_candidatos")
	public Integer getSelCantidadCandidatos() {
		return this.selCantidadCandidatos;
	}

	public void setSelCantidadCandidatos(Integer selCantidadCandidatos) {
		this.selCantidadCandidatos = selCantidadCandidatos;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "selSubEleccion")
	public Set<CanCandidato> getCanCandidatos() {
		return this.canCandidatos;
	}

	public void setCanCandidatos(Set<CanCandidato> canCandidatos) {
		this.canCandidatos = canCandidatos;
	}

}
