package cl.servel.gasto.entity;
// Generated 26-11-2018 23:25:02 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SpaPacto generated by hbm2java
 */
@Entity
@Table(name = "spa_pacto")
public class SpaPacto implements java.io.Serializable {

	private Integer spaId;
	private EleEleccion eleEleccion;
	private PacPacto pacPacto;
	private String spaSigla;
	private Boolean spaEliminado;
	private Date created;
	private Date modified;
	private String spaNombre;
	private String spaCodigoOrigen;
	private Set<RlcSubpactoPartido> rlcSubpactoPartidos = new HashSet<RlcSubpactoPartido>(0);
	private Set<CanCandidato> canCandidatos = new HashSet<CanCandidato>(0);

	public SpaPacto() {
	}

	public SpaPacto(EleEleccion eleEleccion, PacPacto pacPacto) {
		this.eleEleccion = eleEleccion;
		this.pacPacto = pacPacto;
	}

	public SpaPacto(EleEleccion eleEleccion, PacPacto pacPacto, String spaSigla, Boolean spaEliminado, Date created,
			Date modified, String spaNombre, String spaCodigoOrigen, Set<RlcSubpactoPartido> rlcSubpactoPartidos,
			Set<CanCandidato> canCandidatos) {
		this.eleEleccion = eleEleccion;
		this.pacPacto = pacPacto;
		this.spaSigla = spaSigla;
		this.spaEliminado = spaEliminado;
		this.created = created;
		this.modified = modified;
		this.spaNombre = spaNombre;
		this.spaCodigoOrigen = spaCodigoOrigen;
		this.rlcSubpactoPartidos = rlcSubpactoPartidos;
		this.canCandidatos = canCandidatos;
	}

	@SequenceGenerator(name = "SpaPactoIdGenerator", sequenceName = "spa_pacto_spa_id_seq", initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "SpaPactoIdGenerator")

	@Column(name = "spa_id", unique = true, nullable = false)
	public Integer getSpaId() {
		return this.spaId;
	}

	public void setSpaId(Integer spaId) {
		this.spaId = spaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ele_id", nullable = false)
	public EleEleccion getEleEleccion() {
		return this.eleEleccion;
	}

	public void setEleEleccion(EleEleccion eleEleccion) {
		this.eleEleccion = eleEleccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pac_codigo", nullable = false)
	public PacPacto getPacPacto() {
		return this.pacPacto;
	}

	public void setPacPacto(PacPacto pacPacto) {
		this.pacPacto = pacPacto;
	}

	@Column(name = "spa_sigla", length = 5)
	public String getSpaSigla() {
		return this.spaSigla;
	}

	public void setSpaSigla(String spaSigla) {
		this.spaSigla = spaSigla;
	}

	@Column(name = "spa_eliminado")
	public Boolean getSpaEliminado() {
		return this.spaEliminado;
	}

	public void setSpaEliminado(Boolean spaEliminado) {
		this.spaEliminado = spaEliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", length = 13)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified", length = 13)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "spa_nombre", length = 80)
	public String getSpaNombre() {
		return this.spaNombre;
	}

	public void setSpaNombre(String spaNombre) {
		this.spaNombre = spaNombre;
	}

	@Column(name = "spa_codigo_origen", length = 8)
	public String getSpaCodigoOrigen() {
		return this.spaCodigoOrigen;
	}

	public void setSpaCodigoOrigen(String spaCodigoOrigen) {
		this.spaCodigoOrigen = spaCodigoOrigen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spaPacto")
	public Set<RlcSubpactoPartido> getRlcSubpactoPartidos() {
		return this.rlcSubpactoPartidos;
	}

	public void setRlcSubpactoPartidos(Set<RlcSubpactoPartido> rlcSubpactoPartidos) {
		this.rlcSubpactoPartidos = rlcSubpactoPartidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "spaPacto")
	public Set<CanCandidato> getCanCandidatos() {
		return this.canCandidatos;
	}

	public void setCanCandidatos(Set<CanCandidato> canCandidatos) {
		this.canCandidatos = canCandidatos;
	}

}
