package cl.servel.gasto.entity;
// Generated 08-10-2019 17:40:35 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpoAdministrador generated by hbm2java
 */
@Entity
@Table(name = "tpo_administrador")
public class TpoAdministrador implements java.io.Serializable {

	private Integer tpoAdministradorId;
	private String tpoAdmNombre;
	private Boolean tpoAdmEliminado;
	private Date tpoAdmCreated;
	private Date tpoAdmModified;
	private Set<AdmAdministradorElectoral> admAdministradorElectorals = new HashSet<AdmAdministradorElectoral>(0);

	public TpoAdministrador() {
	}

	public TpoAdministrador(String tpoAdmNombre, Boolean tpoAdmEliminado, Date tpoAdmCreated, Date tpoAdmModified,
			Set<AdmAdministradorElectoral> admAdministradorElectorals) {
		this.tpoAdmNombre = tpoAdmNombre;
		this.tpoAdmEliminado = tpoAdmEliminado;
		this.tpoAdmCreated = tpoAdmCreated;
		this.tpoAdmModified = tpoAdmModified;
		this.admAdministradorElectorals = admAdministradorElectorals;
	}

	@SequenceGenerator(name = "cl.servel.gasto.temporal.TpoAdministradorIdGenerator", sequenceName = "tpo_administrador_tpo_administrador_id_seq",initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.temporal.TpoAdministradorIdGenerator")

	@Column(name = "tpo_administrador_id", unique = true, nullable = false)
	public Integer getTpoAdministradorId() {
		return this.tpoAdministradorId;
	}

	public void setTpoAdministradorId(Integer tpoAdministradorId) {
		this.tpoAdministradorId = tpoAdministradorId;
	}

	@Column(name = "tpo_adm_nombre", length = 50)
	public String getTpoAdmNombre() {
		return this.tpoAdmNombre;
	}

	public void setTpoAdmNombre(String tpoAdmNombre) {
		this.tpoAdmNombre = tpoAdmNombre;
	}

	@Column(name = "tpo_adm_eliminado")
	public Boolean getTpoAdmEliminado() {
		return this.tpoAdmEliminado;
	}

	public void setTpoAdmEliminado(Boolean tpoAdmEliminado) {
		this.tpoAdmEliminado = tpoAdmEliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tpo_adm_created", length = 13)
	public Date getTpoAdmCreated() {
		return this.tpoAdmCreated;
	}

	public void setTpoAdmCreated(Date tpoAdmCreated) {
		this.tpoAdmCreated = tpoAdmCreated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tpo_adm_modified", length = 13)
	public Date getTpoAdmModified() {
		return this.tpoAdmModified;
	}

	public void setTpoAdmModified(Date tpoAdmModified) {
		this.tpoAdmModified = tpoAdmModified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoAdministrador")
	public Set<AdmAdministradorElectoral> getAdmAdministradorElectorals() {
		return this.admAdministradorElectorals;
	}

	public void setAdmAdministradorElectorals(Set<AdmAdministradorElectoral> admAdministradorElectorals) {
		this.admAdministradorElectorals = admAdministradorElectorals;
	}

}
