package cl.servel.gasto.entity;
// Generated 09-04-2019 10:17:53 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TpoCtaGasto generated by hbm2java
 */
@Entity
@Table(name = "tpo_cta_gasto")
public class TpoCtaGasto implements java.io.Serializable {

	private Integer tpoCtaId;
	private EveEventoEleccionario eveEventoEleccionario;
	private TpoRendicion tpoRendicion;
	private int tpoCtaCodigo;
	private String tpoCtaNombre;
	private Set<RlcConceptoCtaGasto> rlcConceptoCtaGastos = new HashSet<RlcConceptoCtaGasto>(0);
	private Set<TpoObservacion> tpoObservacions = new HashSet<TpoObservacion>(0);

	public TpoCtaGasto() {
	}

	public TpoCtaGasto(EveEventoEleccionario eveEventoEleccionario, TpoRendicion tpoRendicion, int tpoCtaCodigo) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoRendicion = tpoRendicion;
		this.tpoCtaCodigo = tpoCtaCodigo;
	}

	public TpoCtaGasto(EveEventoEleccionario eveEventoEleccionario, TpoRendicion tpoRendicion, int tpoCtaCodigo,
			String tpoCtaNombre, Set<RlcConceptoCtaGasto> rlcConceptoCtaGastos, Set<TpoObservacion> tpoObservacions) {
		this.eveEventoEleccionario = eveEventoEleccionario;
		this.tpoRendicion = tpoRendicion;
		this.tpoCtaCodigo = tpoCtaCodigo;
		this.tpoCtaNombre = tpoCtaNombre;
		this.rlcConceptoCtaGastos = rlcConceptoCtaGastos;
		this.tpoObservacions = tpoObservacions;
	}

	@SequenceGenerator(name = "TpoCtaGastoIdGenerator", sequenceName = "tpo_cta_gasto_tpo_cta_id_seq", initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "TpoCtaGastoIdGenerator")

	@Column(name = "tpo_cta_id", unique = true, nullable = false)
	public Integer getTpoCtaId() {
		return this.tpoCtaId;
	}

	public void setTpoCtaId(Integer tpoCtaId) {
		this.tpoCtaId = tpoCtaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "eve_id", nullable = false)
	public EveEventoEleccionario getEveEventoEleccionario() {
		return this.eveEventoEleccionario;
	}

	public void setEveEventoEleccionario(EveEventoEleccionario eveEventoEleccionario) {
		this.eveEventoEleccionario = eveEventoEleccionario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tpo_rendicion_id", nullable = false)
	public TpoRendicion getTpoRendicion() {
		return this.tpoRendicion;
	}

	public void setTpoRendicion(TpoRendicion tpoRendicion) {
		this.tpoRendicion = tpoRendicion;
	}

	@Column(name = "tpo_cta_codigo", nullable = false)
	public int getTpoCtaCodigo() {
		return this.tpoCtaCodigo;
	}

	public void setTpoCtaCodigo(int tpoCtaCodigo) {
		this.tpoCtaCodigo = tpoCtaCodigo;
	}

	@Column(name = "tpo_cta_nombre", length = 100)
	public String getTpoCtaNombre() {
		return this.tpoCtaNombre;
	}

	public void setTpoCtaNombre(String tpoCtaNombre) {
		this.tpoCtaNombre = tpoCtaNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoCtaGasto")
	public Set<RlcConceptoCtaGasto> getRlcConceptoCtaGastos() {
		return this.rlcConceptoCtaGastos;
	}

	public void setRlcConceptoCtaGastos(Set<RlcConceptoCtaGasto> rlcConceptoCtaGastos) {
		this.rlcConceptoCtaGastos = rlcConceptoCtaGastos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoCtaGasto")
	public Set<TpoObservacion> getTpoObservacions() {
		return this.tpoObservacions;
	}

	public void setTpoObservacions(Set<TpoObservacion> tpoObservacions) {
		this.tpoObservacions = tpoObservacions;
	}
}
