package cl.servel.gasto.entity;
// Generated 21-06-2019 12:42:33 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpoCandidato generated by hbm2java
 */
@Entity
@Table(name = "tpo_candidato")
public class TpoCandidato implements java.io.Serializable {

	private Integer tpoCandidatoId;
	private String tpoNombre;
	private Date tpoCreated;
	private Boolean tpoCanEliminado;
	private Date modified;
	private Set<CanCandidato> canCandidatos = new HashSet<CanCandidato>(0);

	public TpoCandidato() {
	}

	public TpoCandidato(String tpoNombre, Date tpoCreated, Boolean tpoCanEliminado, Date modified,
			Set<CanCandidato> canCandidatos) {
		this.tpoNombre = tpoNombre;
		this.tpoCreated = tpoCreated;
		this.tpoCanEliminado = tpoCanEliminado;
		this.modified = modified;
		this.canCandidatos = canCandidatos;
	}

	@Id
	@Column(name = "tpo_candidato_id", unique = true, nullable = false)
	public Integer getTpoCandidatoId() {
		return this.tpoCandidatoId;
	}

	public void setTpoCandidatoId(Integer tpoCandidatoId) {
		this.tpoCandidatoId = tpoCandidatoId;
	}

	@Column(name = "tpo_nombre", length = 40)
	public String getTpoNombre() {
		return this.tpoNombre;
	}

	public void setTpoNombre(String tpoNombre) {
		this.tpoNombre = tpoNombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "tpo_created", length = 13)
	public Date getTpoCreated() {
		return this.tpoCreated;
	}

	public void setTpoCreated(Date tpoCreated) {
		this.tpoCreated = tpoCreated;
	}

	@Column(name = "tpo_can_eliminado")
	public Boolean getTpoCanEliminado() {
		return this.tpoCanEliminado;
	}

	public void setTpoCanEliminado(Boolean tpoCanEliminado) {
		this.tpoCanEliminado = tpoCanEliminado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "modified", length = 13)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoCandidato")
	public Set<CanCandidato> getCanCandidatos() {
		return this.canCandidatos;
	}

	public void setCanCandidatos(Set<CanCandidato> canCandidatos) {
		this.canCandidatos = canCandidatos;
	}

}
