package cl.servel.gasto.entity;
// Generated 17-10-2018 19:38:14 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TpoCtaBancaria generated by hbm2java
 */
@Entity
@Table(name = "tpo_cta_bancaria")
public class TpoCtaBancaria implements java.io.Serializable {

	private Integer tpoCtaBancariaId;
	private String tpoNombreCuenta;
	private Set<CctCuentaContable> cctCuentaContables = new HashSet<CctCuentaContable>(0);

	public TpoCtaBancaria() {
	}

	public TpoCtaBancaria(String tpoNombreCuenta, Set<CctCuentaContable> cctCuentaContables) {
		this.tpoNombreCuenta = tpoNombreCuenta;
		this.cctCuentaContables = cctCuentaContables;
	}

	@SequenceGenerator(name = "cl.servel.gasto.entity.TpoCtaBancariaIdGenerator", sequenceName = "tpo_cta_bancaria_tpo_cta_bancaria_id_seq", initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "cl.servel.gasto.entity.TpoCtaBancariaIdGenerator")

	@Column(name = "tpo_cta_bancaria_id", unique = true, nullable = false)
	public Integer getTpoCtaBancariaId() {
		return this.tpoCtaBancariaId;
	}

	public void setTpoCtaBancariaId(Integer tpoCtaBancariaId) {
		this.tpoCtaBancariaId = tpoCtaBancariaId;
	}

	@Column(name = "tpo_nombre_cuenta", length = 50)
	public String getTpoNombreCuenta() {
		return this.tpoNombreCuenta;
	}

	public void setTpoNombreCuenta(String tpoNombreCuenta) {
		this.tpoNombreCuenta = tpoNombreCuenta;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoCtaBancaria")
	public Set<CctCuentaContable> getCctCuentaContables() {
		return this.cctCuentaContables;
	}

	public void setCctCuentaContables(Set<CctCuentaContable> cctCuentaContables) {
		this.cctCuentaContables = cctCuentaContables;
	}

}
