package cl.servel.gasto.entity;
// Generated 28-05-2019 17:59:23 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.SEQUENCE;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TpoRecomendacion generated by hbm2java
 */
@Entity
@Table(name = "tpo_recomendacion")
public class TpoRecomendacion implements java.io.Serializable {

	private Integer tpoRecId;
	private String tpoNombreRecomendacion;

	public TpoRecomendacion() {
	}

	public TpoRecomendacion(String tpoNombreRecomendacion) {
		this.tpoNombreRecomendacion = tpoNombreRecomendacion;
	}

	@SequenceGenerator(name = "TpoRecomendacionIdGenerator", sequenceName = "tpo_recomendacion_tpo_recomendacion_id_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "TpoRecomendacionIdGenerator")

	@Column(name = "tpo_rec_id", unique = true, nullable = false)
	public Integer getTpoRecId() {
		return this.tpoRecId;
	}

	public void setTpoRecId(Integer tpoRecId) {
		this.tpoRecId = tpoRecId;
	}

	@Column(name = "tpo_nombre_recomendacion", nullable = false, length = 100)
	public String getTpoNombreRecomendacion() {
		return this.tpoNombreRecomendacion;
	}

	public void setTpoNombreRecomendacion(String tpoNombreRecomendacion) {
		this.tpoNombreRecomendacion = tpoNombreRecomendacion;
	}

}
