package cl.servel.gasto.entity;
// Generated 14-08-2019 18:11:24 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TpoTipos generated by hbm2java
 */
@Entity
@Table(name = "tpo_tipos")
public class TpoTipos implements java.io.Serializable {

	private Integer tpoId;
	private String tpoCodigo;
	private String tpoDescripcion;
	private String tpoCodAgrupacion;
	private Set<NomNomina> nomNominas = new HashSet<NomNomina>(0);
	private Set<IngIngresos> ingIngresoses = new HashSet<IngIngresos>(0);
	private Set<DetDetalleNomina> detDetalleNominas = new HashSet<DetDetalleNomina>(0);

	public TpoTipos() {
	}

	public TpoTipos(String tpoCodigo, String tpoDescripcion, String tpoCodAgrupacion) {
		this.tpoCodigo = tpoCodigo;
		this.tpoDescripcion = tpoDescripcion;
		this.tpoCodAgrupacion = tpoCodAgrupacion;
	}

	public TpoTipos(String tpoCodigo, String tpoDescripcion, String tpoCodAgrupacion, Set<NomNomina> nomNominas,
			Set<IngIngresos> ingIngresoses, Set<DetDetalleNomina> detDetalleNominas) {
		this.tpoCodigo = tpoCodigo;
		this.tpoDescripcion = tpoDescripcion;
		this.tpoCodAgrupacion = tpoCodAgrupacion;
		this.nomNominas = nomNominas;
		this.ingIngresoses = ingIngresoses;
		this.detDetalleNominas = detDetalleNominas;
	}

	@SequenceGenerator(name = "TpoTiposIdGenerator", sequenceName = "tpo_tipos_tpo_id_seq", initialValue=1, allocationSize=1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "TpoTiposIdGenerator")

	@Column(name = "tpo_id", unique = true, nullable = false)
	public Integer getTpoId() {
		return this.tpoId;
	}

	public void setTpoId(Integer tpoId) {
		this.tpoId = tpoId;
	}

	@Column(name = "tpo_codigo", nullable = false, length = 15)
	public String getTpoCodigo() {
		return this.tpoCodigo;
	}

	public void setTpoCodigo(String tpoCodigo) {
		this.tpoCodigo = tpoCodigo;
	}

	@Column(name = "tpo_descripcion", nullable = false, length = 50)
	public String getTpoDescripcion() {
		return this.tpoDescripcion;
	}

	public void setTpoDescripcion(String tpoDescripcion) {
		this.tpoDescripcion = tpoDescripcion;
	}

	@Column(name = "tpo_cod_agrupacion", nullable = false, length = 10)
	public String getTpoCodAgrupacion() {
		return this.tpoCodAgrupacion;
	}

	public void setTpoCodAgrupacion(String tpoCodAgrupacion) {
		this.tpoCodAgrupacion = tpoCodAgrupacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoTipos")
	public Set<NomNomina> getNomNominas() {
		return this.nomNominas;
	}

	public void setNomNominas(Set<NomNomina> nomNominas) {
		this.nomNominas = nomNominas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoTipos")
	public Set<IngIngresos> getIngIngresoses() {
		return this.ingIngresoses;
	}

	public void setIngIngresoses(Set<IngIngresos> ingIngresoses) {
		this.ingIngresoses = ingIngresoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tpoTipos")
	public Set<DetDetalleNomina> getDetDetalleNominas() {
		return this.detDetalleNominas;
	}

	public void setDetDetalleNominas(Set<DetDetalleNomina> detDetalleNominas) {
		this.detDetalleNominas = detDetalleNominas;
	}

}
